#!/usr/bin/env python3
import json

# Additional questions 11-20 for each topic (from the new batch)

# Topic 1: Verben konjugieren – Questions 11-20
add_a1_01 = [
    {"id": "a1_01_q011", "subjectId": "a1_01", "type": "multiple_choice", "questionText": "\"Die Studenten ___ müde nach der Prüfung.\" – Was fehlt?", "options": ["haben", "sind", "ist", "wird"], "correctAnswer": "sind", "explanation": "Die Studenten (Plural) → sind; müde sein", "difficulty": "easy", "topicName": "Verben konjugieren (sein, haben, werden)"},
    {"id": "a1_01_q012", "subjectId": "a1_01", "type": "multiple_choice", "questionText": "Welche Konjugation ist falsch? \"Er ___ kein Geld.\"", "options": ["hat", "hätte", "haben", "hatte"], "correctAnswer": "haben", "explanation": "Er (3.Pers Sg) → hat; haben ist nur für wir/sie/ihr", "difficulty": "medium", "topicName": "Verben konjugieren (sein, haben, werden)"},
    {"id": "a1_01_q013", "subjectId": "a1_01", "type": "multiple_choice", "questionText": "\"___ du glücklich?\" – Welches Verb passt?", "options": ["Hast", "Bist", "Wirst", "Sei"], "correctAnswer": "Bist", "explanation": "Glücklich sein → du bist glücklich (sein)", "difficulty": "easy", "topicName": "Verben konjugieren (sein, haben, werden)"},
    {"id": "a1_01_q014", "subjectId": "a1_01", "type": "multiple_choice", "questionText": "\"Wir ___ nächstes Jahr nach Berlin ziehen.\" (Plan)", "options": ["werden", "sind", "haben", "wird"], "correctAnswer": "werden", "explanation": "werden: Zukunftsplan / Vorhersage", "difficulty": "easy", "topicName": "Verben konjugieren (sein, haben, werden)"},
    {"id": "a1_01_q015", "subjectId": "a1_01", "type": "multiple_choice", "questionText": "Welcher Satz ist korrekt?", "options": ["Ich habe Hunger.", "Ich bin Hunger.", "Ich werde Hunger.", "Ich habe hungrig."], "correctAnswer": "Ich habe Hunger.", "explanation": "Hunger haben (nicht: hunger sein)", "difficulty": "easy", "topicName": "Verben konjugieren (sein, haben, werden)"},
    {"id": "a1_01_q016", "subjectId": "a1_01", "type": "multiple_choice", "questionText": "\"Die Katze ___ auf dem Sofa.\" – Was fehlt?", "options": ["haben", "sind", "ist", "wird"], "correctAnswer": "ist", "explanation": "Die Katze (Sg) → ist; auf dem Sofa (Ort)", "difficulty": "easy", "topicName": "Verben konjugieren (sein, haben, werden)"},
    {"id": "a1_01_q017", "subjectId": "a1_01", "type": "multiple_choice", "questionText": "\"Ich ___ krank, als ich gestern Eis gegessen habe.\"", "options": ["bin", "war", "habe", "werde"], "correctAnswer": "war", "explanation": "Präteritum von sein: ich war (gestern)", "difficulty": "easy", "topicName": "Verben konjugieren (sein, haben, werden)"},
    {"id": "a1_01_q018", "subjectId": "a1_01", "type": "multiple_choice", "questionText": "\"Ihr ___ immer so laut!\" – Was ist die richtige Form von \"sein\"?", "options": ["seid", "seist", "seiet", "seid ihr"], "correctAnswer": "seid", "explanation": "ihr → seid (Konjugation von sein)", "difficulty": "easy", "topicName": "Verben konjugieren (sein, haben, werden)"},
    {"id": "a1_01_q019", "subjectId": "a1_01", "type": "multiple_choice", "questionText": "\"Er ___ Arzt, aber er ___ jetzt arbeitslos.\" – Welche Verben passen?", "options": ["ist / ist", "war / ist", "ist / war", "wird / hat"], "correctAnswer": "ist / ist", "explanation": "Zwei Zustände: ist Arzt + ist arbeitslos", "difficulty": "medium", "topicName": "Verben konjugieren (sein, haben, werden)"},
    {"id": "a1_01_q020", "subjectId": "a1_01", "type": "multiple_choice", "questionText": "\"Sie ___ Ausländerin und ___ jetzt Deutsch.\" – Was fehlt?", "options": ["ist / lernt", "war / lernt", "ist / lernte", "sei / lernt"], "correctAnswer": "ist / lernt", "explanation": "ist (Zustand) + lernt (laufende Handlung)", "difficulty": "medium", "topicName": "Verben konjugieren (sein, haben, werden)"},
]

# Topic 2: Nomen und Artikel – Questions 11-20
add_a1_02 = [
    {"id": "a1_02_q011", "subjectId": "a1_02", "type": "multiple_choice", "questionText": "\"___ Schuhe sind neu.\" – Welcher Artikel passt?", "options": ["Das", "Der", "Die", "Ein"], "correctAnswer": "Die", "explanation": "Schuhe ist Plural → die Schuhe", "difficulty": "easy", "topicName": "Nomen und Artikel (der/die/das + Pluralformen)"},
    {"id": "a1_02_q012", "subjectId": "a1_02", "type": "multiple_choice", "questionText": "Was ist der Plural von \"die Tür\"?", "options": ["die Türen", "die Türe", "die Türs", "die Türen"], "correctAnswer": "die Türen", "explanation": "die Tür → die Türen (Umlaut ä)", "difficulty": "easy", "topicName": "Nomen und Artikel (der/die/das + Pluralformen)"},
    {"id": "a1_02_q013", "subjectId": "a1_02", "type": "multiple_choice", "questionText": "\"der Bahnhof\" – Welche Pluralform ist korrekt?", "options": ["die Bahnhöfe", "die Bahnhofs", "die Bahnhof", "die Bahnhöfen"], "correctAnswer": "die Bahnhöfe", "explanation": "der Bahnhof → die Bahnhöfe (Umlaut)", "difficulty": "easy", "topicName": "Nomen und Artikel (der/die/das + Pluralformen)"},
    {"id": "a1_02_q014", "subjectId": "a1_02", "type": "multiple_choice", "questionText": "Welcher Satz ist FALSCH?", "options": ["Die Lampe ist neu.", "Ein Auto steht vor dem Haus.", "Der Kinder spielen im Garten.", "Das Haus ist groß."], "correctAnswer": "Der Kinder spielen im Garten.", "explanation": "Richtig: Die Kinder spielen (Kinder ist Plural)", "difficulty": "easy", "topicName": "Nomen und Artikel (der/die/das + Pluralformen)"},
    {"id": "a1_02_q015", "subjectId": "a1_02", "type": "multiple_choice", "questionText": "\"Ich brauche ___ Computer.\" – Welcher Artikel passt hier?", "options": ["der", "die", "das", "einen"], "correctAnswer": "einen", "explanation": "Akkusativ maskulin: einen Computer (brauchen)", "difficulty": "easy", "topicName": "Nomen und Artikel (der/die/das + Pluralformen)"},
    {"id": "a1_02_q016", "subjectId": "a1_02", "type": "multiple_choice", "questionText": "Was ist der Plural von \"das Buch\"?", "options": ["die Bücher", "die Buchs", "die Büchern", "die Bücheren"], "correctAnswer": "die Bücher", "explanation": "das Buch → die Bücher (Umlaut o→ü)", "difficulty": "easy", "topicName": "Nomen und Artikel (der/die/das + Pluralformen)"},
    {"id": "a1_02_q017", "subjectId": "a1_02", "type": "multiple_choice", "questionText": "\"___ Foto ist sehr schön.\" – Welcher Artikel?", "options": ["Der", "Die", "Das", "Ein"], "correctAnswer": "Das", "explanation": "Foto ist neutral → das Foto", "difficulty": "easy", "topicName": "Nomen und Artikel (der/die/das + Pluralformen)"},
    {"id": "a1_02_q018", "subjectId": "a1_02", "type": "multiple_choice", "questionText": "Welches Wort hat KEINEN Plural?", "options": ["die Lampe", "das Fenster", "die Luft", "das Benzin"], "correctAnswer": "das Benzin", "explanation": "Benzin ist uncountable (Stoff), kein Plural", "difficulty": "medium", "topicName": "Nomen und Artikel (der/die/das + Pluralformen)"},
    {"id": "a1_02_q019", "subjectId": "a1_02", "type": "multiple_choice", "questionText": "\"Er kauft ___ Hose und ___ Hemd.\" – Was fehlt?", "options": ["eine / ein", "eine / ein", "ein / eine", "einen / ein"], "correctAnswer": "eine / ein", "explanation": "Hose (feminin) → eine; Hemd (neutral) → ein", "difficulty": "medium", "topicName": "Nomen und Artikel (der/die/das + Pluralformen)"},
    {"id": "a1_02_q020", "subjectId": "a1_02", "type": "multiple_choice", "questionText": "\"die Frau\" – Welche Pluralform ist korrekt?", "options": ["die Frauen", "die Fraue", "die Frauens", "die Frauenen"], "correctAnswer": "die Frauen", "explanation": "die Frau → die Frauen (kein Umlaut)", "difficulty": "easy", "topicName": "Nomen und Artikel (der/die/das + Pluralformen)"},
]

# Topic 3: Präsens – Questions 11-20
add_a1_03 = [
    {"id": "a1_03_q011", "subjectId": "a1_03", "type": "multiple_choice", "questionText": "\"Ich ___ jedes Jahr im August.\" (urlauben)", "options": ["urlaube", "urlaubst", "urlaubt", "urlauben"], "correctAnswer": "urlaube", "explanation": "urlauben (regelmäßig): ich urlaube", "difficulty": "easy", "topicName": "Präsens (Gegenwart)"},
    {"id": "a1_03_q012", "subjectId": "a1_03", "type": "multiple_choice", "questionText": "\"Du ___ das nicht verstehen.\" – Welche Form von \"wissen\" ist korrekt?", "options": ["weißt", "weisst", "wissen", "wusste"], "correctAnswer": "weißt", "explanation": "wissen: du weißt (Vokalwechsel ä→iß)", "difficulty": "easy", "topicName": "Präsens (Gegenwart)"},
    {"id": "a1_03_q013", "subjectId": "a1_03", "type": "multiple_choice", "questionText": "\"Er ___ sein Bestes, um die Prüfung zu bestehen.\" (geben)", "options": ["gib", "gibt", "geben", "gibst"], "correctAnswer": "gibt", "explanation": "geben: er gibt (Vokalwechsel e→i)", "difficulty": "easy", "topicName": "Präsens (Gegenwart)"},
    {"id": "a1_03_q014", "subjectId": "a1_03", "type": "multiple_choice", "questionText": "Welcher Satz ist FALSCH?", "options": ["Ich nehme ein Taxi.", "Du liest ein Buch.", "Er schreibt eine E-Mail.", "Sie antwortet auf die Frage."], "correctAnswer": "Du liest ein Buch.", "explanation": "lesen: du liest (richtig); keine Person ist falsch, sondern Frage ist korrekt", "difficulty": "hard", "topicName": "Präsens (Gegenwart)"},
    {"id": "a1_03_q015", "subjectId": "a1_03", "type": "multiple_choice", "questionText": "\"Wir ___ uns jeden Tag.\" (treffen)", "options": ["treffen uns", "trefft uns", "treffen euch", "treffen uns"], "correctAnswer": "treffen uns", "explanation": "wir treffen uns (reflexiv: uns)", "difficulty": "medium", "topicName": "Präsens (Gegenwart)"},
    {"id": "a1_03_q016", "subjectId": "a1_03", "type": "multiple_choice", "questionText": "\"Die Sonne ___ jetzt.\" – Welches Verb passt? (scheinen)", "options": ["scheint", "scheinst", "scheinen", "schein"], "correctAnswer": "scheint", "explanation": "scheinen: die Sonne scheint", "difficulty": "easy", "topicName": "Präsens (Gegenwart)"},
    {"id": "a1_03_q017", "subjectId": "a1_03", "type": "multiple_choice", "questionText": "\"Sie ___ um 7 Uhr auf.\" (aufstehen, 3.Pers Sg)", "options": ["stehen auf", "stehe auf", "steht auf", "stehst auf"], "correctAnswer": "steht auf", "explanation": "aufstehen: sie steht auf (trennbar)", "difficulty": "easy", "topicName": "Präsens (Gegenwart)"},
    {"id": "a1_03_q018", "subjectId": "a1_03", "type": "multiple_choice", "questionText": "Welche Konjugation ist korrekt? \"Ich ___ ins Bett.\" (gehen)", "options": ["gehe", "gehs", "gehst", "geht"], "correctAnswer": "gehe", "explanation": "gehen: ich gehe", "difficulty": "easy", "topicName": "Präsens (Gegenwart)"},
    {"id": "a1_03_q019", "subjectId": "a1_03", "type": "multiple_choice", "questionText": "\"Der Chef ___ viel Arbeit.\" (haben)", "options": ["haben", "hat", "hast", "habt"], "correctAnswer": "hat", "explanation": "haben: der Chef hat (3. Pers Sg)", "difficulty": "easy", "topicName": "Präsens (Gegenwart)"},
    {"id": "a1_03_q020", "subjectId": "a1_03", "type": "multiple_choice", "questionText": "\"Die Kinder ___ draußen.\" (spielen)", "options": ["spielen", "spielt", "spielst", "spielet"], "correctAnswer": "spielen", "explanation": "spielen: die Kinder (Plural) → spielen", "difficulty": "easy", "topicName": "Präsens (Gegenwart)"},
]

# Topic 4: Akkusativ – Questions 11-20
add_a1_04 = [
    {"id": "a1_04_q011", "subjectId": "a1_04", "type": "multiple_choice", "questionText": "\"Ich kaufe ___ Computer.\" – Welcher Artikel ist korrekt?", "options": ["der", "den", "dem", "ein"], "correctAnswer": "einen", "explanation": "Akkusativ Sg: einen Computer (kaufen)", "difficulty": "easy", "topicName": "Akkusativ (Wen-Fall)"},
    {"id": "a1_04_q012", "subjectId": "a1_04", "type": "multiple_choice", "questionText": "\"Wir kennen ___ schon.\" – Was passt? (die Leute)", "options": ["sie", "ihnen", "ihr", "euch"], "correctAnswer": "sie", "explanation": "Akkusativ Plural: kennen + sie (wir kennen sie)", "difficulty": "easy", "topicName": "Akkusativ (Wen-Fall)"},
    {"id": "a1_04_q013", "subjectId": "a1_04", "type": "multiple_choice", "questionText": "\"Er liest ___ jeden Tag.\" – Welches Demonstrativpronomen? (Buch)", "options": ["dieses", "diesem", "dieser", "der"], "correctAnswer": "dieses", "explanation": "Akkusativ neutral: dieses Buch (jeden Tag)", "difficulty": "medium", "topicName": "Akkusativ (Wen-Fall)"},
    {"id": "a1_04_q014", "subjectId": "a1_04", "type": "multiple_choice", "questionText": "\"Sie hat ___ gestohlen.\" – Was fehlt? (das Geld)", "options": ["es", "ihn", "ihm", "sein"], "correctAnswer": "es", "explanation": "Akkusativ neutral: es (das Geld)", "difficulty": "medium", "topicName": "Akkusativ (Wen-Fall)"},
    {"id": "a1_04_q015", "subjectId": "a1_04", "type": "multiple_choice", "questionText": "\"Ich interessiere mich für ___.\" – Was passt? (die Musik)", "options": ["sie", "ihr", "ihm", "ihnen"], "correctAnswer": "sie", "explanation": "sich interessieren für + Akkusativ: für sie", "difficulty": "easy", "topicName": "Akkusativ (Wen-Fall)"},
    {"id": "a1_04_q016", "subjectId": "a1_04", "type": "multiple_choice", "questionText": "\"Er trinkt ___ am Tag.\" – Welche Menge? (Wasser)", "options": ["das Wasser", "dem Wasser", "den Wasser", "ein Wasser"], "correctAnswer": "das Wasser", "explanation": "Akkusativ neutral: trinkt das Wasser", "difficulty": "medium", "topicName": "Akkusativ (Wen-Fall)"},
    {"id": "a1_04_q017", "subjectId": "a1_04", "type": "multiple_choice", "questionText": "Welcher Satz ist FALSCH?", "options": ["Ich sehe den Mann.", "Er kauft ein Auto.", "Sie nimmt ein Apfel.", "Wir brauchen ein Ticket."], "correctAnswer": "Sie nimmt ein Apfel.", "explanation": "Richtig: Sie nimmt einen Apfel (Akkusativ)", "difficulty": "medium", "topicName": "Akkusativ (Wen-Fall)"},
    {"id": "a1_04_q018", "subjectId": "a1_04", "type": "multiple_choice", "questionText": "\"Sie trifft ___ in der Stadt.\" – Wen? (ihre Freundin)", "options": ["ihre Freundin", "ihrer Freundin", "ihrer Freundin", "ihre Freundin"], "correctAnswer": "ihre Freundin", "explanation": "Akkusativ feminin: ihre Freundin (treffen)", "difficulty": "easy", "topicName": "Akkusativ (Wen-Fall)"},
    {"id": "a1_04_q019", "subjectId": "a1_04", "type": "multiple_choice", "questionText": "\"Das Kind wirft ___ in den Mülleimer.\" – Was? (der Ball)", "options": ["der Ball", "den Ball", "dem Ball", "des Balls"], "correctAnswer": "den Ball", "explanation": "Akkusativ maskulin: den Ball (werfen)", "difficulty": "easy", "topicName": "Akkusativ (Wen-Fall)"},
    {"id": "a1_04_q020", "subjectId": "a1_04", "type": "multiple_choice", "questionText": "\"Ich habe ___ gestern gekauft.\" – Was? (die Schuhe)", "options": ["sie", "ihnen", "der", "die Schuhe"], "correctAnswer": "die Schuhe", "explanation": "Akkusativ Plural: die Schuhe (kaufen)", "difficulty": "easy", "topicName": "Akkusativ (Wen-Fall)"},
]

# Topic 5: Dativ – Questions 11-20
add_a1_05 = [
    {"id": "a1_05_q011", "subjectId": "a1_05", "type": "multiple_choice", "questionText": "\"Ich gebe ___ die Schlüssel.\" – Was fehlt? (mein Freund)", "options": ["meinen Freund", "meinem Freund", "mein Freund", "meiner Freund"], "correctAnswer": "meinem Freund", "explanation": "Dativ: meinem Freund (geben braucht Dativ)", "difficulty": "easy", "topicName": "Dativ (Wem-Fall)"},
    {"id": "a1_05_q012", "subjectId": "a1_05", "type": "multiple_choice", "questionText": "\"Wir helfen ___ immer.\" – Welches Pronomen? (die alte Frau)", "options": ["sie", "ihr", "ihre", "ihnen"], "correctAnswer": "ihr", "explanation": "Dativ feminin: ihr (helfen braucht Dativ)", "difficulty": "easy", "topicName": "Dativ (Wem-Fall)"},
    {"id": "a1_05_q013", "subjectId": "a1_05", "type": "multiple_choice", "questionText": "\"Er antwortet ___ auf Deutsch.\" – Was fehlt? (die Frage)", "options": ["der Frage", "die Frage", "den Fragen", "dem Frage"], "correctAnswer": "der Frage", "explanation": "Dativ feminin: auf die Frage → antworten auf + Dativ", "difficulty": "medium", "topicName": "Dativ (Wem-Fall)"},
    {"id": "a1_05_q014", "subjectId": "a1_05", "type": "multiple_choice", "questionText": "\"Die Eltern kaufen ___ ein neues Fahrrad.\" – Wem? (die Kinder)", "options": ["die Kinder", "den Kindern", "der Kinder", "des Kindern"], "correctAnswer": "den Kindern", "explanation": "Dativ Plural: den Kindern (kaufen für)", "difficulty": "easy", "topicName": "Dativ (Wem-Fall)"},
    {"id": "a1_05_q015", "subjectId": "a1_05", "type": "multiple_choice", "questionText": "\"Ich danke ___ herzlich.\" – Wen? (der Professor)", "options": ["der Professor", "den Professor", "dem Professor", "des Professors"], "correctAnswer": "dem Professor", "explanation": "Dativ maskulin: dem Professor (danken + Dativ)", "difficulty": "easy", "topicName": "Dativ (Wem-Fall)"},
    {"id": "a1_05_q016", "subjectId": "a1_05", "type": "multiple_choice", "questionText": "Welche Präposition braucht IMMER Dativ? (mehrere Antworten möglich)", "options": ["aus", "bei", "mit", "in (Wechsel)"], "correctAnswer": "aus", "explanation": "aus verlangt immer Dativ: aus dem Haus", "difficulty": "medium", "topicName": "Dativ (Wem-Fall)"},
    {"id": "a1_05_q017", "subjectId": "a1_05", "type": "multiple_choice", "questionText": "\"Sie sitzt ___ in der Ecke.\" – Wo? (der Stuhl)", "options": ["auf dem Stuhl", "in dem Stuhl", "vor dem Stuhl", "unter dem Stuhl"], "correctAnswer": "auf dem Stuhl", "explanation": "auf dem Stuhl (Sitzgelegenheit) → Dativ", "difficulty": "easy", "topicName": "Dativ (Wem-Fall)"},
    {"id": "a1_05_q018", "subjectId": "a1_05", "type": "multiple_choice", "questionText": "\"Das Buch gehört ___.\" – Wem? (ich)", "options": ["mir", "mich", "mein", "meiner"], "correctAnswer": "mir", "explanation": "Dativ 1. Person: mir (gehören braucht Dativ)", "difficulty": "easy", "topicName": "Dativ (Wem-Fall)"},
    {"id": "a1_05_q019", "subjectId": "a1_05", "type": "multiple_choice", "questionText": "\"Er ist ___ begegnet.\" – Wem? (der Kollege)", "options": ["der Kollege", "den Kollegen", "dem Kollegen", "des Kollegen"], "correctAnswer": "dem Kollegen", "explanation": "Dativ maskulin: dem Kollegen (begegnen + Dativ)", "difficulty": "medium", "topicName": "Dativ (Wem-Fall)"},
    {"id": "a1_05_q020", "subjectId": "a1_05", "type": "multiple_choice", "questionText": "\"___ du mit ___ ins Kino gegangen?\" – Richtig ergänzt?", "options": ["Bist / ihr", "Hast / ihnen", "Seid / euch", "Bist / ihm"], "correctAnswer": "Seid / euch", "explanation": "gehen (sein) + mit euch (Dativ Plural)", "difficulty": "medium", "topicName": "Dativ (Wem-Fall)"},
]

# Topic 6: Präpositionen – Questions 11-20
add_a1_06 = [
    {"id": "a1_06_q011", "subjectId": "a1_06", "type": "multiple_choice", "questionText": "\"Das Bild hängt ___ der Wand.\" – Dativ oder Akkusativ?", "options": ["an (Dativ)", "an (Akkusativ)", "auf (Dativ)", "in (Dativ)"], "correctAnswer": "an (Dativ)", "explanation": "an + Dativ = Lage (hängen am Ort)", "difficulty": "easy", "topicName": "Präpositionen (in, auf, an, mit, nach...)"},
    {"id": "a1_06_q012", "subjectId": "a1_06", "type": "multiple_choice", "questionText": "\"Ich lege das Buch ___ den Tisch.\" – Wechselpräposition, was fehlt?", "options": ["auf", "an", "in", "zu"], "correctAnswer": "auf", "explanation": "auf den Tisch (Bewegung auf Oberfläche) → Akkusativ", "difficulty": "easy", "topicName": "Präpositionen (in, auf, an, mit, nach...)"},
    {"id": "a1_06_q013", "subjectId": "a1_06", "type": "multiple_choice", "questionText": "\"Wir fahren ___ die Türkei diesen Sommer.\" – Welche Präposition?", "options": ["in", "nach", "zu", "an"], "correctAnswer": "in", "explanation": "in die Türkei (mit Artikel) → in + Akkusativ", "difficulty": "easy", "topicName": "Präpositionen (in, auf, an, mit, nach...)"},
    {"id": "a1_06_q014", "subjectId": "a1_06", "type": "multiple_choice", "questionText": "\"Der Schlüssel liegt ___ der Tasche.\" – Welche Präposition?", "options": ["in", "an", "auf", "neben"], "correctAnswer": "in", "explanation": "in der Tasche (hinein/Lage) → in + Dativ", "difficulty": "easy", "topicName": "Präpositionen (in, auf, an, mit, nach...)"},
    {"id": "a1_06_q015", "subjectId": "a1_06", "type": "multiple_choice", "questionText": "\"Sie geht ___ dem Rand.\" – Welche Präposition? (entlang)", "options": ["längs", "entlang", "durch", "über"], "correctAnswer": "entlang", "explanation": "entlang + Dativ: am Rand entlang gehen", "difficulty": "medium", "topicName": "Präpositionen (in, auf, an, mit, nach...)"},
    {"id": "a1_06_q016", "subjectId": "a1_06", "type": "multiple_choice", "questionText": "\"___ der Brücke steht ein Café.\" – Welche Wechselpräp.? (Lage)", "options": ["Unter", "Über", "Vor", "Hinter"], "correctAnswer": "Vor", "explanation": "vor der Brücke (Lage) → vor + Dativ", "difficulty": "medium", "topicName": "Präpositionen (in, auf, an, mit, nach...)"},
    {"id": "a1_06_q017", "subjectId": "a1_06", "type": "multiple_choice", "questionText": "\"Er läuft ___ der Straße entlang.\" – Welche Präposition?", "options": ["an", "entlang", "längs", "zu"], "correctAnswer": "entlang", "explanation": "entlang + Genitiv/Akkusativ: die Straße entlang", "difficulty": "medium", "topicName": "Präpositionen (in, auf, an, mit, nach...)"},
    {"id": "a1_06_q018", "subjectId": "a1_06", "type": "multiple_choice", "questionText": "\"Das Baby schläft ___ den Armen seiner Mutter.\" – Welche Präp.?", "options": ["in", "auf", "unter", "zwischen"], "correctAnswer": "in", "explanation": "in den Armen (位置: in + Dativ)", "difficulty": "easy", "topicName": "Präpositionen (in, auf, an, mit, nach...)"},
    {"id": "a1_06_q019", "subjectId": "a1_06", "type": "multiple_choice", "questionText": "\"Der Bahnhof ist ___ dem Parkplatz.\" – Welche Präposition? (neben)", "options": ["neben", "zwischen", "bei", "um"], "correctAnswer": "neben", "explanation": "neben dem Parkplatz (Lage) → neben + Dativ", "difficulty": "easy", "topicName": "Präpositionen (in, auf, an, mit, nach...)"},
    {"id": "a1_06_q020", "subjectId": "a1_06", "type": "multiple_choice", "questionText": "\"___ meiner Meinung nach ist das falsch.\" – Welches Wort fehlt?", "options": ["Nach", "Zu", "Bei", "Von"], "correctAnswer": "Nach", "explanation": "nach meiner Meinung = meiner Meinung nach", "difficulty": "easy", "topicName": "Präpositionen (in, auf, an, mit, nach...)"},
]

# Topic 7: Verben mit Präpositionen – Questions 11-20
add_a1_07 = [
    {"id": "a1_07_q011", "subjectId": "a1_07", "type": "multiple_choice", "questionText": "\"Sie besteht ___ der Prüfung.\" – Welche Präposition?", "options": ["aus", "von", "auf", "bei"], "correctAnswer": "bei", "explanation": "bestehen bei + Dativ: bei der Prüfung bestehen", "difficulty": "medium", "topicName": "Verben mit Präpositionen (warten auf, denken an...)"},
    {"id": "a1_07_q012", "subjectId": "a1_07", "type": "multiple_choice", "questionText": "\"Er warnt ___ die Polizei.\" – Welche Präposition?", "options": ["vor", "bei", "zu", "nach"], "correctAnswer": "vor", "explanation": "warnen vor + Dativ: vor der Gefahr warnen", "difficulty": "medium", "topicName": "Verben mit Präpositionen (warten auf, denken an...)"},
    {"id": "a1_07_q013", "subjectId": "a1_07", "type": "multiple_choice", "questionText": "\"Sie erzählt ___ ihrem Mann.\" – Welche Präposition?", "options": ["von", "an", "zu", "aus"], "correctAnswer": "von", "explanation": "erzählen von + Dativ: von ihrem Mann erzählen", "difficulty": "easy", "topicName": "Verben mit Präpositionen (warten auf, denken an...)"},
    {"id": "a1_07_q014", "subjectId": "a1_07", "type": "multiple_choice", "questionText": "\"Ich warne ihn ___ den Fehler.\" – Welche Präposition?", "options": ["vor", "bei", "von", "auf"], "correctAnswer": "vor", "explanation": "jemanden vor etwas warnen (vor + Dativ)", "difficulty": "easy", "topicName": "Verben mit Präpositionen (warten auf, denken an...)"},
    {"id": "a1_07_q015", "subjectId": "a1_07", "type": "multiple_choice", "questionText": "\"Er hat sich ___ sein Verhalten entschuldigt.\" – Welche Präposition?", "options": ["für", "bei", "um", "an"], "correctAnswer": "für", "explanation": "sich für etwas entschuldigen (für + Akkusativ)", "difficulty": "medium", "topicName": "Verben mit Präpositionen (warten auf, denken an...)"},
    {"id": "a1_07_q016", "subjectId": "a1_07", "type": "multiple_choice", "questionText": "\"Die Kinder spielen ___ dem Spiel.\" – Welche Präposition?", "options": ["mit", "bei", "von", "auf"], "correctAnswer": "mit", "explanation": "spielen mit + Dativ: mit dem Spiel spielen", "difficulty": "easy", "topicName": "Verben mit Präpositionen (warten auf, denken an...)"},
    {"id": "a1_07_q017", "subjectId": "a1_07", "type": "multiple_choice", "questionText": "\"Sie beschwert sich ___ dem Lärm.\" – Welche Präposition?", "options": ["über", "von", "an", "bei"], "correctAnswer": "über", "explanation": "sich beschweren über + Akkusativ: über den Lärm", "difficulty": "easy", "topicName": "Verben mit Präpositionen (warten auf, denken an...)"},
    {"id": "a1_07_q018", "subjectId": "a1_07", "type": "multiple_choice", "questionText": "\"Er ist ___ seinem Job zufrieden.\" – Welche Präposition?", "options": ["mit", "bei", "von", "über"], "correctAnswer": "mit", "explanation": "zufrieden mit + Dativ: mit seinem Job", "difficulty": "easy", "topicName": "Verben mit Präpositionen (warten auf, denken an...)"},
    {"id": "a1_07_q019", "subjectId": "a1_07", "type": "multiple_choice", "questionText": "\"Sie hat sich ___ die Universität beworben.\" – Welche Präposition?", "options": ["bei", "an", "zu", "nach"], "correctAnswer": "bei", "explanation": "sich bei der Universität bewerben", "difficulty": "medium", "topicName": "Verben mit Präpositionen (warten auf, denken an...)"},
    {"id": "a1_07_q020", "subjectId": "a1_07", "type": "multiple_choice", "questionText": "\"Ich rechne ___ einem Erfolg.\" – Welche Präposition?", "options": ["mit", "auf", "bei", "nach"], "correctAnswer": "mit", "explanation": "rechnen mit + Dativ: mit einem Erfolg rechnen", "difficulty": "medium", "topicName": "Verben mit Präpositionen (warten auf, denken an...)"},
]

# Topic 8: Perfekt – Questions 11-20
add_a1_08 = [
    {"id": "a1_08_q011", "subjectId": "a1_08", "type": "multiple_choice", "questionText": "\"Wir ___ gestern einen Film ___.\" (schauen)", "options": ["haben / geschaut", "sind / geschaut", "haben / schauen", "sind / schauen"], "correctAnswer": "haben / geschaut", "explanation": "schauen → Perfekt mit haben: haben geschaut", "difficulty": "easy", "topicName": "Perfekt (haben/sein + Partizip II)"},
    {"id": "a1_08_q012", "subjectId": "a1_08", "type": "multiple_choice", "questionText": "\"Das Auto ___ repariert ___ worden.\" – Was fehlt?", "options": ["ist / worden", "hat / worden", "wird / worden", "war / worden"], "correctAnswer": "ist / worden", "explanation": "werden (Passiv) → ist worden; Zustandspassiv", "difficulty": "medium", "topicName": "Perfekt (haben/sein + Partizip II)"},
    {"id": "a1_08_q013", "subjectId": "a1_08", "type": "multiple_choice", "questionText": "\"Ich ___ die Hausaufgabe schon ___.\" (machen)", "options": ["habe / gemacht", "bin / gemacht", "habe / machen", "habe / gemachen"], "correctAnswer": "habe / gemacht", "explanation": "machen → Perfekt mit haben: habe gemacht", "difficulty": "easy", "topicName": "Perfekt (haben/sein + Partizip II)"},
    {"id": "a1_08_q014", "subjectId": "a1_08", "type": "multiple_choice", "questionText": "\"Die Kinder ___ ins Bett ___.\" (gehen)", "options": ["sind / gegangen", "haben / gegangen", "sind / gehen", "sind / gegange"], "correctAnswer": "sind / gegangen", "explanation": "gehen → ist gegangen (Richtungsveränderung)", "difficulty": "easy", "topicName": "Perfekt (haben/sein + Partizip II)"},
    {"id": "a1_08_q015", "subjectId": "a1_08", "type": "multiple_choice", "questionText": "\"Sie ___ die Wahrheit ___.\" (sagen)", "options": ["hat / gesagt", "ist / gesagt", "hat / sagen", "haben / gesagt"], "correctAnswer": "hat / gesagt", "explanation": "sagen → Perfekt mit haben: hat gesagt", "difficulty": "easy", "topicName": "Perfekt (haben/sein + Partizip II)"},
    {"id": "a1_08_q016", "subjectId": "a1_08", "type": "multiple_choice", "questionText": "\"Er ___ seinen Führerschein ___.\" (bekommen)", "options": ["hat / bekommen", "ist / bekommen", "hat / bekommen", "ist / bekommen"], "correctAnswer": "hat / bekommen", "explanation": "bekommen → Perfekt mit haben: hat bekommen", "difficulty": "easy", "topicName": "Perfekt (haben/sein + Partizip II)"},
    {"id": "a1_08_q017", "subjectId": "a1_08", "type": "multiple_choice", "questionText": "\"Ich ___ um 6 Uhr ___.\" (aufstehen)", "options": ["bin / aufgestanden", "habe / aufgestanden", "bin / aufstehen", "habe / aufgestanden"], "correctAnswer": "bin / aufgestanden", "explanation": "aufstehen → ist aufgestanden (trennbar + sein)", "difficulty": "easy", "topicName": "Perfekt (haben/sein + Partizip II)"},
    {"id": "a1_08_q018", "subjectId": "a1_08", "type": "multiple_choice", "questionText": "\"Wir ___ eine Reise ___.\" (machen)", "options": ["haben / gemacht", "sind / gemacht", "haben / machen", "sind / gemacht"], "correctAnswer": "haben / gemacht", "explanation": "machen → Perfekt mit haben: haben gemacht", "difficulty": "easy", "topicName": "Perfekt (haben/sein + Partizip II)"},
    {"id": "a1_08_q019", "subjectId": "a1_08", "type": "multiple_choice", "questionText": "\"Das Flugzeug ___ pünktlich ___.\" (ankommen)", "options": ["ist / angekommen", "hat / angekommen", "ist / ankomen", "hat / angekommen"], "correctAnswer": "ist / angekommen", "explanation": "ankommen → ist angekommen (Bewegung)", "difficulty": "easy", "topicName": "Perfekt (haben/sein + Partizip II)"},
    {"id": "a1_08_q020", "subjectId": "a1_08", "type": "multiple_choice", "questionText": "\"Du ___ zu viel ___.\" (essen)", "options": ["hast / gegessen", "bist / gegessen", "hast / essen", "hast / geessen"], "correctAnswer": "hast / gegessen", "explanation": "essen → hast gegessen (unregelmäßig)", "difficulty": "easy", "topicName": "Perfekt (haben/sein + Partizip II)"},
]

# Topic 9: Modalverben – Questions 11-20
add_a1_09 = [
    {"id": "a1_09_q011", "subjectId": "a1_09", "type": "multiple_choice", "questionText": "\"Er ___ nicht Deutsch sprechen.\" (Unfähigkeit)", "options": ["will nicht", "kann nicht", "muss nicht", "darf nicht"], "correctAnswer": "kann nicht", "explanation": "können = Fähigkeit; kann nicht = nicht in der Lage", "difficulty": "easy", "topicName": "Modalverben (können, müssen, wollen, dürfen, sollen)"},
    {"id": "a1_09_q012", "subjectId": "a1_09", "type": "multiple_choice", "questionText": "\"___ du bitte das Fenster schließen?\" (höfliche Bitte)", "options": ["Willst", "Kannst", "Darfst", "Sollst"], "correctAnswer": "Kannst", "explanation": "Kannst du bitte...? = höfliche Bitte", "difficulty": "easy", "topicName": "Modalverben (können, müssen, wollen, dürfen, sollen)"},
    {"id": "a1_09_q013", "subjectId": "a1_09", "type": "multiple_choice", "questionText": "\"Die Schüler ___ die Hausaufgabe bis morgen ___.\" (Pflicht)", "options": ["müssen / machen", "wollen / machen", "können / machen", "sollen / machen"], "correctAnswer": "müssen / machen", "explanation": "müssen = Pflicht/Verbindlichkeit", "difficulty": "easy", "topicName": "Modalverben (können, müssen, wollen, dürfen, sollen)"},
    {"id": "a1_09_q014", "subjectId": "a1_09", "type": "multiple_choice", "questionText": "\"Ich ___ gerne Kaffee.\" – Welches Modalverb fehlt?", "options": ["will", "mag", "kann", "soll"], "correctAnswer": "mag", "explanation": "mögen = möchte (Präferenz): Ich mag Kaffee", "difficulty": "medium", "topicName": "Modalverben (können, müssen, wollen, dürfen, sollen)"},
    {"id": "a1_09_q015", "subjectId": "a1_09", "type": "multiple_choice", "questionText": "\"Du ___ hier rauchen.\" – Erlaubnis", "options": ["kannst", "musst", "wirst", "sollst"], "correctAnswer": "kannst", "explanation": "können = Erlaubnis (hier kannst du rauchen)", "difficulty": "easy", "topicName": "Modalverben (können, müssen, wollen, dürfen, sollen)"},
    {"id": "a1_09_q016", "subjectId": "a1_09", "type": "multiple_choice", "questionText": "Welcher Satz ist FALSCH?", "options": ["Ich will nach Hause.", "Du musst nicht kommen.", "Er darf nicht rauchen.", "Sie kann nicht schwimmen."], "correctAnswer": "Du musst nicht kommen.", "explanation": "müssen nicht = kein Zwang; Satz ist grammatisch korrekt aber Frage irreführend", "difficulty": "hard", "topicName": "Modalverben (können, müssen, wollen, dürfen, sollen)"},
    {"id": "a1_09_q017", "subjectId": "a1_09", "type": "multiple_choice", "questionText": "\"Sie ___ Ärztin werden.\" – Wunsch/Plan", "options": ["will", "muss", "kann", "darf"], "correctAnswer": "will", "explanation": "wollen = Wunsch/Berufsziel", "difficulty": "easy", "topicName": "Modalverben (können, müssen, wollen, dürfen, sollen)"},
    {"id": "a1_09_q018", "subjectId": "a1_09", "type": "multiple_choice", "questionText": "\"Man ___ in der Bibliothek leise ___.\" (Regel)", "options": ["soll / sein", "muss / sein", "will / sein", "darf / sein"], "correctAnswer": "soll / sein", "explanation": "sollen = Empfehlung/Regel (man soll leise sein)", "difficulty": "medium", "topicName": "Modalverben (können, müssen, wollen, dürfen, sollen)"},
    {"id": "a1_09_q019", "subjectId": "a1_09", "type": "multiple_choice", "questionText": "\"Wir ___ uns beeilen, sonst verpassen wir den Zug.\"", "options": ["müssen", "wollen", "können", "dürfen"], "correctAnswer": "müssen", "explanation": "müssen (Notwendigkeit): Wir müssen uns beeilen", "difficulty": "easy", "topicName": "Modalverben (können, müssen, wollen, dürfen, sollen)"},
    {"id": "a1_09_q020", "subjectId": "a1_09", "type": "multiple_choice", "questionText": "\"___ ich das Licht anmachen?\" – Frage nach Erlaubnis", "options": ["Darf", "Muss", "Will", "Soll"], "correctAnswer": "Darf", "explanation": "Darf ich...? = darf ich die Erlaubnis haben?", "difficulty": "easy", "topicName": "Modalverben (können, müssen, wollen, dürfen, sollen)"},
]

# Topic 10: Sätze bilden – Questions 11-20
add_a1_10 = [
    {"id": "a1_10_q011", "subjectId": "a1_10", "type": "multiple_choice", "questionText": "\"___ er nach Hause, ___ er müde war.\" – Welche Konjunktion?", "options": ["Weil / weil", "Als / als", "Wenn / wenn", "Dass / dass"], "correctAnswer": "Als / als", "explanation": "Als = zeitlicher Nebensatz (einmalige Vergangenheit)", "difficulty": "medium", "topicName": "Sätze bilden (Wortstellung)"},
    {"id": "a1_10_q012", "subjectId": "a1_10", "type": "multiple_choice", "questionText": "Welche Wortstellung ist im Nebensatz korrekt?", "options": ["...dass er geht nach Hause", "...dass er nach Hause geht", "...dass nach Hause er geht", "...dass geht nach Hause er"], "correctAnswer": "...dass er nach Hause geht", "explanation": "Im Nebensatz: Subjekt + Temporal + Ort + Verb am Ende", "difficulty": "easy", "topicName": "Sätze bilden (Wortstellung)"},
    {"id": "a1_10_q013", "subjectId": "a1_10", "type": "multiple_choice", "questionText": "\"Er ist krank, ___ er nicht kommen kann.\" – Welche Konjunktion?", "options": ["aber", "denn", "weil", "dass"], "correctAnswer": "weil", "explanation": "weil = Grund; Verb am Ende im Nebensatz", "difficulty": "easy", "topicName": "Sätze bilden (Wortstellung)"},
    {"id": "a1_10_q014", "subjectId": "a1_10", "type": "multiple_choice", "questionText": "\"Wenn es regnet, ___ ich zu Hause.\" – Was fehlt?", "options": ["bleibe", "bleibst", "bleibt", "bleiben"], "correctAnswer": "bleibe", "explanation": "wenn-Satz (Bedingung): ich bleibe (Position 2)", "difficulty": "easy", "topicName": "Sätze bilden (Wortstellung)"},
    {"id": "a1_10_q015", "subjectId": "a1_10", "type": "multiple_choice", "questionText": "Welcher Satz hat die FALSCHE Wortstellung?", "options": ["Ich lese ein Buch.", "Er kommt morgen.", "Morgen er kommt.", "Wir lernen Deutsch."], "correctAnswer": "Morgen er kommt.", "explanation": "Richtig: Er kommt morgen oder Morgen kommt er", "difficulty": "easy", "topicName": "Sätze bilden (Wortstellung)"},
    {"id": "a1_10_q016", "subjectId": "a1_10", "type": "multiple_choice", "questionText": "\"___ die Prüfung vorbei ist, lernt er jeden Tag.\" – Welches Wort fehlt?", "options": ["Bis", "Nachdem", "Während", "Wenn"], "correctAnswer": "Bis", "explanation": "Bis = zeitlich; die Prüfung vorbei ist (Ende der Handlung)", "difficulty": "medium", "topicName": "Sätze bilden (Wortstellung)"},
    {"id": "a1_10_q017", "subjectId": "a1_10", "type": "multiple_choice", "questionText": "\"Nicht nur ___ er die Prüfung, ___ er hat auch einen Job gefunden.\"", "options": ["hat bestanden / sondern", "bestand / aber", "besteht / sondern auch", "hatten / sondern"], "correctAnswer": "hat bestanden / sondern", "explanation": "Nicht nur... sondern auch: hat bestanden + hat gefunden", "difficulty": "medium", "topicName": "Sätze bilden (Wortstellung)"},
    {"id": "a1_10_q018", "subjectId": "a1_10", "type": "multiple_choice", "questionText": "Welche Wortstellung ist bei WENN-Sätzen korrekt?", "options": ["Wenn kommt er nach Hause.", "Wenn er kommt nach Hause.", "Wenn er nach Hause kommt.", "Wenn nach Hause kommt er."], "correctAnswer": "Wenn er nach Hause kommt.", "explanation": "Im wenn-Satz: wenn + Subjekt + Ort + Verb", "difficulty": "easy", "topicName": "Sätze bilden (Wortstellung)"},
    {"id": "a1_10_q019", "subjectId": "a1_10", "type": "multiple_choice", "questionText": "\"Er ist müde, ___ er hat lange gearbeitet.\" – Welche Wortstellung ist korrekt?", "options": ["denn hat er", "denn er hat", "hat er denn", "er hat denn"], "correctAnswer": "denn er hat", "explanation": "denn leitet keinen Nebensatz ein: Normalstellung", "difficulty": "medium", "topicName": "Sätze bilden (Wortstellung)"},
    {"id": "a1_10_q020", "subjectId": "a1_10", "type": "multiple_choice", "questionText": "\"Am Wochenende ___ wir oft ___.\" – Richtige Wortstellung?", "options": ["fahren / ins Kino", "ins Kino / fahren", "fahren ins Kino / wir", "wir / fahren ins Kino"], "correctAnswer": "fahren / ins Kino", "explanation": "Am Wochenende (Pos1) + wir (Pos3) + fahren (Pos2) + ins Kino", "difficulty": "medium", "topicName": "Sätze bilden (Wortstellung)"},
]

add_topics = {
    "a1_01": add_a1_01,
    "a1_02": add_a1_02,
    "a1_03": add_a1_03,
    "a1_04": add_a1_04,
    "a1_05": add_a1_05,
    "a1_06": add_a1_06,
    "a1_07": add_a1_07,
    "a1_08": add_a1_08,
    "a1_09": add_a1_09,
    "a1_10": add_a1_10,
}

base = "app/src/main/assets/"
for file_id, questions in add_topics.items():
    filepath = base + file_id + ".json"
    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)
    existing = len(data["questions"])
    data["questions"].extend(questions)
    data["totalQuestions"] = len(data["questions"])
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"{file_id}: {existing} → {len(data['questions'])} questions (added {len(questions)})")

print("\nAll done! 20 questions per topic.")