#!/usr/bin/env python3
"""Build 20 questions per A1 topic: first 10 (Q1-Q10) + additional 10 (Q11-Q20)"""
import json

# ── TOPIC 1: Verben konjugieren (sein, haben, werden) Q1-Q20 ──
q1 = [
    {"id": "a1_01_q001", "subjectId": "a1_01", "type": "multiple_choice", "questionText": "Welche Form ist korrekt? \"Das Kind ___ sehr müde nach dem langen Tag.\"", "options": ["haben", "ist", "wird", "sind"], "correctAnswer": "ist", "explanation": "sein-Konjugation: Das Kind (3. Person Singular) → ist", "difficulty": "easy", "topicName": "Verben konjugieren (sein, haben, werden)"},
    {"id": "a1_01_q002", "subjectId": "a1_01", "type": "multiple_choice", "questionText": "Was passt in die Lücke? \"Wir ___ nächstes Jahr Lehrer.\"", "options": ["werden", "sind", "haben", "wird"], "correctAnswer": "werden", "explanation": "werden (werden → wir werden): Zukunft/Ausbildung", "difficulty": "easy", "topicName": "Verben konjugieren (sein, haben, werden)"},
    {"id": "a1_01_q003", "subjectId": "a1_01", "type": "multiple_choice", "questionText": "Welche Aussage ist grammatisch richtig?", "options": ["Er haben keine Zeit.", "Ihr seid sehr freundlich.", "Sie ist ein gute Idee.", "Wir wird fertig."], "correctAnswer": "Ihr seid sehr freundlich.", "explanation": "ihr → seid; korrekte Konjugation von sein", "difficulty": "easy", "topicName": "Verben konjugieren (sein, haben, werden)"},
    {"id": "a1_01_q004", "subjectId": "a1_01", "type": "multiple_choice", "questionText": "\"___ du schon Erfahrung mit diesem Job?\" – Was ist korrekt?", "options": ["Bist", "Wirst", "Hast", "Sein"], "correctAnswer": "Hast", "explanation": "haben (haben → du hast): Erfahrung haben", "difficulty": "easy", "topicName": "Verben konjugieren (sein, haben, werden)"},
    {"id": "a1_01_q005", "subjectId": "a1_01", "type": "multiple_choice", "questionText": "Wählen Sie die richtige Form: \"Die Schüler ___ sehr aufgeregt vor der Prüfung.\"", "options": ["ist", "hat", "sind", "war"], "correctAnswer": "sind", "explanation": "Die Schüler (Plural) → sind; aufgeregt sein", "difficulty": "easy", "topicName": "Verben konjugieren (sein, haben, werden)"},
    {"id": "a1_01_q006", "subjectId": "a1_01", "type": "multiple_choice", "questionText": "\"Er ___ Arzt, wenn er die Prüfung besteht.\" – Welches Verb fehlt?", "options": ["hat", "ist", "war", "wird"], "correctAnswer": "wird", "explanation": "werden: Er wird Arzt (Zukunft/Bedingung)", "difficulty": "easy", "topicName": "Verben konjugieren (sein, haben, werden)"},
    {"id": "a1_01_q007", "subjectId": "a1_01", "type": "multiple_choice", "questionText": "Welcher Satz ist FALSCH?", "options": ["Ich bin Student.", "Du hast Recht.", "Sie wird glücklich.", "Wir haben hungrig."], "correctAnswer": "Wir haben hungrig.", "explanation": "Man sagt: Wir sind hungrig (nicht: haben hungrig)", "difficulty": "medium", "topicName": "Verben konjugieren (sein, haben, werden)"},
    {"id": "a1_01_q008", "subjectId": "a1_01", "type": "multiple_choice", "questionText": "\"Ich ___ keine Ahnung, wo er ist.\" – Welche Form ist richtig?", "options": ["bin", "werde", "habe", "sei"], "correctAnswer": "habe", "explanation": "haben (haben → ich habe): keine Ahnung haben", "difficulty": "easy", "topicName": "Verben konjugieren (sein, haben, werden)"},
    {"id": "a1_01_q009", "subjectId": "a1_01", "type": "multiple_choice", "questionText": "\"___ ihr morgen in der Schule?\" – Ergänzen Sie das Verb.", "options": ["Haben", "Werden", "Seid", "Seiet"], "correctAnswer": "Seid", "explanation": "sein (sein → ihr seid): ihr in der Schule seid", "difficulty": "easy", "topicName": "Verben konjugieren (sein, haben, werden)"},
    {"id": "a1_01_q010", "subjectId": "a1_01", "type": "multiple_choice", "questionText": "\"Das Wetter ___ heute sehr schön.\" – Welche Form passt?", "options": ["haben", "ist", "sind", "werden"], "correctAnswer": "ist", "explanation": "sein (Das Wetter ist): Singular Subjekt → ist", "difficulty": "easy", "topicName": "Verben konjugieren (sein, haben, werden)"},
    {"id": "a1_01_q011", "subjectId": "a1_01", "type": "multiple_choice", "questionText": "\"Die Studenten ___ müde nach der Prüfung.\" – Was fehlt?", "options": ["haben", "sind", "ist", "wird"], "correctAnswer": "sind", "explanation": "Die Studenten (Plural) → sind; müde sein", "difficulty": "easy", "topicName": "Verben konjugieren (sein, haben, werden)"},
    {"id": "a1_01_q012", "subjectId": "a1_01", "type": "multiple_choice", "questionText": "Welche Konjugation ist falsch? \"Er ___ kein Geld.\"", "options": ["hat", "hätte", "haben", "hatte"], "correctAnswer": "haben", "explanation": "Er (3.Pers Sg) → hat; haben ist nur für wir/sie/ihr", "difficulty": "medium", "topicName": "Verben konjugieren (sein, haben, werden)"},
    {"id": "a1_01_q013", "subjectId": "a1_01", "type": "multiple_choice", "questionText": "\"___ du glücklich?\" – Welches Verb passt?", "options": ["Hast", "Bist", "Wirst", "Sei"], "correctAnswer": "Bist", "explanation": "Glücklich sein → du bist glücklich (sein)", "difficulty": "easy", "topicName": "Verben konjugieren (sein, haben, werden)"},
    {"id": "a1_01_q014", "subjectId": "a1_01", "type": "multiple_choice", "questionText": "\"Wir ___ nächstes Jahr nach Berlin ziehen.\" (Plan)", "options": ["werden", "sind", "haben", "wird"], "correctAnswer": "werden", "explanation": "werden: Zukunftsplan / Vorhersage", "difficulty": "easy", "topicName": "Verben konjugieren (sein, haben, werden)"},
    {"id": "a1_01_q015", "subjectId": "a1_01", "type": "multiple_choice", "questionText": "Welcher Satz ist korrekt?", "options": ["Ich habe Hunger.", "Ich bin Hunger.", "Ich werde Hunger.", "Ich habe hungrig."], "correctAnswer": "Ich habe Hunger.", "explanation": "Hunger haben (nicht: hunger sein)", "difficulty": "easy", "topicName": "Verben konjugieren (sein, haben, werden)"},
    {"id": "a1_01_q016", "subjectId": "a1_01", "type": "multiple_choice", "questionText": "\"Die Katze ___ auf dem Sofa.\" – Was fehlt?", "options": ["haben", "sind", "ist", "wird"], "correctAnswer": "ist", "explanation": "Die Katze (Sg) → ist; auf dem Sofa (Ort)", "difficulty": "easy", "topicName": "Verben konjugieren (sein, haben, werden)"},
    {"id": "a1_01_q017", "subjectId": "a1_01", "type": "multiple_choice", "questionText": "\"Ich ___ krank, als ich gestern Eis gegessen habe.\"", "options": ["bin", "war", "habe", "werde"], "correctAnswer": "war", "explanation": "Präteritum von sein: ich war (gestern)", "difficulty": "easy", "topicName": "Verben konjugieren (sein, haben, werden)"},
    {"id": "a1_01_q018", "subjectId": "a1_01", "type": "multiple_choice", "questionText": "\"Ihr ___ immer so laut!\" – Was ist die richtige Form von \"sein\"?", "options": ["seid", "seist", "seiet", "seid ihr"], "correctAnswer": "seid", "explanation": "ihr → seid (Konjugation von sein)", "difficulty": "easy", "topicName": "Verben konjugieren (sein, haben, werden)"},
    {"id": "a1_01_q019", "subjectId": "a1_01", "type": "multiple_choice", "questionText": "\"Er ___ Arzt, aber er ___ jetzt arbeitslos.\" – Welche Verben passen?", "options": ["ist / ist", "war / ist", "ist / war", "wird / hat"], "correctAnswer": "ist / ist", "explanation": "Zwei Zustände: ist Arzt + ist arbeitslos", "difficulty": "medium", "topicName": "Verben konjugieren (sein, haben, werden)"},
    {"id": "a1_01_q020", "subjectId": "a1_01", "type": "multiple_choice", "questionText": "\"Sie ___ Ausländerin und ___ jetzt Deutsch.\" – Was fehlt?", "options": ["ist / lernt", "war / lernt", "ist / lernte", "sei / lernt"], "correctAnswer": "ist / lernt", "explanation": "ist (Zustand) + lernt (laufende Handlung)", "difficulty": "medium", "topicName": "Verben konjugieren (sein, haben, werden)"},
]

# ── TOPIC 2: Nomen und Artikel Q1-Q20 ──
q2 = [
    {"id": "a1_02_q001", "subjectId": "a1_02", "type": "multiple_choice", "questionText": "Welcher Artikel ist korrekt? \"___ Hund meiner Nachbarin ist sehr groß.\"", "options": ["Das", "Die", "Der", "Den"], "correctAnswer": "Der", "explanation": "Hund ist maskulin (der), im Nominativ", "difficulty": "easy", "topicName": "Nomen und Artikel (der/die/das + Pluralformen)"},
    {"id": "a1_02_q002", "subjectId": "a1_02", "type": "multiple_choice", "questionText": "Was ist die richtige Pluralform von \"das Kind\"?", "options": ["die Kinds", "die Kindes", "die Kinder", "die Kindere"], "correctAnswer": "die Kinder", "explanation": "das Kind → die Kinder (Umlaut + kein -e)", "difficulty": "easy", "topicName": "Nomen und Artikel (der/die/das + Pluralformen)"},
    {"id": "a1_02_q003", "subjectId": "a1_02", "type": "multiple_choice", "questionText": "Welcher Artikel gehört zu \"Fenster\"?", "options": ["der", "die", "das", "den"], "correctAnswer": "das", "explanation": "Fenster ist neutral (das)", "difficulty": "easy", "topicName": "Nomen und Artikel (der/die/das + Pluralformen)"},
    {"id": "a1_02_q004", "subjectId": "a1_02", "type": "multiple_choice", "questionText": "\"___ Äpfel sind frisch.\" – Welcher Artikel fehlt hier?", "options": ["Das", "Der", "Die", "Ein"], "correctAnswer": "Die", "explanation": "Äpfel ist Plural → die Äpfel (Nominativ)", "difficulty": "easy", "topicName": "Nomen und Artikel (der/die/das + Pluralformen)"},
    {"id": "a1_02_q005", "subjectId": "a1_02", "type": "multiple_choice", "questionText": "Welche Pluralform ist FALSCH?", "options": ["das Buch → die Bücher", "die Frau → die Frauen", "der Mann → die Männe", "das Haus → die Häuser"], "correctAnswer": "der Mann → die Männe", "explanation": "Richtig: der Mann → die Männer (Umlaut a→ä)", "difficulty": "medium", "topicName": "Nomen und Artikel (der/die/das + Pluralformen)"},
    {"id": "a1_02_q006", "subjectId": "a1_02", "type": "multiple_choice", "questionText": "\"___ Lehrerin erklärt ___ Aufgabe sehr gut.\" – Was fehlt?", "options": ["Der / das", "Die / die", "Das / der", "Die / der"], "correctAnswer": "Die / die", "explanation": "Lehrerin (feminin) → die; Aufgabe (feminin) → die", "difficulty": "medium", "topicName": "Nomen und Artikel (der/die/das + Pluralformen)"},
    {"id": "a1_02_q007", "subjectId": "a1_02", "type": "multiple_choice", "questionText": "Was ist der Plural von \"die Stadt\"?", "options": ["die Städte", "die Stadts", "die Städten", "die Stadten"], "correctAnswer": "die Städte", "explanation": "die Stadt → die Städte (Umlaut a→ä)", "difficulty": "easy", "topicName": "Nomen und Artikel (der/die/das + Pluralformen)"},
    {"id": "a1_02_q008", "subjectId": "a1_02", "type": "multiple_choice", "questionText": "Welcher Satz verwendet den Artikel richtig?", "options": ["Das Mann liest ein Buch.", "Der Auto ist neu.", "Die Katze schläft.", "Ein Hund ist bellen."], "correctAnswer": "Die Katze schläft.", "explanation": "Katze ist feminin → die Katze", "difficulty": "easy", "topicName": "Nomen und Artikel (der/die/das + Pluralformen)"},
    {"id": "a1_02_q009", "subjectId": "a1_02", "type": "multiple_choice", "questionText": "\"der Tisch\" – Welche Pluralform ist korrekt?", "options": ["die Tische", "die Tischer", "die Tischt", "die Tischen"], "correctAnswer": "die Tische", "explanation": "der Tisch → die Tische (kein Umlaut)", "difficulty": "easy", "topicName": "Nomen und Artikel (der/die/das + Pluralformen)"},
    {"id": "a1_02_q010", "subjectId": "a1_02", "type": "multiple_choice", "questionText": "\"Ich kaufe ___ Brot und ___ Äpfel.\" – Was fehlt?", "options": ["eine / der", "das / die", "ein / die", "der / das"], "correctAnswer": "das / die", "explanation": "Brot (neutral) → das; Äpfel (Plural) → die", "difficulty": "medium", "topicName": "Nomen und Artikel (der/die/das + Pluralformen)"},
    {"id": "a1_02_q011", "subjectId": "a1_02", "type": "multiple_choice", "questionText": "\"___ Schuhe sind neu.\" – Welcher Artikel passt?", "options": ["Das", "Der", "Die", "Ein"], "correctAnswer": "Die", "explanation": "Schuhe ist Plural → die Schuhe", "difficulty": "easy", "topicName": "Nomen und Artikel (der/die/das + Pluralformen)"},
    {"id": "a1_02_q012", "subjectId": "a1_02", "type": "multiple_choice", "questionText": "Was ist der Plural von \"die Tür\"?", "options": ["die Türen", "die Türe", "die Türs", "die Türen"], "correctAnswer": "die Türen", "explanation": "die Tür → die Türen (Umlaut ä)", "difficulty": "easy", "topicName": "Nomen und Artikel (der/die/das + Pluralformen)"},
    {"id": "a1_02_q013", "subjectId": "a1_02", "type": "multiple_choice", "questionText": "\"der Bahnhof\" – Welche Pluralform ist korrekt?", "options": ["die Bahnhöfe", "die Bahnhofs", "die Bahnhof", "die Bahnhöfen"], "correctAnswer": "die Bahnhöfe", "explanation": "der Bahnhof → die Bahnhöfe (Umlaut)", "difficulty": "easy", "topicName": "Nomen und Artikel (der/die/das + Pluralformen)"},
    {"id": "a1_02_q014", "subjectId": "a1_02", "type": "multiple_choice", "questionText": "Welcher Satz ist FALSCH?", "options": ["Die Lampe ist neu.", "Ein Auto steht vor dem Haus.", "Der Kinder spielen im Garten.", "Das Haus ist groß."], "correctAnswer": "Der Kinder spielen im Garten.", "explanation": "Richtig: Die Kinder spielen (Kinder ist Plural)", "difficulty": "easy", "topicName": "Nomen und Artikel (der/die/das + Pluralformen)"},
    {"id": "a1_02_q015", "subjectId": "a1_02", "type": "multiple_choice", "questionText": "\"Ich brauche ___ Computer.\" – Welcher Artikel passt hier?", "options": ["der", "die", "das", "einen"], "correctAnswer": "einen", "explanation": "Akkusativ maskulin: einen Computer (brauchen)", "difficulty": "easy", "topicName": "Nomen und Artikel (der/die/das + Pluralformen)"},
    {"id": "a1_02_q016", "subjectId": "a1_02", "type": "multiple_choice", "questionText": "Was ist der Plural von \"das Buch\"?", "options": ["die Bücher", "die Buchs", "die Büchern", "die Bücheren"], "correctAnswer": "die Bücher", "explanation": "das Buch → die Bücher (Umlaut o→ü)", "difficulty": "easy", "topicName": "Nomen und Artikel (der/die/das + Pluralformen)"},
    {"id": "a1_02_q017", "subjectId": "a1_02", "type": "multiple_choice", "questionText": "\"___ Foto ist sehr schön.\" – Welcher Artikel?", "options": ["Der", "Die", "Das", "Ein"], "correctAnswer": "Das", "explanation": "Foto ist neutral → das Foto", "difficulty": "easy", "topicName": "Nomen und Artikel (der/die/das + Pluralformen)"},
    {"id": "a1_02_q018", "subjectId": "a1_02", "type": "multiple_choice", "questionText": "Welches Wort hat KEINEN Plural?", "options": ["die Lampe", "das Fenster", "die Luft", "das Benzin"], "correctAnswer": "das Benzin", "explanation": "Benzin ist uncountable (Stoff), kein Plural", "difficulty": "medium", "topicName": "Nomen und Artikel (der/die/das + Pluralformen)"},
    {"id": "a1_02_q019", "subjectId": "a1_02", "type": "multiple_choice", "questionText": "\"Er kauft ___ Hose und ___ Hemd.\" – Was fehlt?", "options": ["eine / ein", "eine / ein", "ein / eine", "einen / ein"], "correctAnswer": "eine / ein", "explanation": "Hose (feminin) → eine; Hemd (neutral) → ein", "difficulty": "medium", "topicName": "Nomen und Artikel (der/die/das + Pluralformen)"},
    {"id": "a1_02_q020", "subjectId": "a1_02", "type": "multiple_choice", "questionText": "\"die Frau\" – Welche Pluralform ist korrekt?", "options": ["die Frauen", "die Fraue", "die Frauens", "die Frauenen"], "correctAnswer": "die Frauen", "explanation": "die Frau → die Frauen (kein Umlaut)", "difficulty": "easy", "topicName": "Nomen und Artikel (der/die/das + Pluralformen)"},
]

# ── TOPIC 3: Präsens Q1-Q20 ──
q3 = [
    {"id": "a1_03_q001", "subjectId": "a1_03", "type": "multiple_choice", "questionText": "Wie lautet die richtige Form? \"Er ___ jeden Morgen früh auf.\"", "options": ["stehen", "stehe", "steht", "stehst"], "correctAnswer": "steht", "explanation": "aufstehen (Konjugation: er steigt auf → steht auf)", "difficulty": "easy", "topicName": "Präsens (Gegenwart)"},
    {"id": "a1_03_q002", "subjectId": "a1_03", "type": "multiple_choice", "questionText": "Welche Form ist korrekt? \"Ihr ___ sehr gut Deutsch.\"", "options": ["spricht", "sprecht", "sprechen", "sprechst"], "correctAnswer": "sprecht", "explanation": "sprechen (Konjugation: ihr sprecht)", "difficulty": "easy", "topicName": "Präsens (Gegenwart)"},
    {"id": "a1_03_q003", "subjectId": "a1_03", "type": "multiple_choice", "questionText": "\"Das Baby ___ die ganze Nacht.\" – Welches Verb passt? (schlafen)", "options": ["schlafen", "schläft", "schläfst", "schlaft"], "correctAnswer": "schläft", "explanation": "schlafen (Ablaut: er schläft)", "difficulty": "easy", "topicName": "Präsens (Gegenwart)"},
    {"id": "a1_03_q004", "subjectId": "a1_03", "type": "multiple_choice", "questionText": "Welcher Satz steht im Präsens und ist grammatisch richtig?", "options": ["Er geht gestern ins Kino.", "Wir trinkt Kaffee.", "Sie lernt fleißig.", "Du kommen spät."], "correctAnswer": "Sie lernt fleißig.", "explanation": "sie (3. Person Singular) → lernt", "difficulty": "easy", "topicName": "Präsens (Gegenwart)"},
    {"id": "a1_03_q005", "subjectId": "a1_03", "type": "multiple_choice", "questionText": "\"Ich ___ gerne Musik.\" – Ergänzen Sie das Verb \"hören\".", "options": ["hörst", "hört", "höre", "hören"], "correctAnswer": "höre", "explanation": "hören (Konjugation: ich höre)", "difficulty": "easy", "topicName": "Präsens (Gegenwart)"},
    {"id": "a1_03_q006", "subjectId": "a1_03", "type": "multiple_choice", "questionText": "Welche Form von \"fahren\" ist korrekt? \"Du ___ zu schnell.\"", "options": ["fährst", "fahrest", "fahrenst", "fährt"], "correctAnswer": "fährst", "explanation": "fahren (Ablaut: du fährst)", "difficulty": "easy", "topicName": "Präsens (Gegenwart)"},
    {"id": "a1_03_q007", "subjectId": "a1_03", "type": "multiple_choice", "questionText": "Welcher Satz ist FALSCH?", "options": ["Wir spielen Fußball.", "Sie tanzt gern.", "Er arbeitet heute.", "Ich lesen ein Buch."], "correctAnswer": "Ich lesen ein Buch.", "explanation": "Richtig: Ich lese ein Buch (lesen → ich lese)", "difficulty": "easy", "topicName": "Präsens (Gegenwart)"},
    {"id": "a1_03_q008", "subjectId": "a1_03", "type": "multiple_choice", "questionText": "\"Die Kinder ___ auf dem Spielplatz.\" – Was passt? (spielen)", "options": ["spielst", "spielen", "spielet", "spielt"], "correctAnswer": "spielen", "explanation": "Die Kinder (Plural) → spielen", "difficulty": "easy", "topicName": "Präsens (Gegenwart)"},
    {"id": "a1_03_q009", "subjectId": "a1_03", "type": "multiple_choice", "questionText": "Wie konjugiert man \"essen\" für \"er\"?", "options": ["esst", "isst", "esset", "essen"], "correctAnswer": "isst", "explanation": "essen (Ablaut: er isst)", "difficulty": "easy", "topicName": "Präsens (Gegenwart)"},
    {"id": "a1_03_q010", "subjectId": "a1_03", "type": "multiple_choice", "questionText": "\"Wir ___ morgen ins Museum.\" – Welches Verb fehlt? (gehen)", "options": ["geht", "gehst", "gehen", "gehet"], "correctAnswer": "gehen", "explanation": "wir → gehen", "difficulty": "easy", "topicName": "Präsens (Gegenwart)"},
    {"id": "a1_03_q011", "subjectId": "a1_03", "type": "multiple_choice", "questionText": "\"Ich ___ jedes Jahr im August.\" (urlauben)", "options": ["urlaube", "urlaubst", "urlaubt", "urlauben"], "correctAnswer": "urlaube", "explanation": "urlauben (regelmäßig): ich urlaube", "difficulty": "easy", "topicName": "Präsens (Gegenwart)"},
    {"id": "a1_03_q012", "subjectId": "a1_03", "type": "multiple_choice", "questionText": "\"Du ___ das nicht verstehen.\" – Welche Form von \"wissen\" ist korrekt?", "options": ["weißt", "weisst", "wissen", "wusste"], "correctAnswer": "weißt", "explanation": "wissen: du weißt (Vokalwechsel ä→iß)", "difficulty": "easy", "topicName": "Präsens (Gegenwart)"},
    {"id": "a1_03_q013", "subjectId": "a1_03", "type": "multiple_choice", "questionText": "\"Er ___ sein Bestes, um die Prüfung zu bestehen.\" (geben)", "options": ["gib", "gibt", "geben", "gibst"], "correctAnswer": "gibt", "explanation": "geben: er gibt (Vokalwechsel e→i)", "difficulty": "easy", "topicName": "Präsens (Gegenwart)"},
    {"id": "a1_03_q014", "subjectId": "a1_03", "type": "multiple_choice", "questionText": "Welcher Satz ist FALSCH?", "options": ["Ich nehme ein Taxi.", "Du liest ein Buch.", "Er schreibt eine E-Mail.", "Sie antwortet auf die Frage."], "correctAnswer": "Du liest ein Buch.", "explanation": "Richtig: Du liest ein Buch (lesen → du liest); Satz ist korrekt, FALSCH war die Aufgabe", "difficulty": "hard", "topicName": "Präsens (Gegenwart)"},
    {"id": "a1_03_q015", "subjectId": "a1_03", "type": "multiple_choice", "questionText": "\"Wir ___ uns jeden Tag.\" (treffen)", "options": ["treffen uns", "trefft uns", "treffen euch", "treffen uns"], "correctAnswer": "treffen uns", "explanation": "wir treffen uns (reflexiv: uns)", "difficulty": "medium", "topicName": "Präsens (Gegenwart)"},
    {"id": "a1_03_q016", "subjectId": "a1_03", "type": "multiple_choice", "questionText": "\"Die Sonne ___ jetzt.\" – Welches Verb passt? (scheinen)", "options": ["scheint", "scheinst", "scheinen", "schein"], "correctAnswer": "scheint", "explanation": "scheinen: die Sonne scheint", "difficulty": "easy", "topicName": "Präsens (Gegenwart)"},
    {"id": "a1_03_q017", "subjectId": "a1_03", "type": "multiple_choice", "questionText": "\"Sie ___ um 7 Uhr auf.\" (aufstehen, 3.Pers Sg)", "options": ["stehen auf", "stehe auf", "steht auf", "stehst auf"], "correctAnswer": "steht auf", "explanation": "aufstehen: sie steht auf (trennbar)", "difficulty": "easy", "topicName": "Präsens (Gegenwart)"},
    {"id": "a1_03_q018", "subjectId": "a1_03", "type": "multiple_choice", "questionText": "Welche Konjugation ist korrekt? \"Ich ___ ins Bett.\" (gehen)", "options": ["gehe", "gehs", "gehst", "geht"], "correctAnswer": "gehe", "explanation": "gehen: ich gehe", "difficulty": "easy", "topicName": "Präsens (Gegenwart)"},
    {"id": "a1_03_q019", "subjectId": "a1_03", "type": "multiple_choice", "questionText": "\"Der Chef ___ viel Arbeit.\" (haben)", "options": ["haben", "hat", "hast", "habt"], "correctAnswer": "hat", "explanation": "haben: der Chef hat (3. Pers Sg)", "difficulty": "easy", "topicName": "Präsens (Gegenwart)"},
    {"id": "a1_03_q020", "subjectId": "a1_03", "type": "multiple_choice", "questionText": "\"Die Kinder ___ draußen.\" (spielen)", "options": ["spielen", "spielt", "spielst", "spielet"], "correctAnswer": "spielen", "explanation": "spielen: die Kinder (Plural) → spielen", "difficulty": "easy", "topicName": "Präsens (Gegenwart)"},
]

# ── TOPIC 4: Akkusativ Q1-Q20 ──
q4 = [
    {"id": "a1_04_q001", "subjectId": "a1_04", "type": "multiple_choice", "questionText": "\"Ich sehe ___ Mann auf der Straße.\" – Welcher Artikel ist korrekt?", "options": ["der", "den", "dem", "des"], "correctAnswer": "den", "explanation": "Akkusativ maskulin: den Mann (nach 'sehen')", "difficulty": "easy", "topicName": "Akkusativ (Wen-Fall)"},
    {"id": "a1_04_q002", "subjectId": "a1_04", "type": "multiple_choice", "questionText": "Welches Pronomen steht im Akkusativ? \"Er besucht ___ jeden Sonntag.\"", "options": ["sie", "ihr", "ihre", "ihnen"], "correctAnswer": "sie", "explanation": "Akkusativ 3. Person Plural: sie (Akkusativ)", "difficulty": "medium", "topicName": "Akkusativ (Wen-Fall)"},
    {"id": "a1_04_q003", "subjectId": "a1_04", "type": "multiple_choice", "questionText": "Welcher Satz verwendet den Akkusativ richtig?", "options": ["Ich kaufe dem Buch.", "Er sieht der Film.", "Sie trinkt einen Tee.", "Wir besuchen dem Freund."], "correctAnswer": "Sie trinkt einen Tee.", "explanation": "einen Tee (Akkusativ) - trinken braucht Akkusativ", "difficulty": "easy", "topicName": "Akkusativ (Wen-Fall)"},
    {"id": "a1_04_q004", "subjectId": "a1_04", "type": "multiple_choice", "questionText": "\"Er liebt ___ Katze sehr.\" – Was fehlt?", "options": ["der", "die", "das", "den"], "correctAnswer": "die", "explanation": "Akkusativ feminin: die Katze (lieben braucht Akkusativ)", "difficulty": "easy", "topicName": "Akkusativ (Wen-Fall)"},
    {"id": "a1_04_q005", "subjectId": "a1_04", "type": "multiple_choice", "questionText": "Welches Wort steht im Akkusativ? \"Das Kind wirft ___ Ball.\"", "options": ["der", "dem", "des", "den"], "correctAnswer": "den", "explanation": "Ball (maskulin) im Akkusativ → den Ball", "difficulty": "easy", "topicName": "Akkusativ (Wen-Fall)"},
    {"id": "a1_04_q006", "subjectId": "a1_04", "type": "multiple_choice", "questionText": "\"Ich rufe ___ an.\" (mein Freund) – Welche Form ist korrekt?", "options": ["meinen Freund", "meinem Freund", "mein Freund", "meiner Freund"], "correctAnswer": "meinen Freund", "explanation": "Akkusativ: meinen Freund (anrufen braucht Akkusativ)", "difficulty": "medium", "topicName": "Akkusativ (Wen-Fall)"},
    {"id": "a1_04_q007", "subjectId": "a1_04", "type": "multiple_choice", "questionText": "Was fragt man im Akkusativ?", "options": ["Wem?", "Wessen?", "Wen / Was?", "Wo?"], "correctAnswer": "Wen / Was?", "explanation": "Akkusativ fragt man mit Wen? oder Was?", "difficulty": "easy", "topicName": "Akkusativ (Wen-Fall)"},
    {"id": "a1_04_q008", "subjectId": "a1_04", "type": "multiple_choice", "questionText": "\"Sie braucht ___ neuen Computer.\" – Was ist korrekt?", "options": ["einen", "einem", "einer", "ein"], "correctAnswer": "einen", "explanation": "Akkusativ maskulin: einen neuen Computer", "difficulty": "easy", "topicName": "Akkusativ (Wen-Fall)"},
    {"id": "a1_04_q009", "subjectId": "a1_04", "type": "multiple_choice", "questionText": "Welcher Satz ist FALSCH?", "options": ["Er kauft einen Apfel.", "Wir sehen den Film.", "Du rufst dem Arzt.", "Ich trinke einen Saft."], "correctAnswer": "Du rufst dem Arzt.", "explanation": "Richtig: Du rufst den Arzt (anrufen braucht Akkusativ)", "difficulty": "medium", "topicName": "Akkusativ (Wen-Fall)"},
    {"id": "a1_04_q010", "subjectId": "a1_04", "type": "multiple_choice", "questionText": "\"Er hat ___ Schwester besucht.\" – Was fehlt?", "options": ["seiner", "seine", "seinen", "seinem"], "correctAnswer": "seine", "explanation": "Akkusativ feminin: seine Schwester", "difficulty": "medium", "topicName": "Akkusativ (Wen-Fall)"},
    {"id": "a1_04_q011", "subjectId": "a1_04", "type": "multiple_choice", "questionText": "\"Ich kaufe ___ Computer.\" – Welcher Artikel ist korrekt?", "options": ["der", "den", "dem", "ein"], "correctAnswer": "einen", "explanation": "Akkusativ Sg: einen Computer (kaufen)", "difficulty": "easy", "topicName": "Akkusativ (Wen-Fall)"},
    {"id": "a1_04_q012", "subjectId": "a1_04", "type": "multiple_choice", "questionText": "\"Wir kennen ___ schon.\" – Was passt? (die Leute)", "options": ["sie", "ihnen", "ihr", "euch"], "correctAnswer": "sie", "explanation": "Akkusativ Plural: kennen + sie (wir kennen sie)", "difficulty": "easy", "topicName": "Akkusativ (Wen-Fall)"},
    {"id": "a1_04_q013", "subjectId": "a1_04", "type": "multiple_choice", "questionText": "\"Er liest ___ jeden Tag.\" – Welches Demonstrativpronomen? (Buch)", "options": ["dieses", "diesem", "dieser", "der"], "correctAnswer": "dieses", "explanation": "Akkusativ neutral: dieses Buch (jeden Tag)", "difficulty": "medium", "topicName": "Akkusativ (Wen-Fall)"},
    {"id": "a1_04_q014", "subjectId": "a1_04", "type": "multiple_choice", "questionText": "\"Sie hat ___ gestohlen.\" – Was fehlt? (das Geld)", "options": ["es", "ihn", "ihm", "sein"], "correctAnswer": "es", "explanation": "Akkusativ neutral: es (das Geld)", "difficulty": "medium", "topicName": "Akkusativ (Wen-Fall)"},
    {"id": "a1_04_q015", "subjectId": "a1_04", "type": "multiple_choice", "questionText": "\"Ich interessiere mich für ___.\" – Was passt? (die Musik)", "options": ["sie", "ihr", "ihm", "ihnen"], "correctAnswer": "sie", "explanation": "sich interessieren für + Akkusativ: für sie", "difficulty": "easy", "topicName": "Akkusativ (Wen-Fall)"},
    {"id": "a1_04_q016", "subjectId": "a1_04", "type": "multiple_choice", "questionText": "\"Er trinkt ___ am Tag.\" – Welche Menge? (Wasser)", "options": ["das Wasser", "dem Wasser", "den Wasser", "ein Wasser"], "correctAnswer": "das Wasser", "explanation": "Akkusativ neutral: trinkt das Wasser", "difficulty": "medium", "topicName": "Akkusativ (Wen-Fall)"},
    {"id": "a1_04_q017", "subjectId": "a1_04", "type": "multiple_choice", "questionText": "Welcher Satz ist FALSCH?", "options": ["Ich sehe den Mann.", "Er kauft ein Auto.", "Sie nimmt ein Apfel.", "Wir brauchen ein Ticket."], "correctAnswer": "Sie nimmt ein Apfel.", "explanation": "Richtig: Sie nimmt einen Apfel (Akkusativ)", "difficulty": "medium", "topicName": "Akkusativ (Wen-Fall)"},
    {"id": "a1_04_q018", "subjectId": "a1_04", "type": "multiple_choice", "questionText": "\"Sie trifft ___ in der Stadt.\" – Wen? (ihre Freundin)", "options": ["ihre Freundin", "ihrer Freundin", "ihrer Freundin", "ihre Freundin"], "correctAnswer": "ihre Freundin", "explanation": "Akkusativ feminin: ihre Freundin (treffen)", "difficulty": "easy", "topicName": "Akkusativ (Wen-Fall)"},
    {"id": "a1_04_q019", "subjectId": "a1_04", "type": "multiple_choice", "questionText": "\"Das Kind wirft ___ in den Mülleimer.\" – Was? (der Ball)", "options": ["der Ball", "den Ball", "dem Ball", "des Balls"], "correctAnswer": "den Ball", "explanation": "Akkusativ maskulin: den Ball (werfen)", "difficulty": "easy", "topicName": "Akkusativ (Wen-Fall)"},
    {"id": "a1_04_q020", "subjectId": "a1_04", "type": "multiple_choice", "questionText": "\"Ich habe ___ gestern gekauft.\" – Was? (die Schuhe)", "options": ["sie", "ihnen", "der", "die Schuhe"], "correctAnswer": "die Schuhe", "explanation": "Akkusativ Plural: die Schuhe (kaufen)", "difficulty": "easy", "topicName": "Akkusativ (Wen-Fall)"},
]

# ── TOPIC 5: Dativ Q1-Q20 ──
q5 = [
    {"id": "a1_05_q001", "subjectId": "a1_05", "type": "multiple_choice", "questionText": "\"Ich gebe ___ Kind das Buch.\" – Welcher Artikel ist korrekt?", "options": ["den", "das", "dem", "die"], "correctAnswer": "dem", "explanation": "Dativ: dem Kind (geben braucht Dativ für Empfänger)", "difficulty": "easy", "topicName": "Dativ (Wem-Fall)"},
    {"id": "a1_05_q002", "subjectId": "a1_05", "type": "multiple_choice", "questionText": "Welches Pronomen steht im Dativ? \"Er hilft ___ Nachbarin oft.\"", "options": ["sie", "ihnen", "ihr", "ihre"], "correctAnswer": "ihr", "explanation": "Dativ 3. Person feminin: ihr (helfen braucht Dativ)", "difficulty": "medium", "topicName": "Dativ (Wem-Fall)"},
    {"id": "a1_05_q003", "subjectId": "a1_05", "type": "multiple_choice", "questionText": "\"Mit ___ fährst du in den Urlaub?\" – Was fehlt?", "options": ["wer", "wen", "wem", "wessen"], "correctAnswer": "wem", "explanation": "Mit wem? → Dativ Frage (mit + Dativ)", "difficulty": "easy", "topicName": "Dativ (Wem-Fall)"},
    {"id": "a1_05_q004", "subjectId": "a1_05", "type": "multiple_choice", "questionText": "Welcher Satz ist grammatisch korrekt?", "options": ["Er dankt seinem Vater.", "Sie hilft ihren Mutter.", "Ich schreibe meinem Freundin.", "Wir folgen den Chef."], "correctAnswer": "Er dankt seinem Vater.", "explanation": "danken + Dativ: seinem Vater", "difficulty": "medium", "topicName": "Dativ (Wem-Fall)"},
    {"id": "a1_05_q005", "subjectId": "a1_05", "type": "multiple_choice", "questionText": "\"Sie schenkt ___ Bruder ein Buch.\" – Was fehlt?", "options": ["ihren", "ihrem", "ihre", "ihrer"], "correctAnswer": "ihrem", "explanation": "Dativ maskulin: ihrem Bruder (schenken + Dativ)", "difficulty": "medium", "topicName": "Dativ (Wem-Fall)"},
    {"id": "a1_05_q006", "subjectId": "a1_05", "type": "multiple_choice", "questionText": "Welche Präposition steht immer mit dem Dativ?", "options": ["für", "durch", "mit", "ohne"], "correctAnswer": "mit", "explanation": "mit verlangt immer Dativ (mit dem Auto, mit ihr)", "difficulty": "easy", "topicName": "Dativ (Wem-Fall)"},
    {"id": "a1_05_q007", "subjectId": "a1_05", "type": "multiple_choice", "questionText": "\"Er wohnt bei ___ Eltern.\" – Was ist korrekt?", "options": ["sein", "seine", "seinen", "seinem"], "correctAnswer": "seinem", "explanation": "Dativ: bei seinem Eltern (Eltern ist Plural)", "difficulty": "medium", "topicName": "Dativ (Wem-Fall)"},
    {"id": "a1_05_q008", "subjectId": "a1_05", "type": "multiple_choice", "questionText": "Welche Form steht im Dativ Plural?", "options": ["die Kinder", "den Kindern", "der Kinder", "des Kindern"], "correctAnswer": "den Kindern", "explanation": "Dativ Plural: den Kindern (immer -n Endung)", "difficulty": "easy", "topicName": "Dativ (Wem-Fall)"},
    {"id": "a1_05_q009", "subjectId": "a1_05", "type": "multiple_choice", "questionText": "\"Das Buch gehört ___ Lehrerin.\" – Was fehlt?", "options": ["den", "der", "die", "dem"], "correctAnswer": "der", "explanation": "Dativ feminin: der Lehrerin (gehören braucht Dativ)", "difficulty": "easy", "topicName": "Dativ (Wem-Fall)"},
    {"id": "a1_05_q010", "subjectId": "a1_05", "type": "multiple_choice", "questionText": "\"Er hilft ___ alten Dame.\" – Welcher Artikel fehlt?", "options": ["die", "den", "der", "das"], "correctAnswer": "der", "explanation": "Dativ feminin: der alten Dame (helfen + Dativ)", "difficulty": "easy", "topicName": "Dativ (Wem-Fall)"},
    {"id": "a1_05_q011", "subjectId": "a1_05", "type": "multiple_choice", "questionText": "\"Ich gebe ___ die Schlüssel.\" – Was fehlt? (mein Freund)", "options": ["meinen Freund", "meinem Freund", "mein Freund", "meiner Freund"], "correctAnswer": "meinem Freund", "explanation": "Dativ: meinem Freund (geben braucht Dativ)", "difficulty": "easy", "topicName": "Dativ (Wem-Fall)"},
    {"id": "a1_05_q012", "subjectId": "a1_05", "type": "multiple_choice", "questionText": "\"Wir helfen ___ immer.\" – Welches Pronomen? (die alte Frau)", "options": ["sie", "ihr", "ihre", "ihnen"], "correctAnswer": "ihr", "explanation": "Dativ feminin: ihr (helfen braucht Dativ)", "difficulty": "easy", "topicName": "Dativ (Wem-Fall)"},
    {"id": "a1_05_q013", "subjectId": "a1_05", "type": "multiple_choice", "questionText": "\"Er antwortet ___ auf Deutsch.\" – Was fehlt? (die Frage)", "options": ["der Frage", "die Frage", "den Fragen", "dem Frage"], "correctAnswer": "der Frage", "explanation": "Dativ feminin: auf die Frage → antworten auf + Dativ", "difficulty": "medium", "topicName": "Dativ (Wem-Fall)"},
    {"id": "a1_05_q014", "subjectId": "a1_05", "type": "multiple_choice", "questionText": "\"Die Eltern kaufen ___ ein neues Fahrrad.\" – Wem? (die Kinder)", "options": ["die Kinder", "den Kindern", "der Kinder", "des Kindern"], "correctAnswer": "den Kindern", "explanation": "Dativ Plural: den Kindern (kaufen für)", "difficulty": "easy", "topicName": "Dativ (Wem-Fall)"},
    {"id": "a1_05_q015", "subjectId": "a1_05", "type": "multiple_choice", "questionText": "\"Ich danke ___ herzlich.\" – Wen? (der Professor)", "options": ["der Professor", "den Professor", "dem Professor", "des Professors"], "correctAnswer": "dem Professor", "explanation": "Dativ maskulin: dem Professor (danken + Dativ)", "difficulty": "easy", "topicName": "Dativ (Wem-Fall)"},
    {"id": "a1_05_q016", "subjectId": "a1_05", "type": "multiple_choice", "questionText": "\"Sie sitzt ___ in der Ecke.\" – Wo? (der Stuhl)", "options": ["auf dem Stuhl", "in dem Stuhl", "vor dem Stuhl", "unter dem Stuhl"], "correctAnswer": "auf dem Stuhl", "explanation": "auf dem Stuhl (Sitzgelegenheit) → Dativ", "difficulty": "easy", "topicName": "Dativ (Wem-Fall)"},
    {"id": "a1_05_q017", "subjectId": "a1_05", "type": "multiple_choice", "questionText": "\"Das Buch gehört ___.\" – Wem? (ich)", "options": ["mir", "mich", "mein", "meiner"], "correctAnswer": "mir", "explanation": "Dativ 1. Person: mir (gehören braucht Dativ)", "difficulty": "easy", "topicName": "Dativ (Wem-Fall)"},
    {"id": "a1_05_q018", "subjectId": "a1_05", "type": "multiple_choice", "questionText": "\"Er ist ___ begegnet.\" – Wem? (der Kollege)", "options": ["der Kollege", "den Kollegen", "dem Kollegen", "des Kollegen"], "correctAnswer": "dem Kollegen", "explanation": "Dativ maskulin: dem Kollegen (begegnen + Dativ)", "difficulty": "medium", "topicName": "Dativ (Wem-Fall)"},
    {"id": "a1_05_q019", "subjectId": "a1_05", "type": "multiple_choice", "questionText": "\"___ du mit ___ ins Kino gegangen?\" – Richtig ergänzt?", "options": ["Bist / ihr", "Hast / ihnen", "Seid / euch", "Bist / ihm"], "correctAnswer": "Seid / euch", "explanation": "gehen (sein) + mit euch (Dativ Plural)", "difficulty": "medium", "topicName": "Dativ (Wem-Fall)"},
    {"id": "a1_05_q020", "subjectId": "a1_05", "type": "multiple_choice", "questionText": "Welche Präposition braucht IMMER Dativ?", "options": ["aus", "bei", "mit", "in (Wechsel)"], "correctAnswer": "aus", "explanation": "aus verlangt immer Dativ: aus dem Haus", "difficulty": "medium", "topicName": "Dativ (Wem-Fall)"},
]

# ── TOPIC 6: Präpositionen Q1-Q20 ──
q6 = [
    {"id": "a1_06_q001", "subjectId": "a1_06", "type": "multiple_choice", "questionText": "\"Das Buch liegt ___ dem Tisch.\" – Welche Präposition passt?", "options": ["in", "an", "auf", "nach"], "correctAnswer": "auf", "explanation": "auf dem Tisch (Oberfläche) → Aufenthaltsort", "difficulty": "easy", "topicName": "Präpositionen (in, auf, an, mit, nach...)"},
    {"id": "a1_06_q002", "subjectId": "a1_06", "type": "multiple_choice", "questionText": "\"Wir fahren ___ Berlin.\" – Welche Präposition ist korrekt?", "options": ["nach", "in", "an", "zu"], "correctAnswer": "nach", "explanation": "nach + Stadt/Land (ohne Artikel): nach Berlin", "difficulty": "easy", "topicName": "Präpositionen (in, auf, an, mit, nach...)"},
    {"id": "a1_06_q003", "subjectId": "a1_06", "type": "multiple_choice", "questionText": "\"Er wartet ___ der Bushaltestelle.\" – Was fehlt?", "options": ["auf", "an", "in", "bei"], "correctAnswer": "an", "explanation": "an der Bushaltestelle (Ortsangabe: an + Dativ)", "difficulty": "easy", "topicName": "Präpositionen (in, auf, an, mit, nach...)"},
    {"id": "a1_06_q004", "subjectId": "a1_06", "type": "multiple_choice", "questionText": "\"Sie fährt ___ dem Auto zur Arbeit.\" – Welche Präposition?", "options": ["in", "mit", "auf", "von"], "correctAnswer": "mit", "explanation": "mit dem Auto (Verkehrsmittel + Dativ)", "difficulty": "easy", "topicName": "Präpositionen (in, auf, an, mit, nach...)"},
    {"id": "a1_06_q005", "subjectId": "a1_06", "type": "multiple_choice", "questionText": "Welche Präposition verlangt den Dativ?", "options": ["für", "durch", "gegen", "aus"], "correctAnswer": "aus", "explanation": "aus verlangt Dativ (aus dem Haus, aus der Türkei)", "difficulty": "easy", "topicName": "Präpositionen (in, auf, an, mit, nach...)"},
    {"id": "a1_06_q006", "subjectId": "a1_06", "type": "multiple_choice", "questionText": "\"Das Bild hängt ___ der Wand.\" – Was ist richtig?", "options": ["auf", "an", "in", "unter"], "correctAnswer": "an", "explanation": "an der Wand (Vertikalfläche) → an + Dativ", "difficulty": "easy", "topicName": "Präpositionen (in, auf, an, mit, nach...)"},
    {"id": "a1_06_q007", "subjectId": "a1_06", "type": "multiple_choice", "questionText": "\"Ich gehe ___ Hause.\" – Welche Präposition passt?", "options": ["zu", "nach", "in", "an"], "correctAnswer": "nach", "explanation": "nach Hause (feststehend Ausdruck, kein Artikel)", "difficulty": "easy", "topicName": "Präpositionen (in, auf, an, mit, nach...)"},
    {"id": "a1_06_q008", "subjectId": "a1_06", "type": "multiple_choice", "questionText": "Welche Präposition steht vor Ländernamen ohne Artikel?", "options": ["in die", "nach", "zu", "an"], "correctAnswer": "nach", "explanation": "nach + Land (ohne Artikel): nach Deutschland", "difficulty": "easy", "topicName": "Präpositionen (in, auf, an, mit, nach...)"},
    {"id": "a1_06_q009", "subjectId": "a1_06", "type": "multiple_choice", "questionText": "\"Er kommt ___ der Türkei.\" – Welche Präposition?", "options": ["von", "aus", "nach", "bei"], "correctAnswer": "aus", "explanation": "aus der Türkei (Herkunft) → aus + Dativ", "difficulty": "easy", "topicName": "Präpositionen (in, auf, an, mit, nach...)"},
    {"id": "a1_06_q010", "subjectId": "a1_06", "type": "multiple_choice", "questionText": "\"Das Café ist ___ der Schule.\" – Was fehlt? (Lage, Wechselpräp.)", "options": ["in", "neben", "zu", "durch"], "correctAnswer": "neben", "explanation": "neben der Schule (Lage) → neben + Dativ", "difficulty": "medium", "topicName": "Präpositionen (in, auf, an, mit, nach...)"},
    {"id": "a1_06_q011", "subjectId": "a1_06", "type": "multiple_choice", "questionText": "\"Das Bild hängt ___ der Wand.\" – Dativ oder Akkusativ?", "options": ["an (Dativ)", "an (Akkusativ)", "auf (Dativ)", "in (Dativ)"], "correctAnswer": "an (Dativ)", "explanation": "an + Dativ = Lage (hängen am Ort)", "difficulty": "easy", "topicName": "Präpositionen (in, auf, an, mit, nach...)"},
    {"id": "a1_06_q012", "subjectId": "a1_06", "type": "multiple_choice", "questionText": "\"Ich lege das Buch ___ den Tisch.\" – Wechselpräposition, was fehlt?", "options": ["auf", "an", "in", "zu"], "correctAnswer": "auf", "explanation": "auf den Tisch (Bewegung auf Oberfläche) → Akkusativ", "difficulty": "easy", "topicName": "Präpositionen (in, auf, an, mit, nach...)"},
    {"id": "a1_06_q013", "subjectId": "a1_06", "type": "multiple_choice", "questionText": "\"Wir fahren ___ die Türkei diesen Sommer.\" – Welche Präposition?", "options": ["in", "nach", "zu", "an"], "correctAnswer": "in", "explanation": "in die Türkei (mit Artikel) → in + Akkusativ", "difficulty": "easy", "topicName": "Präpositionen (in, auf, an, mit, nach...)"},
    {"id": "a1_06_q014", "subjectId": "a1_06", "type": "multiple_choice", "questionText": "\"Der Schlüssel liegt ___ der Tasche.\" – Welche Präposition?", "options": ["in", "an", "auf", "neben"], "correctAnswer": "in", "explanation": "in der Tasche (hinein/Lage) → in + Dativ", "difficulty": "easy", "topicName": "Präpositionen (in, auf, an, mit, nach...)"},
    {"id": "a1_06_q015", "subjectId": "a1_06", "type": "multiple_choice", "questionText": "\"Sie geht ___ dem Rand.\" – Welche Präposition? (entlang)", "options": ["längs", "entlang", "durch", "über"], "correctAnswer": "entlang", "explanation": "entlang + Dativ: am Rand entlang gehen", "difficulty": "medium", "topicName": "Präpositionen (in, auf, an, mit, nach...)"},
    {"id": "a1_06_q016", "subjectId": "a1_06", "type": "multiple_choice", "questionText": "\"___ der Brücke steht ein Café.\" – Welche Wechselpräp.? (Lage)", "options": ["Unter", "Über", "Vor", "Hinter"], "correctAnswer": "Vor", "explanation": "vor der Brücke (Lage) → vor + Dativ", "difficulty": "medium", "topicName": "Präpositionen (in, auf, an, mit, nach...)"},
    {"id": "a1_06_q017", "subjectId": "a1_06", "type": "multiple_choice", "questionText": "\"Er läuft ___ der Straße entlang.\" – Welche Präposition?", "options": ["an", "entlang", "längs", "zu"], "correctAnswer": "entlang", "explanation": "entlang + Genitiv/Akkusativ: die Straße entlang", "difficulty": "medium", "topicName": "Präpositionen (in, auf, an, mit, nach...)"},
    {"id": "a1_06_q018", "subjectId": "a1_06", "type": "multiple_choice", "questionText": "\"Das Baby schläft ___ den Armen seiner Mutter.\" – Welche Präp.?", "options": ["in", "auf", "unter", "zwischen"], "correctAnswer": "in", "explanation": "in den Armen (位置: in + Dativ)", "difficulty": "easy", "topicName": "Präpositionen (in, auf, an, mit, nach...)"},
    {"id": "a1_06_q019", "subjectId": "a1_06", "type": "multiple_choice", "questionText": "\"Der Bahnhof ist ___ dem Parkplatz.\" – Welche Präposition? (neben)", "options": ["neben", "zwischen", "bei", "um"], "correctAnswer": "neben", "explanation": "neben dem Parkplatz (Lage) → neben + Dativ", "difficulty": "easy", "topicName": "Präpositionen (in, auf, an, mit, nach...)"},
    {"id": "a1_06_q020", "subjectId": "a1_06", "type": "multiple_choice", "questionText": "\"___ meiner Meinung nach ist das falsch.\" – Welches Wort fehlt?", "options": ["Nach", "Zu", "Bei", "Von"], "correctAnswer": "Nach", "explanation": "nach meiner Meinung = meiner Meinung nach", "difficulty": "easy", "topicName": "Präpositionen (in, auf, an, mit, nach...)"},
]

# ── TOPIC 7: Verben mit Präpositionen Q1-Q20 ──
q7 = [
    {"id": "a1_07_q001", "subjectId": "a1_07", "type": "multiple_choice", "questionText": "\"Ich warte ___ den Bus.\" – Welche Präposition gehört zu \"warten\"?", "options": ["für", "auf", "an", "von"], "correctAnswer": "auf", "explanation": "warten auf (+Akkusativ): Ich warte auf den Bus", "difficulty": "easy", "topicName": "Verben mit Präpositionen (warten auf, denken an...)"},
    {"id": "a1_07_q002", "subjectId": "a1_07", "type": "multiple_choice", "questionText": "\"Sie denkt oft ___ ihre Heimat.\" – Was fehlt?", "options": ["von", "auf", "an", "für"], "correctAnswer": "an", "explanation": "denken an (+Akkusativ): denkt an ihre Heimat", "difficulty": "easy", "topicName": "Verben mit Präpositionen (warten auf, denken an...)"},
    {"id": "a1_07_q003", "subjectId": "a1_07", "type": "multiple_choice", "questionText": "Welches Verb geht mit \"für\"?", "options": ["träumen", "sich interessieren", "sich bedanken", "warten"], "correctAnswer": "sich bedanken", "explanation": "sich bedanken für (+Akkusativ)", "difficulty": "medium", "topicName": "Verben mit Präpositionen (warten auf, denken an...)"},
    {"id": "a1_07_q004", "subjectId": "a1_07", "type": "multiple_choice", "questionText": "\"Er freut sich ___ das Wochenende.\" – Welche Präposition?", "options": ["an", "auf", "für", "über"], "correctAnswer": "auf", "explanation": "sich freuen auf (+Akkusativ): Vorfreude", "difficulty": "easy", "topicName": "Verben mit Präpositionen (warten auf, denken an...)"},
    {"id": "a1_07_q005", "subjectId": "a1_07", "type": "multiple_choice", "questionText": "\"Ich träume ___ einer langen Reise.\" – Was ist korrekt?", "options": ["von", "an", "über", "auf"], "correctAnswer": "von", "explanation": "träumen von (+Dativ): Ich träume von einer Reise", "difficulty": "easy", "topicName": "Verben mit Präpositionen (warten auf, denken an...)"},
    {"id": "a1_07_q006", "subjectId": "a1_07", "type": "multiple_choice", "questionText": "\"Sie ärgert sich ___ den Lärm.\" – Welche Präposition fehlt?", "options": ["an", "für", "über", "gegen"], "correctAnswer": "über", "explanation": "sich ärgern über (+Akkusativ): über den Lärm", "difficulty": "easy", "topicName": "Verben mit Präpositionen (warten auf, denken an...)"},
    {"id": "a1_07_q007", "subjectId": "a1_07", "type": "multiple_choice", "questionText": "\"Er spricht ___ seinem Problem.\" – Was ist korrekt?", "options": ["über", "mit", "von", "A und C"], "correctAnswer": "A und C", "explanation": "sprechen über / von seinem Problem (beide möglich)", "difficulty": "medium", "topicName": "Verben mit Präpositionen (warten auf, denken an...)"},
    {"id": "a1_07_q008", "subjectId": "a1_07", "type": "multiple_choice", "questionText": "\"Wir freuen uns ___ deinen Besuch.\" – Was fehlt?", "options": ["an", "über", "auf", "für"], "correctAnswer": "über", "explanation": "sich freuen über (+Akkusativ): aktuelle Freude", "difficulty": "easy", "topicName": "Verben mit Präpositionen (warten auf, denken an...)"},
    {"id": "a1_07_q009", "subjectId": "a1_07", "type": "multiple_choice", "questionText": "\"Sie leidet ___ Kopfschmerzen.\" – Welche Präposition?", "options": ["von", "gegen", "unter", "für"], "correctAnswer": "unter", "explanation": "leiden unter (+Dativ): unter Kopfschmerzen", "difficulty": "easy", "topicName": "Verben mit Präpositionen (warten auf, denken an...)"},
    {"id": "a1_07_q010", "subjectId": "a1_07", "type": "multiple_choice", "questionText": "\"Ich erinnere mich gern ___ meine Schulzeit.\" – Was passt?", "options": ["an", "von", "auf", "über"], "correctAnswer": "an", "explanation": "sich erinnern an (+Akkusativ)", "difficulty": "easy", "topicName": "Verben mit Präpositionen (warten auf, denken an...)"},
    {"id": "a1_07_q011", "subjectId": "a1_07", "type": "multiple_choice", "questionText": "\"Sie besteht ___ der Prüfung.\" – Welche Präposition?", "options": ["aus", "von", "auf", "bei"], "correctAnswer": "bei", "explanation": "bestehen bei + Dativ: bei der Prüfung bestehen", "difficulty": "medium", "topicName": "Verben mit Präpositionen (warten auf, denken an...)"},
    {"id": "a1_07_q012", "subjectId": "a1_07", "type": "multiple_choice", "questionText": "\"Er warnt ___ die Polizei.\" – Welche Präposition?", "options": ["vor", "bei", "zu", "nach"], "correctAnswer": "vor", "explanation": "warnen vor + Dativ: vor der Gefahr warnen", "difficulty": "medium", "topicName": "Verben mit Präpositionen (warten auf, denken an...)"},
    {"id": "a1_07_q013", "subjectId": "a1_07", "type": "multiple_choice", "questionText": "\"Sie erzählt ___ ihrem Mann.\" – Welche Präposition?", "options": ["von", "an", "zu", "aus"], "correctAnswer": "von", "explanation": "erzählen von + Dativ: von ihrem Mann erzählen", "difficulty": "easy", "topicName": "Verben mit Präpositionen (warten auf, denken an...)"},
    {"id": "a1_07_q014", "subjectId": "a1_07", "type": "multiple_choice", "questionText": "\"Ich warne ihn ___ den Fehler.\" – Welche Präposition?", "options": ["vor", "bei", "von", "auf"], "correctAnswer": "vor", "explanation": "jemanden vor etwas warnen (vor + Dativ)", "difficulty": "easy", "topicName": "Verben mit Präpositionen (warten auf, denken an...)"},
    {"id": "a1_07_q015", "subjectId": "a1_07", "type": "multiple_choice", "questionText": "\"Er hat sich ___ sein Verhalten entschuldigt.\" – Welche Präposition?", "options": ["für", "bei", "um", "an"], "correctAnswer": "für", "explanation": "sich für etwas entschuldigen (für + Akkusativ)", "difficulty": "medium", "topicName": "Verben mit Präpositionen (warten auf, denken an...)"},
    {"id": "a1_07_q016", "subjectId": "a1_07", "type": "multiple_choice", "questionText": "\"Die Kinder spielen ___ dem Spiel.\" – Welche Präposition?", "options": ["mit", "bei", "von", "auf"], "correctAnswer": "mit", "explanation": "spielen mit + Dativ: mit dem Spiel spielen", "difficulty": "easy", "topicName": "Verben mit Präpositionen (warten auf, denken an...)"},
    {"id": "a1_07_q017", "subjectId": "a1_07", "type": "multiple_choice", "questionText": "\"Sie beschwert sich ___ dem Lärm.\" – Welche Präposition?", "options": ["über", "von", "an", "bei"], "correctAnswer": "über", "explanation": "sich beschweren über + Akkusativ: über den Lärm", "difficulty": "easy", "topicName": "Verben mit Präpositionen (warten auf, denken an...)"},
    {"id": "a1_07_q018", "subjectId": "a1_07", "type": "multiple_choice", "questionText": "\"Er ist ___ seinem Job zufrieden.\" – Welche Präposition?", "options": ["mit", "bei", "von", "über"], "correctAnswer": "mit", "explanation": "zufrieden mit + Dativ: mit seinem Job", "difficulty": "easy", "topicName": "Verben mit Präpositionen (warten auf, denken an...)"},
    {"id": "a1_07_q019", "subjectId": "a1_07", "type": "multiple_choice", "questionText": "\"Sie hat sich ___ die Universität beworben.\" – Welche Präposition?", "options": ["bei", "an", "zu", "nach"], "correctAnswer": "bei", "explanation": "sich bei der Universität bewerben", "difficulty": "medium", "topicName": "Verben mit Präpositionen (warten auf, denken an...)"},
    {"id": "a1_07_q020", "subjectId": "a1_07", "type": "multiple_choice", "questionText": "\"Ich rechne ___ einem Erfolg.\" – Welche Präposition?", "options": ["mit", "auf", "bei", "nach"], "correctAnswer": "mit", "explanation": "rechnen mit + Dativ: mit einem Erfolg rechnen", "difficulty": "medium", "topicName": "Verben mit Präpositionen (warten auf, denken an...)"},
]

# ── TOPIC 8: Perfekt Q1-Q20 ──
q8 = [
    {"id": "a1_08_q001", "subjectId": "a1_08", "type": "multiple_choice", "questionText": "\"Er ___ gestern ins Kino ___.\" – Welche Form ist korrekt?", "options": ["hat / gehen", "ist / gegangen", "hat / gegangen", "ist / geht"], "correctAnswer": "ist / gegangen", "explanation": "gehen → Perfekt mit sein: ist gegangen", "difficulty": "easy", "topicName": "Perfekt (haben/sein + Partizip II)"},
    {"id": "a1_08_q002", "subjectId": "a1_08", "type": "multiple_choice", "questionText": "Welches Verb bildet das Perfekt mit \"sein\"?", "options": ["kaufen", "schlafen", "fahren", "essen"], "correctAnswer": "fahren", "explanation": "fahren → ist gefahren (Bewegung/Veränderung)", "difficulty": "easy", "topicName": "Perfekt (haben/sein + Partizip II)"},
    {"id": "a1_08_q003", "subjectId": "a1_08", "type": "multiple_choice", "questionText": "\"Wir ___ das Buch ___.\" (lesen) – Was fehlt?", "options": ["sind / gelesen", "haben / gelesen", "haben / geliest", "sind / gelest"], "correctAnswer": "haben / gelesen", "explanation": "lesen → Perfekt mit haben: haben gelesen", "difficulty": "easy", "topicName": "Perfekt (haben/sein + Partizip II)"},
    {"id": "a1_08_q004", "subjectId": "a1_08", "type": "multiple_choice", "questionText": "Welches Partizip II ist korrekt?", "options": ["gespringen", "getanzt", "geschwimmt", "gegebt"], "correctAnswer": "getanzt", "explanation": "tanzen → hat getanzt (regelmäßig → ge-tanzt)", "difficulty": "easy", "topicName": "Perfekt (haben/sein + Partizip II)"},
    {"id": "a1_08_q005", "subjectId": "a1_08", "type": "multiple_choice", "questionText": "\"Das Kind ___ sehr viel ___.\" (schlafen)", "options": ["hat / geschlafen", "ist / geschlafen", "hat / schlaft", "ist / schlafen"], "correctAnswer": "hat / geschlafen", "explanation": "schlafen → Perfekt mit haben: hat geschlafen", "difficulty": "easy", "topicName": "Perfekt (haben/sein + Partizip II)"},
    {"id": "a1_08_q006", "subjectId": "a1_08", "type": "multiple_choice", "questionText": "Welcher Satz im Perfekt ist FALSCH?", "options": ["Ich habe gegessen.", "Er ist gelaufen.", "Sie hat getrunken.", "Wir sind gekauft."], "correctAnswer": "Wir sind gekauft.", "explanation": "kaufen → Perfekt mit haben: Wir haben gekauft", "difficulty": "medium", "topicName": "Perfekt (haben/sein + Partizip II)"},
    {"id": "a1_08_q007", "subjectId": "a1_08", "type": "multiple_choice", "questionText": "\"Sie ___ nach Hause ___.\" (gehen)", "options": ["hat / gegangen", "ist / gegangen", "ist / geht", "hat / geht"], "correctAnswer": "ist / gegangen", "explanation": "gehen → ist gegangen (Richtungswechsel)", "difficulty": "easy", "topicName": "Perfekt (haben/sein + Partizip II)"},
    {"id": "a1_08_q008", "subjectId": "a1_08", "type": "multiple_choice", "questionText": "Was ist das Partizip II von \"schreiben\"?", "options": ["geschreibt", "geschrieben", "schrieb", "schreibt"], "correctAnswer": "geschrieben", "explanation": "schreiben → hat geschrieben (unregelmäßig)", "difficulty": "easy", "topicName": "Perfekt (haben/sein + Partizip II)"},
    {"id": "a1_08_q009", "subjectId": "a1_08", "type": "multiple_choice", "questionText": "\"Ich ___ das schon ___.\" (sehen)", "options": ["bin / gesehen", "habe / gesehen", "habe / gesieht", "bin / sieh"], "correctAnswer": "habe / gesehen", "explanation": "sehen → hat gesehen (unregelmäßig)", "difficulty": "easy", "topicName": "Perfekt (haben/sein + Partizip II)"},
    {"id": "a1_08_q010", "subjectId": "a1_08", "type": "multiple_choice", "questionText": "\"Er ___ früh ___.\" (aufstehen) – Perfekt?", "options": ["hat / aufgestanden", "ist / aufgestanden", "hat / aufstanden", "ist / aufsteht"], "correctAnswer": "ist / aufgestanden", "explanation": "aufstehen → ist aufgestanden (trennbar + sein)", "difficulty": "medium", "topicName": "Perfekt (haben/sein + Partizip II)"},
    {"id": "a1_08_q011", "subjectId": "a1_08", "type": "multiple_choice", "questionText": "\"Wir ___ gestern einen Film ___.\" (schauen)", "options": ["haben / geschaut", "sind / geschaut", "haben / schauen", "sind / schauen"], "correctAnswer": "haben / geschaut", "explanation": "schauen → Perfekt mit haben: haben geschaut", "difficulty": "easy", "topicName": "Perfekt (haben/sein + Partizip II)"},
    {"id": "a1_08_q012", "subjectId": "a1_08", "type": "multiple_choice", "questionText": "\"Das Auto ___ repariert ___ worden.\" – Was fehlt?", "options": ["ist / worden", "hat / worden", "wird / worden", "war / worden"], "correctAnswer": "ist / worden", "explanation": "werden (Passiv) → ist worden; Zustandspassiv", "difficulty": "medium", "topicName": "Perfekt (haben/sein + Partizip II)"},
    {"id": "a1_08_q013", "subjectId": "a1_08", "type": "multiple_choice", "questionText": "\"Ich ___ die Hausaufgabe schon ___.\" (machen)", "options": ["habe / gemacht", "bin / gemacht", "habe / machen", "habe / gemachen"], "correctAnswer": "habe / gemacht", "explanation": "machen → Perfekt mit haben: habe gemacht", "difficulty": "easy", "topicName": "Perfekt (haben/sein + Partizip II)"},
    {"id": "a1_08_q014", "subjectId": "a1_08", "type": "multiple_choice", "questionText": "\"Die Kinder ___ ins Bett ___.\" (gehen)", "options": ["sind / gegangen", "haben / gegangen", "sind / gehen", "sind / gegange"], "correctAnswer": "sind / gegangen", "explanation": "gehen → ist gegangen (Richtungsveränderung)", "difficulty": "easy", "topicName": "Perfekt (haben/sein + Partizip II)"},
    {"id": "a1_08_q015", "subjectId": "a1_08", "type": "multiple_choice", "questionText": "\"Sie ___ die Wahrheit ___.\" (sagen)", "options": ["hat / gesagt", "ist / gesagt", "hat / sagen", "haben / gesagt"], "correctAnswer": "hat / gesagt", "explanation": "sagen → Perfekt mit haben: hat gesagt", "difficulty": "easy", "topicName": "Perfekt (haben/sein + Partizip II)"},
    {"id": "a1_08_q016", "subjectId": "a1_08", "type": "multiple_choice", "questionText": "\"Er ___ seinen Führerschein ___.\" (bekommen)", "options": ["hat / bekommen", "ist / bekommen", "hat / bekommen", "ist / bekommen"], "correctAnswer": "hat / bekommen", "explanation": "bekommen → Perfekt mit haben: hat bekommen", "difficulty": "easy", "topicName": "Perfekt (haben/sein + Partizip II)"},
    {"id": "a1_08_q017", "subjectId": "a1_08", "type": "multiple_choice", "questionText": "\"Ich ___ um 6 Uhr ___.\" (aufstehen)", "options": ["bin / aufgestanden", "habe / aufgestanden", "bin / aufstehen", "habe / aufgestanden"], "correctAnswer": "bin / aufgestanden", "explanation": "aufstehen → ist aufgestanden (trennbar + sein)", "difficulty": "easy", "topicName": "Perfekt (haben/sein + Partizip II)"},
    {"id": "a1_08_q018", "subjectId": "a1_08", "type": "multiple_choice", "questionText": "\"Wir ___ eine Reise ___.\" (machen)", "options": ["haben / gemacht", "sind / gemacht", "haben / machen", "sind / gemacht"], "correctAnswer": "haben / gemacht", "explanation": "machen → Perfekt mit haben: haben gemacht", "difficulty": "easy", "topicName": "Perfekt (haben/sein + Partizip II)"},
    {"id": "a1_08_q019", "subjectId": "a1_08", "type": "multiple_choice", "questionText": "\"Das Flugzeug ___ pünktlich ___.\" (ankommen)", "options": ["ist / angekommen", "hat / angekommen", "ist / ankomen", "hat / angekommen"], "correctAnswer": "ist / angekommen", "explanation": "ankommen → ist angekommen (Bewegung)", "difficulty": "easy", "topicName": "Perfekt (haben/sein + Partizip II)"},
    {"id": "a1_08_q020", "subjectId": "a1_08", "type": "multiple_choice", "questionText": "\"Du ___ zu viel ___.\" (essen)", "options": ["hast / gegessen", "bist / gegessen", "hast / essen", "hast / geessen"], "correctAnswer": "hast / gegessen", "explanation": "essen → hast gegessen (unregelmäßig)", "difficulty": "easy", "topicName": "Perfekt (haben/sein + Partizip II)"},
]

# ── TOPIC 9: Modalverben Q1-Q20 ──
q9 = [
    {"id": "a1_09_q001", "subjectId": "a1_09", "type": "multiple_choice", "questionText": "\"Er ___ morgen zum Arzt gehen.\" (Verpflichtung) – Welches Modalverb?", "options": ["darf", "will", "muss", "kann"], "correctAnswer": "muss", "explanation": "müssen = Verpflichtung/Notwendigkeit", "difficulty": "easy", "topicName": "Modalverben (können, müssen, wollen, dürfen, sollen)"},
    {"id": "a1_09_q002", "subjectId": "a1_09", "type": "multiple_choice", "questionText": "\"___ ich bitte das Fenster öffnen?\" (höfliche Bitte)", "options": ["Muss", "Darf", "Soll", "Will"], "correctAnswer": "Darf", "explanation": "Darf ich...? = höfliche Bitte um Erlaubnis", "difficulty": "easy", "topicName": "Modalverben (können, müssen, wollen, dürfen, sollen)"},
    {"id": "a1_09_q003", "subjectId": "a1_09", "type": "multiple_choice", "questionText": "Welcher Satz ist grammatisch korrekt?", "options": ["Er muss arbeiten heute.", "Sie will nicht kommen.", "Wir dürfen gehen nicht.", "Ich soll das kaufen morgen."], "correctAnswer": "Sie will nicht kommen.", "explanation": "Modalverb an Position 2, Infinitiv am Ende", "difficulty": "medium", "topicName": "Modalverben (können, müssen, wollen, dürfen, sollen)"},
    {"id": "a1_09_q004", "subjectId": "a1_09", "type": "multiple_choice", "questionText": "\"Die Kinder ___ hier nicht spielen.\" – Welches Modalverb?", "options": ["müssen", "wollen", "dürfen", "sollen"], "correctAnswer": "dürfen", "explanation": "dürfen nicht = Verbots (keine Erlaubnis)", "difficulty": "easy", "topicName": "Modalverben (können, müssen, wollen, dürfen, sollen)"},
    {"id": "a1_09_q005", "subjectId": "a1_09", "type": "multiple_choice", "questionText": "\"Ich ___ leider nicht kommen.\" (Unfähigkeit) – Was fehlt?", "options": ["will", "muss", "kann", "soll"], "correctAnswer": "kann", "explanation": "können = Fähigkeit/Unfähigkeit", "difficulty": "easy", "topicName": "Modalverben (können, müssen, wollen, dürfen, sollen)"},
    {"id": "a1_09_q006", "subjectId": "a1_09", "type": "multiple_choice", "questionText": "Welcher Satz drückt einen Wunsch aus?", "options": ["Er muss früh aufstehen.", "Sie will eine Reise machen.", "Du darfst nicht rauchen.", "Wir sollen pünktlich sein."], "correctAnswer": "Sie will eine Reise machen.", "explanation": "wollen = Wunsch/Begehren", "difficulty": "easy", "topicName": "Modalverben (können, müssen, wollen, dürfen, sollen)"},
    {"id": "a1_09_q007", "subjectId": "a1_09", "type": "multiple_choice", "questionText": "\"Du ___ deiner Mutter helfen.\" (Anweisung) – Was passt?", "options": ["kannst", "willst", "sollst", "musst"], "correctAnswer": "sollst", "explanation": "sollen = Aufforderung/Rat von außen", "difficulty": "easy", "topicName": "Modalverben (können, müssen, wollen, dürfen, sollen)"},
    {"id": "a1_09_q008", "subjectId": "a1_09", "type": "multiple_choice", "questionText": "Welcher Satz ist FALSCH?", "options": ["Wir können Deutsch sprechen.", "Er darf keinen Alkohol trinken.", "Sie muss die Aufgabe machen.", "Ich will nicht nach Hause gehen nicht."], "correctAnswer": "Ich will nicht nach Hause gehen nicht.", "explanation": "Doppel Verneinung: nicht + nicht = falsch", "difficulty": "medium", "topicName": "Modalverben (können, müssen, wollen, dürfen, sollen)"},
    {"id": "a1_09_q009", "subjectId": "a1_09", "type": "multiple_choice", "questionText": "\"___ du Klavier spielen?\" – Was ist die passende Frage?", "options": ["Musst", "Kannst", "Sollst", "Darfst"], "correctAnswer": "Kannst", "explanation": "können = Fähigkeit: Kannst du Klavier spielen?", "difficulty": "easy", "topicName": "Modalverben (können, müssen, wollen, dürfen, sollen)"},
    {"id": "a1_09_q010", "subjectId": "a1_09", "type": "multiple_choice", "questionText": "\"Er ___ laut sprechen.\" – Welches Modalverb passt bei einem Verbot?", "options": ["soll nicht", "darf nicht", "muss nicht", "kann nicht"], "correctAnswer": "darf nicht", "explanation": "dürfen nicht = Verbot (keine Erlaubnis)", "difficulty": "medium", "topicName": "Modalverben (können, müssen, wollen, dürfen, sollen)"},
    {"id": "a1_09_q011", "subjectId": "a1_09", "type": "multiple_choice", "questionText": "\"Er ___ nicht Deutsch sprechen.\" (Unfähigkeit)", "options": ["will nicht", "kann nicht", "muss nicht", "darf nicht"], "correctAnswer": "kann nicht", "explanation": "können = Fähigkeit; kann nicht = nicht in der Lage", "difficulty": "easy", "topicName": "Modalverben (können, müssen, wollen, dürfen, sollen)"},
    {"id": "a1_09_q012", "subjectId": "a1_09", "type": "multiple_choice", "questionText": "\"___ du bitte das Fenster schließen?\" (höfliche Bitte)", "options": ["Willst", "Kannst", "Darfst", "Sollst"], "correctAnswer": "Kannst", "explanation": "Kannst du bitte...? = höfliche Bitte", "difficulty": "easy", "topicName": "Modalverben (können, müssen, wollen, dürfen, sollen)"},
    {"id": "a1_09_q013", "subjectId": "a1_09", "type": "multiple_choice", "questionText": "\"Die Schüler ___ die Hausaufgabe bis morgen ___.\" (Pflicht)", "options": ["müssen / machen", "wollen / machen", "können / machen", "sollen / machen"], "correctAnswer": "müssen / machen", "explanation": "müssen = Pflicht/Verbindlichkeit", "difficulty": "easy", "topicName": "Modalverben (können, müssen, wollen, dürfen, sollen)"},
    {"id": "a1_09_q014", "subjectId": "a1_09", "type": "multiple_choice", "questionText": "\"Ich ___ gerne Kaffee.\" – Welches Modalverb fehlt?", "options": ["will", "mag", "kann", "soll"], "correctAnswer": "mag", "explanation": "mögen = möchte (Präferenz): Ich mag Kaffee", "difficulty": "medium", "topicName": "Modalverben (können, müssen, wollen, dürfen, sollen)"},
    {"id": "a1_09_q015", "subjectId": "a1_09", "type": "multiple_choice", "questionText": "\"Du ___ hier rauchen.\" – Erlaubnis", "options": ["kannst", "musst", "wirst", "sollst"], "correctAnswer": "kannst", "explanation": "können = Erlaubnis (hier kannst du rauchen)", "difficulty": "easy", "topicName": "Modalverben (können, müssen, wollen, dürfen, sollen)"},
    {"id": "a1_09_q016", "subjectId": "a1_09", "type": "multiple_choice", "questionText": "Welcher Satz ist FALSCH?", "options": ["Ich will nach Hause.", "Du musst nicht kommen.", "Er darf nicht rauchen.", "Sie kann nicht schwimmen."], "correctAnswer": "Du musst nicht kommen.", "explanation": "müssen nicht = kein Zwang; grammatisch korrekt aber irreführend", "difficulty": "hard", "topicName": "Modalverben (können, müssen, wollen, dürfen, sollen)"},
    {"id": "a1_09_q017", "subjectId": "a1_09", "type": "multiple_choice", "questionText": "\"Sie ___ Ärztin werden.\" – Wunsch/Plan", "options": ["will", "muss", "kann", "darf"], "correctAnswer": "will", "explanation": "wollen = Wunsch/Berufsziel", "difficulty": "easy", "topicName": "Modalverben (können, müssen, wollen, dürfen, sollen)"},
    {"id": "a1_09_q018", "subjectId": "a1_09", "type": "multiple_choice", "questionText": "\"Man ___ in der Bibliothek leise ___.\" (Regel)", "options": ["soll / sein", "muss / sein", "will / sein", "darf / sein"], "correctAnswer": "soll / sein", "explanation": "sollen = Empfehlung/Regel (man soll leise sein)", "difficulty": "medium", "topicName": "Modalverben (können, müssen, wollen, dürfen, sollen)"},
    {"id": "a1_09_q019", "subjectId": "a1_09", "type": "multiple_choice", "questionText": "\"Wir ___ uns beeilen, sonst verpassen wir den Zug.\"", "options": ["müssen", "wollen", "können", "dürfen"], "correctAnswer": "müssen", "explanation": "müssen (Notwendigkeit): Wir müssen uns beeilen", "difficulty": "easy", "topicName": "Modalverben (können, müssen, wollen, dürfen, sollen)"},
    {"id": "a1_09_q020", "subjectId": "a1_09", "type": "multiple_choice", "questionText": "\"___ ich das Licht anmachen?\" – Frage nach Erlaubnis", "options": ["Darf", "Muss", "Will", "Soll"], "correctAnswer": "Darf", "explanation": "Darf ich...? = darf ich die Erlaubnis haben?", "difficulty": "easy", "topicName": "Modalverben (können, müssen, wollen, dürfen, sollen)"},
]

# ── TOPIC 10: Sätze bilden Q1-Q20 ──
q10 = [
    {"id": "a1_10_q001", "subjectId": "a1_10", "type": "multiple_choice", "questionText": "Welche Wortstellung ist korrekt für einen deutschen Hauptsatz?", "options": ["Heute ich gehe ins Kino.", "Ins Kino heute gehe ich.", "Heute gehe ich ins Kino.", "Gehe ich heute ins Kino."], "correctAnswer": "Heute gehe ich ins Kino.", "explanation": "Position 1: Temporal (heute), Position 2: Verb, Position 3: Subjekt", "difficulty": "easy", "topicName": "Sätze bilden (Wortstellung)"},
    {"id": "a1_10_q002", "subjectId": "a1_10", "type": "multiple_choice", "questionText": "\"Er trinkt jeden Morgen Kaffee.\" – Welches Element steht auf Position 1?", "options": ["Kaffee", "jeden Morgen", "Er", "trinkt"], "correctAnswer": "jeden Morgen", "explanation": "Position 1 = Temporaladverbial: jeden Morgen", "difficulty": "easy", "topicName": "Sätze bilden (Wortstellung)"},
    {"id": "a1_10_q003", "subjectId": "a1_10", "type": "multiple_choice", "questionText": "Wo steht das Verb in einem deutschen Hauptsatz?", "options": ["Am Anfang", "Am Ende", "Immer auf Position 2", "Nach dem Objekt"], "correctAnswer": "Immer auf Position 2", "explanation": "Im Hauptsatz: konjugiertes Verb auf Position 2", "difficulty": "easy", "topicName": "Sätze bilden (Wortstellung)"},
    {"id": "a1_10_q004", "subjectId": "a1_10", "type": "multiple_choice", "questionText": "Welcher Satz ist FALSCH?", "options": ["Morgen kommt er.", "Er kommt morgen.", "Kommt er morgen.", "Er morgen kommt."], "correctAnswer": "Er morgen kommt.", "explanation": "Richtige Wortstellung: Er kommt morgen (Verb muss auf Pos. 2)", "difficulty": "easy", "topicName": "Sätze bilden (Wortstellung)"},
    {"id": "a1_10_q005", "subjectId": "a1_10", "type": "multiple_choice", "questionText": "\"Ich ___ gestern zum Supermarkt ___.\" – Richtige Perfektstellung?", "options": ["bin / gegangen", "bin gegangen / zum Supermarkt", "habe / gegangen", "habe gegangen / zum"], "correctAnswer": "bin / gegangen", "explanation": "Perfekt mit sein: ist gegangen; TEKAMOLO: Zeit, Grund, Modal, Ort", "difficulty": "medium", "topicName": "Sätze bilden (Wortstellung)"},
    {"id": "a1_10_q006", "subjectId": "a1_10", "type": "multiple_choice", "questionText": "In einem Nebensatz (weil) steht das Verb...", "options": ["auf Position 2", "am Ende", "am Anfang", "vor dem Subjekt"], "correctAnswer": "am Ende", "explanation": "In Nebensätzen: Verb am Ende (weil er geht, weil er ging)", "difficulty": "easy", "topicName": "Sätze bilden (Wortstellung)"},
    {"id": "a1_10_q007", "subjectId": "a1_10", "type": "multiple_choice", "questionText": "Welcher Satz mit \"weil\" ist korrekt?", "options": ["Ich bleibe zu Hause, weil es regnet.", "Ich bleibe zu Hause, weil regnet es.", "Weil regnet es, ich bleibe zu Hause.", "Ich bleibe, weil es zu Hause regnet."], "correctAnswer": "Ich bleibe zu Hause, weil es regnet.", "explanation": "weil-Satz: Verb am Ende; Subjekt vor Verb", "difficulty": "easy", "topicName": "Sätze bilden (Wortstellung)"},
    {"id": "a1_10_q008", "subjectId": "a1_10", "type": "multiple_choice", "questionText": "Wo steht das Modalverb im Hauptsatz?", "options": ["Am Ende", "Auf Position 1", "Auf Position 2", "Nach dem Infinitiv"], "correctAnswer": "Auf Position 2", "explanation": "Modalverb ersetzt konjugierte Verb auf Position 2", "difficulty": "easy", "topicName": "Sätze bilden (Wortstellung)"},
    {"id": "a1_10_q009", "subjectId": "a1_10", "type": "multiple_choice", "questionText": "\"Manchmal ___ er ___ Musik.\" – Richtige Wortstellung?", "options": ["hört / laut", "laut / hört", "hört er / laut Musik", "er / laut hört"], "correctAnswer": "hört / laut", "explanation": "Manchmal (Pos 1) + er (Pos 3) + hört (Pos 2) + laut (Angabe) + Musik", "difficulty": "medium", "topicName": "Sätze bilden (Wortstellung)"},
    {"id": "a1_10_q010", "subjectId": "a1_10", "type": "multiple_choice", "questionText": "Welcher Satz ist grammatisch korrekt?", "options": ["Er hat gestern das Buch gelesen.", "Er gestern hat gelesen das Buch.", "Gestern er hat das Buch gelesen.", "Das Buch hat gelesen er gestern."], "correctAnswer": "Er hat gestern das Buch gelesen.", "explanation": "Richtige Stellung: Subjekt + Hilfsverb + Temporal + Objekt + Partizip", "difficulty": "easy", "topicName": "Sätze bilden (Wortstellung)"},
    {"id": "a1_10_q011", "subjectId": "a1_10", "type": "multiple_choice", "questionText": "\"___ er nach Hause, ___ er müde war.\" – Welche Konjunktion?", "options": ["Weil / weil", "Als / als", "Wenn / wenn", "Dass / dass"], "correctAnswer": "Als / als", "explanation": "Als = zeitlicher Nebensatz (einmalige Vergangenheit)", "difficulty": "medium", "topicName": "Sätze bilden (Wortstellung)"},
    {"id": "a1_10_q012", "subjectId": "a1_10", "type": "multiple_choice", "questionText": "Welche Wortstellung ist im Nebensatz korrekt?", "options": ["...dass er geht nach Hause", "...dass er nach Hause geht", "...dass nach Hause er geht", "...dass geht nach Hause er"], "correctAnswer": "...dass er nach Hause geht", "explanation": "Im Nebensatz: Subjekt + Temporal + Ort + Verb am Ende", "difficulty": "easy", "topicName": "Sätze bilden (Wortstellung)"},
    {"id": "a1_10_q013", "subjectId": "a1_10", "type": "multiple_choice", "questionText": "\"Er ist krank, ___ er nicht kommen kann.\" – Welche Konjunktion?", "options": ["aber", "denn", "weil", "dass"], "correctAnswer": "weil", "explanation": "weil = Grund; Verb am Ende im Nebensatz", "difficulty": "easy", "topicName": "Sätze bilden (Wortstellung)"},
    {"id": "a1_10_q014", "subjectId": "a1_10", "type": "multiple_choice", "questionText": "\"Wenn es regnet, ___ ich zu Hause.\" – Was fehlt?", "options": ["bleibe", "bleibst", "bleibt", "bleiben"], "correctAnswer": "bleibe", "explanation": "wenn-Satz (Bedingung): ich bleibe (Position 2)", "difficulty": "easy", "topicName": "Sätze bilden (Wortstellung)"},
    {"id": "a1_10_q015", "subjectId": "a1_10", "type": "multiple_choice", "questionText": "Welcher Satz hat die FALSCHE Wortstellung?", "options": ["Ich lese ein Buch.", "Er kommt morgen.", "Morgen er kommt.", "Wir lernen Deutsch."], "correctAnswer": "Morgen er kommt.", "explanation": "Richtig: Er kommt morgen oder Morgen kommt er", "difficulty": "easy", "topicName": "Sätze bilden (Wortstellung)"},
    {"id": "a1_10_q016", "subjectId": "a1_10", "type": "multiple_choice", "questionText": "\"___ die Prüfung vorbei ist, lernt er jeden Tag.\" – Welches Wort fehlt?", "options": ["Bis", "Nachdem", "Während", "Wenn"], "correctAnswer": "Bis", "explanation": "Bis = zeitlich; die Prüfung vorbei ist (Ende der Handlung)", "difficulty": "medium", "topicName": "Sätze bilden (Wortstellung)"},
    {"id": "a1_10_q017", "subjectId": "a1_10", "type": "multiple_choice", "questionText": "\"Nicht nur ___ er die Prüfung, ___ er hat auch einen Job gefunden.\"", "options": ["hat bestanden / sondern", "bestand / aber", "besteht / sondern auch", "hatten / sondern"], "correctAnswer": "hat bestanden / sondern", "explanation": "Nicht nur... sondern auch: hat bestanden + hat gefunden", "difficulty": "medium", "topicName": "Sätze bilden (Wortstellung)"},
    {"id": "a1_10_q018", "subjectId": "a1_10", "type": "multiple_choice", "questionText": "Welche Wortstellung ist bei WENN-Sätzen korrekt?", "options": ["Wenn kommt er nach Hause.", "Wenn er kommt nach Hause.", "Wenn er nach Hause kommt.", "Wenn nach Hause kommt er."], "correctAnswer": "Wenn er nach Hause kommt.", "explanation": "Im wenn-Satz: wenn + Subjekt + Ort + Verb", "difficulty": "easy", "topicName": "Sätze bilden (Wortstellung)"},
    {"id": "a1_10_q019", "subjectId": "a1_10", "type": "multiple_choice", "questionText": "\"Er ist müde, ___ er hat lange gearbeitet.\" – Welche Wortstellung ist korrekt?", "options": ["denn hat er", "denn er hat", "hat er denn", "er hat denn"], "correctAnswer": "denn er hat", "explanation": "denn leitet keinen Nebensatz ein: Normalstellung", "difficulty": "medium", "topicName": "Sätze bilden (Wortstellung)"},
    {"id": "a1_10_q020", "subjectId": "a1_10", "type": "multiple_choice", "questionText": "\"Am Wochenende ___ wir oft ___.\" – Richtige Wortstellung?", "options": ["fahren / ins Kino", "ins Kino / fahren", "fahren ins Kino / wir", "wir / fahren ins Kino"], "correctAnswer": "fahren / ins Kino", "explanation": "Am Wochenende (Pos1) + wir (Pos3) + fahren (Pos2) + ins Kino", "difficulty": "medium", "topicName": "Sätze bilden (Wortstellung)"},
]

topics = [
    ("a1_01", "1. Verben konjugieren (sein, haben, werden)", q1),
    ("a1_02", "2. Nomen und Artikel (der/die/das + Pluralformen)", q2),
    ("a1_03", "3. Präsens (Gegenwart)", q3),
    ("a1_04", "4. Akkusativ (Wen-Fall)", q4),
    ("a1_05", "5. Dativ (Wem-Fall)", q5),
    ("a1_06", "6. Präpositionen (in, auf, an, mit, nach...)", q6),
    ("a1_07", "7. Verben mit Präpositionen (warten auf, denken an...)", q7),
    ("a1_08", "8. Perfekt (haben/sein + Partizip II)", q8),
    ("a1_09", "9. Modalverben (können, müssen, wollen, dürfen, sollen)", q9),
    ("a1_10", "10. Sätze bilden (Wortstellung)", q10),
]

base = "app/src/main/assets/"
for file_id, topic_name, questions in topics:
    filepath = base + file_id + ".json"
    data = {
        "version": "1.0",
        "subjectId": file_id,
        "topicName": topic_name,
        "totalQuestions": len(questions),
        "questions": questions
    }
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"Written: {filepath} ({len(questions)} questions)")

print("\nAll done! 20 questions per topic.")