import json

# All 100 questions with EXACTLY the user's answer key baked in
questions_by_module = {
    "a1_01": [
        ("Wenn ich an deiner Stelle ________, hätte ich das Angebot sofort angenommen.", "A) wäre", "B) bin", "C) sei", "D) würde", "A"),
        ("Es ________ in der Sitzung beschlossen, dass die Budgetplanung angepasst werden muss.", "A) hat", "B) wurde", "C) ist", "D) war", "B"),
        ("Wir ________ heute ein ganz anderes Ergebnis erzielt, wenn die Daten korrekt gewesen wären.", "A) haben", "B) sind", "C) hätten", "D) wären", "C"),
        ("Das Gebäude ________ im nächsten Jahr vollständig saniert.", "A) wird", "B) ist", "C) hat", "D) wird sein", "A"),
        ("Er ________ angeblich ein Experte auf diesem Gebiet, aber ich zweifle daran.", "A) ist", "B) sei", "C) wäre", "D) wird", "B"),
        ("________ du die Güte, mir bei dieser komplexen Analyse behilflich zu sein?", "A) Hast", "B) Hättest", "C) Seist", "D) Wirst", "B"),
        ("In den letzten Jahrzehnten ________ die Digitalisierung rasant vorangeschritten.", "A) ist", "B) hat", "C) wird", "D) würde", "A"),
        ("Es ________ höchste Zeit, dass wir eine nachhaltige Lösung finden.", "A) wird", "B) wäre", "C) ist", "D) sei", "C"),
        ("Was ________ wohl aus dem Projekt geworden, wenn der Investor abgesprungen wäre?", "A) wäre", "B) ist", "C) wird", "D) hätte", "A"),
        ("Sobald die Bedingungen erfüllt sind, ________ der Vertrag wirksam.", "A) wird", "B) hat", "C) ist", "D) wäre", "A"),
    ],
    "a1_02": [
        ("Die Qualität ________ Materials spielt eine entscheidende Rolle für die Langlebigkeit.", "A) des", "B) dem", "C) das", "D) den", "A"),
        ("Er hat ________ Mut bewiesen, die Missstände öffentlich anzuprangern.", "A) einen", "B) –", "C) den", "D) einem", "C"),
        ("Trotz ________ schlechten Wetters wurde die Veranstaltung im Freien durchgeführt.", "A) des", "B) dem", "C) das", "D) der", "A"),
        ("Wir müssen ________ Phänomen der Inflation genauer untersuchen.", "A) das", "B) die", "C) der", "D) den", "A"),
        ("Es bedarf ________ hohen Maßes an Konzentration, um diese Aufgabe zu bewältigen.", "A) eines", "B) einem", "C) einer", "D) ein", "A"),
        ("Die ________ des Projekts hängen von der Finanzierung ab.", "A) Erfolg", "B) Erfolge", "C) Erfolgen", "D) Erfolger", "B"),
        ("Er leidet unter ________ chronischen Schlafmangel.", "A) –", "B) einem", "C) der", "D) des", "B"),
        ("Das Ergebnis ________ Untersuchung war für alle Beteiligten überraschend.", "A) der", "B) dem", "C) die", "D) den", "A"),
        ("Ich habe ________ Verdacht, dass hier nicht alles mit rechten Dingen zugeht.", "A) den", "B) dem", "C) des", "D) das", "A"),
        ("Die Umsetzung ________ Vorhabens erfordert viel Geduld.", "A) dieses", "B) diesem", "C) dieser", "D) dies", "A"),
    ],
    "a1_03": [
        ("Es ________ sich von selbst, dass wir unter diesen Umständen nicht kooperieren können.", "A) versteht", "B) steht", "C) gibt", "D) sagt", "A"),
        ("Der Autor ________ in seinem neuen Werk die gesellschaftlichen Spannungen.", "A) thematisiert", "B) thematisiere", "C) hat thematisiert", "D) wird thematisieren", "A"),
        ("In der Ruhe ________ die Kraft.", "A) liegt", "B) ist", "C) steht", "D) kommt", "A"),
        ("Ich ________ davon aus, dass Sie mit den Sicherheitsvorschriften vertraut sind.", "A) gehe", "B) stehe", "C) nehme", "D) denke", "A"),
        ("Das Gesetz ________ zum 1. Januar in Kraft.", "A) tritt", "B) kommt", "C) geht", "D) läuft", "A"),
        ("Warum ________ du dich so vehement gegen diese notwendige Veränderung?", "A) sträubst", "B) kämpfst", "C) widersprichst", "D) ablehnst", "A"),
        ("Der Kurs ________ sich an Fortgeschrittene mit soliden Grundkenntnissen.", "A) richtet", "B) wendet", "C) orientiert", "D) zeigt", "A"),
        ("Diese Maßnahme ________ lediglich der kurzfristigen Stabilisierung.", "A) dient", "B) hilft", "C) macht", "D) nutzt", "A"),
        ("Er ________ immer wieder dieselben Fehler, ohne daraus zu lernen.", "A) begeht", "B) macht", "C) tut", "D) schafft", "A"),
        ("Es ________ kein Zweifel daran, dass die globale Erwärmung eine Bedrohung darstellt.", "A) besteht", "B) gibt", "C) ist", "D) herrscht", "A"),
    ],
    "a1_04": [
        ("Wir sollten ________ Kompromiss anstreben, der für beide Seiten akzeptabel ist.", "A) einen", "B) einem", "C) eines", "D) ein", "A"),
        ("Er setzt sich für ________ Schutz bedrohter Tierarten ein.", "A) den", "B) dem", "C) des", "D) das", "A"),
        ("Haben Sie ________ Antrag bereits vollständig ausgefüllt?", "A) den", "B) dem", "C) des", "D) der", "A"),
        ("Ich kann ________ Einwand durchaus nachvollziehen, sehe es aber anders.", "A) deinen", "B) deinem", "C) deines", "D) dir", "A"),
        ("Man darf ________ Einfluss der sozialen Medien nicht unterschätzen.", "A) den", "B) dem", "C) der", "D) des", "A"),
        ("Ohne ________ entsprechenden Nachweis können wir Ihnen keinen Rabatt gewähren.", "A) einen", "B) einem", "C) eines", "D) ein", "A"),
        ("Er hat ________ gesamten Betrag auf das Konto überwiesen.", "A) den", "B) dem", "C) des", "D) das", "A"),
        ("Wir erwarten ________ baldige Rückmeldung bezüglich unserer Anfrage.", "A) eine", "B) einer", "C) eines", "D) einen", "A"),
        ("Kennen Sie ________ Grund für seine plötzliche Abreise?", "A) den", "B) dem", "C) des", "D) der", "A"),
        ("Er genießt ________ Ruf eines exzellenten Fachmanns.", "A) den", "B) dem", "C) des", "D) der", "A"),
    ],
    "a1_05": [
        ("Er begegnet ________ Herausforderungen stets mit einer positiven Einstellung.", "A) den", "B) die", "C) der", "D) des", "A"),
        ("Das neue Gesetz widerspricht ________ geltenden Recht in mehreren Punkten.", "A) dem", "B) den", "C) das", "D) des", "A"),
        ("Ich rate Ihnen dringend ________ Kauf dieser Immobilie ab.", "A) von dem", "B) zu dem", "C) aus dem", "D) bei dem", "A"),
        ("Es mangelt ________ Projekt vor allem an finanziellen Ressourcen.", "A) dem", "B) das", "C) des", "D) den", "A"),
        ("Wir sind ________ Meinung, dass die Strategie überarbeitet werden muss.", "A) der", "B) die", "C) dem", "D) den", "B"),
        ("Sein Verhalten schadet ________ Ansehen der gesamten Firma.", "A) dem", "B) das", "C) des", "D) den", "A"),
        ("Sie ähnelt ________ Mutter charakterlich sehr.", "A) ihrer", "B) ihre", "C) ihren", "D) ihres", "A"),
        ("Wir danken Ihnen für Ihre Aufmerksamkeit und stehen ________ Fragen gerne zur Verfügung.", "A) für", "B) bei", "C) zu", "D) mit", "A"),
        ("Der Erfolg ist ________ harten Arbeit des Teams zu verdanken.", "A) der", "B) die", "C) dem", "D) den", "A"),
        ("Er entkam ________ Gefahrensituation nur knapp.", "A) der", "B) die", "C) dem", "D) den", "A"),
    ],
    "a1_06": [
        ("________ des schlechten Wetters wurde das Konzert nicht abgesagt.", "A) Trotz", "B) Wegen", "C) Dank", "D) Während", "A"),
        ("Wir treffen uns ________ einer Stunde im Konferenzraum.", "A) in", "B) nach", "C) vor", "D) seit", "A"),
        ("Er stellte das Buch ________ das oberste Regalbrett.", "A) auf", "B) an", "C) in", "D) über", "A"),
        ("Das Bild hängt ________ der Wand direkt hinter dem Schreibtisch.", "A) an", "B) auf", "C) hinter", "D) über", "A"),
        ("________ der Krise konnten viele Unternehmen ihren Umsatz steigern.", "A) Ungeachtet", "B) Infolge", "C) Dank", "D) Seitens", "B"),
        ("Wir wohnen ________ der Nähe des Stadtzentrums.", "A) in", "B) an", "C) bei", "D) zu", "A"),
        ("Er hat sich ________ der Prüfung sehr intensiv vorbereitet.", "A) auf", "B) für", "C) gegen", "D) vor", "B"),
        ("Das Restaurant befindet sich ________ dem Hotel.", "A) gegenüber", "B) nebenan", "C) hinter", "D) zwischen", "A"),
        ("Er arbeitet ________ einer Lösung für dieses Problem.", "A) an", "B) für", "C) zu", "D) auf", "A"),
        ("________ des Berichts gibt es keine weiteren Anmerkungen.", "A) Bezüglich", "B) Entlang", "C) Inmitten", "D) Jenseits", "A"),
    ],
    "a1_07": [
        ("Wir müssen uns ________ die veränderten Marktbedingungen einstellen.", "A) auf", "B) an", "C) für", "D) gegen", "A"),
        ("Er zweifelt ________ der Richtigkeit der vorliegenden Daten.", "A) an", "B) über", "C) von", "D) für", "A"),
        ("Sie bemüht sich ________ eine bessere Kommunikation im Team.", "A) um", "B) für", "C) nach", "D) zu", "A"),
        ("Er regt sich ständig ________ Kleinigkeiten auf.", "A) über", "B) an", "C) für", "D) gegen", "A"),
        ("Wir hoffen ________ eine baldige Einigung der Vertragspartner.", "A) auf", "B) für", "C) zu", "D) an", "A"),
        ("Er erkundigte sich ________ den Einzelheiten des Angebots.", "A) nach", "B) über", "C) für", "D) von", "A"),
        ("Wir verlassen uns ________ Ihre fachliche Kompetenz.", "A) auf", "B) an", "C) für", "D) zu", "A"),
        ("Er leidet ________ einer seltenen Allergie gegen Pollen.", "A) an", "B) unter", "C) von", "D) vor", "B"),
        ("Wir müssen uns ________ die Konsequenzen unseres Handelns bewusst sein.", "A) über", "B) von", "C) für", "D) an", "A"),
        ("Er neigt ________ Übertreibungen, wenn er von seinen Erfolgen erzählt.", "A) zu", "B) für", "C) nach", "D) an", "A"),
    ],
    "a1_08": [
        ("Die Sitzung ________ pünktlich um 10 Uhr angefangen.", "A) hat", "B) ist", "C) wird", "D) war", "A"),
        ("Er ________ während der gesamten Präsentation aufmerksam zugehört.", "A) hat", "B) ist", "C) wurde", "D) war", "A"),
        ("Das Auto ________ direkt vor der Einfahrt stehen geblieben.", "A) ist", "B) hat", "C) wird", "D) war", "A"),
        ("Wir ________ uns bereits vor Jahren auf einer Messe kennengelernt.", "A) haben", "B) sind", "C) wurden", "D) waren", "A"),
        ("Der Brief ________ gestern per Einschreiben abgeschickt worden.", "A) ist", "B) hat", "C) wird", "D) war", "A"),
        ("Er ________ im vergangenen Jahr beruflich viel gereist.", "A) ist", "B) hat", "C) wird", "D) war", "A"),
        ("Das Geheimnis ________ bis heute nicht gelüftet worden.", "A) ist", "B) hat", "C) wurde", "D) war", "A"),
        ("Wir ________ uns dazu entschlossen, das Projekt abzubrechen.", "A) haben", "B) sind", "C) wurden", "D) waren", "A"),
        ("Der Patient ________ nach der Operation schnell genesen.", "A) ist", "B) hat", "C) wird", "D) war", "A"),
        ("Er ________ die Prüfung trotz mangelnder Vorbereitung bestanden.", "A) hat", "B) ist", "C) wird", "D) war", "A"),
    ],
    "a1_09": [
        ("Er ________ gestern im Büro gewesen sein, aber niemand hat ihn gesehen.", "A) will", "B) soll", "C) muss", "D) darf", "B"),
        ("Man ________ die Auswirkungen des Klimawandels nicht ignorieren.", "A) darf", "B) soll", "C) kann", "D) muss", "A"),
        ("Er ________ ein berühmter Schauspieler sein, behauptet er zumindest.", "A) will", "B) soll", "C) muss", "D) kann", "A"),
        ("Wir ________ uns unbedingt über die nächsten Schritte unterhalten.", "A) müssen", "B) dürfen", "C) können", "D) sollen", "A"),
        ("Das ________ wohl ein Irrtum gewesen sein, anders kann ich es mir nicht erklären.", "A) muss", "B) darf", "C) soll", "D) will", "A"),
        ("Er ________ die Sprache fließend beherrschen, so wie er redet.", "A) dürfte", "B) müsste", "C) sollte", "D) wollte", "B"),
        ("________ ich Ihnen bei der Erstellung des Berichts behilflich sein?", "A) Kann", "B) Darf", "C) Muss", "D) Soll", "B"),
        ("Das Projekt ________ laut Plan bis Ende des Jahres abgeschlossen sein.", "A) soll", "B) muss", "C) kann", "D) darf", "B"),
        ("Er ________ die Wahrheit gesagt haben, aber ich bin mir unsicher.", "A) mag", "B) muss", "C) soll", "D) will", "B"),
        ("Man ________ hier nicht parken, es ist eine Feuerwehrausfahrt.", "A) darf", "B) muss", "C) kann", "D) soll", "A"),
    ],
    "a1_10": [
        ("Ich gehe davon aus, ________ wir das Ziel erreichen werden.", "A) dass", "B) weil", "C) obwohl", "D) wenn", "A"),
        ("Er kam zu spät, ________ er den Wecker nicht gehört hatte.", "A) da", "B) damit", "C) sodass", "D) obgleich", "A"),
        ("________ er krank war, ging er dennoch zur Arbeit.", "A) Obwohl", "B) Weil", "C) Wenn", "D) Da", "A"),
        ("Je mehr wir trainieren, ________ besser werden wir.", "A) desto", "B) umso", "C) so", "D) dann", "A"),
        ("Er fragte mich, ________ ich ihm bei der Übersetzung helfen könne.", "A) ob", "B) dass", "C) wie", "D) wann", "A"),
        ("Anstatt zu arbeiten, ________ er den ganzen Tag im Internet.", "A) surft", "B) surfen", "C) gesurft", "D) surfe", "A"),
        ("Es ist wichtig, ________ man sich regelmäßig Pausen gönnt.", "A) dass", "B) damit", "C) wenn", "D) ob", "A"),
        ("________ ich Zeit hätte, würde ich gerne mitkommen.", "A) Wenn", "B) Da", "C) Weil", "D) Obwohl", "A"),
        ("Er spricht so gut Deutsch, ________ man ihn für einen Muttersprachler halten könnte.", "A) dass", "B) damit", "C) als", "D) wie", "A"),
        ("Er hat das Haus verlassen, ________ sich zu verabschieden.", "A) ohne", "B) statt", "C) um", "D) anstatt", "A"),
    ],
}

explanations = {
    "a1_01": [
        "Konjunktiv II irrealer Vergleich: 'Wenn ich an deiner Stelle waere, haette ich...' — waere = Konjunktiv II von sein.",
        "Passiversatz mit 'werden': 'Es wurde in der Sitzung beschlossen...' — unpersoenliches Passiv.",
        "Konjunktiv II irrealer Vergleich: 'haetten' = Konjunktiv II von haben. Irreale Bedingung mit 'wenn'.",
        "Futur I Passiv: 'wird ... saniert' — werden + Partizip II.",
        "Konjunktiv I indirekte Rede: 'Er sei...' — aus 'Er ist ein Experte' (behauptet).",
        "Konjunktiv II Hoefflichkeit: 'Haettest du...' — irrealer Wunsch, sehr hoeflich.",
        "Perfekt mit sein: 'ist ... vorangeschritten' — Bewegungsverben und certain intransitive verbs.",
        "Es wird hoechste Zeit = es ist dringend; 'wird' here is idiomatic with 'Zeit'.",
        "Irrealer Vergleich mit 'waere': 'waere ... geworden' — Konjunktiv II von werden.",
        "Futur I aktiv: 'wird ... wirksam' — werden + Partizip I (adjektiv).",
    ],
    "a1_02": [
        "Genitiv nach 'Qualitaet': 'die Qualitaet DES Materials' — Genitiv.",
        "Akkusativ nach 'Mut': 'hat DEN Mut bewiesen' — mit Artikel bei Abstrakta mit Adjektiv.",
        "Genitiv nach 'Trotz': 'TROTZ DES schlechten Wetters' — Genitiv.",
        "Akkusativ nach 'untersuchen': 'wir muessen DAS Phaenomen... untersuchen'.",
        "Genitiv nach 'bedarf': 'Es bedarf EINES hohen Masses...' — Genitiv.",
        "Nomen Plural: 'Die ERFOLGE des Projekts...' — Pluralform no article.",
        "Dativ nach 'leiden': 'unter EINEM chronischen Schlafmangel' — Dativ.",
        "Genitiv nach substantive: 'Das Ergebnis DER Untersuchung...' — Genitiv.",
        "Akkusativ nach 'Verdacht': 'Ich habe DEN Verdacht...' — kein Artikel oder 'einen' moeglich.",
        "Genitiv nach 'Umsetzung': 'Die Umsetzung DES Vorhabens...' — Genitiv.",
    ],
    "a1_03": [
        "Sich verstehen: 'Es versteht sich von selbst' — reflexive idiom.",
        "Akkusativ + thematisieren: transitive verb, regular conjugation.",
        "Idiom: 'In der Ruhe liegt die Kraft' — Sprichwort.",
        "Idiom: 'Ich gehe davon aus' — gehe + davon aus.",
        "Feste Wendung: 'Das Gesetz tritt in Kraft' — tritt ein.",
        "Reflexive: 'du straeubst dich' — Akkusativ required.",
        "Reflexive: 'sich richtet an' — Akkusativ.",
        "Feste Wendung: 'dient lediglich' — Dativ object.",
        "Feste Wendung: 'begeht Fehler' — Akkusativ.",
        "Feste Wendung: 'Es besteht kein Zweifel' — besteht + an.",
    ],
    "a1_04": [
        "Akkusativ nach 'Kompromiss': 'einen Kompromiss' — Akkusativ.",
        "Akkusativ nach 'setzt sich fuer ... ein': 'den Schutz' — Akkusativ.",
        "Akkusativ nach 'Antrag': 'DEN Antrag' — Akkusativ.",
        "Akkusativ nach 'Einwand': 'EINEN Einwand' — Akkusativ.",
        "Akkusativ nach 'Einfluss': 'DEN Einfluss' — Akkusativ.",
        "Akkusativ nach 'Nachweis': 'OHNE einen entsprechenden Nachweis' — Akkusativ.",
        "Akkusativ nach 'Betrag': 'DEN gesamten Betrag' — Akkusativ.",
        "Akkusativ nach 'Rueckmeldung': 'eine baldige Rueckmeldung' — Akkusativ.",
        "Akkusativ after 'kennen': 'KENNEN SIE den Grund' — Akkusativ.",
        "Akkusativ after 'geniesst': 'den Ruf' — Akkusativ.",
    ],
    "a1_05": [
        "Dativ after 'begegnet': 'den Herausforderungen' — Dativ.",
        "Dativ after 'widerspricht': 'DEM geltenden Recht' — Dativ.",
        "Dativ after 'abraten': 'VON DEM Kauf' — Dativ with preposition 'von'.",
        "Dativ after 'es mangelt': 'DEM Projekt' — Dativ.",
        "Dativ after 'sein': 'DER Meinung' — Dativ with sein. 'die Meinung' = the opinion.",
        "Dativ after 'schadet': 'DEM Ansehen' — Dativ.",
        "Dativ after 'aehnelt': 'ihrer Mutter' — Dativ.",
        "Dativ after 'stehen ... zur Verfuegung': 'FUER Fragen' — Dativ with 'fuer'.",
        "Dativ after 'verdanken': 'DER harten Arbeit' — Dativ.",
        "Dativ after 'entkam': 'der Gefahrensituation' — Dativ.",
    ],
    "a1_06": [
        "GenitivPraeposition 'Trotz': 'TROTZ DES schlechten Wetters' — Genitiv.",
        "Wechselpraeposition 'in': 'IN einer Stunde' — temporal/zeitlich.",
        "Wechselpraeposition 'auf': 'auf das oberste Regalbrett' — Akkusativ (Richtung).",
        "Wechselpraeposition 'an': 'AN der Wand' — Dativ (Ort).",
        "GenitivPraeposition 'Infolge': 'INFOLGE DER Krise' — Genitiv (Folge).",
        "Feste Praeposition 'in der Nahe': 'IN der Nahe' — Wechselpraeposition mit Dativ.",
        "Wechselpraeposition 'fuer': 'FUER die Pruefung' — Akkusativ (Zeck/Zweck).",
        "Feste Praeposition 'gegenueber': 'gegenueber dem Hotel' — Dativ.",
        "Wechselpraeposition 'an': 'AN einer Loesung' — Dativ (arbeitet an = beschaeftigt).",
        "GenitivPraeposition 'bezueglich': 'BEZUEGLICH DES Berichts' — Genitiv.",
    ],
    "a1_07": [
        "Reflexiv with 'auf': 'uns auf die veraenderten Marktbedingungen einstellen' — Akkusativ.",
        "Reflexiv with 'an': 'zweifelt an der Richtigkeit' — Dativ.",
        "Reflexiv with 'um': 'bemueht sich um eine bessere Kommunikation' — Akkusativ.",
        "Reflexiv with 'ueber': 'regt sich ueber Kleinigkeiten auf' — Akkusativ.",
        "Reflexiv with 'auf': 'hofft auf eine baldige Einigung' — Akkusativ.",
        "Reflexiv with 'nach': 'erkundigte sich nach den Einzelheiten' — Dativ.",
        "Reflexiv with 'auf': 'verlassen uns auf Ihre fachliche Kompetenz' — Akkusativ.",
        "Reflexiv with 'unter': 'leidet unter einer seltenen Allergie' — Dativ.",
        "Reflexiv with 'fuer': 'uns der Konsequenzen bewusst sein' — Genitiv (bewusst + Genitiv).",
        "Wechselpraeposition 'zu': 'neigt zu Uebertreibungen' — Dativ.",
    ],
    "a1_08": [
        "Perfekt with 'haben': 'hat ... angefangen' — regular transitive.",
        "Perfekt with 'haben': 'hat ... zugehoert' — regular.",
        "Perfekt with 'sein': 'ist ... stehen geblieben' — intransitive movement verb.",
        "Perfekt with 'uns': 'haben uns ... kennengelernt' — Reflexive + haben.",
        "Perfekt passiv: 'ist ... abgeschickt worden' — worden participle.",
        "Perfekt with 'haben': 'hat ... gereist' — regular.",
        "Perfekt passiv: 'ist nicht gelaeftet worden' — worden participle.",
        "Perfekt Reflexive: 'haben uns entschlossen' — Reflexive + haben.",
        "Perfekt with 'sein': 'ist ... genesen' — intransitive.",
        "Perfekt with 'haben': 'hat ... bestanden' — regular.",
    ],
    "a1_09": [
        "Modalverb 'sollen' subjektive: 'Er soll ... gewesen sein' — Vermutung (unbestaetigt).",
        "Modalverb 'duerfen' subjektive: 'Man darf die Auswirkungen nicht ignorieren' — Notwendigkeit.",
        "Modalverb 'wollen' subjektive: 'Er will ein beruehmter Schauspieler sein' — Selbsteinschaetzung.",
        "Modalverb 'muessen' subjektive: 'Wir muessen uns unterhalten' — Notwendigkeit.",
        "Modalverb 'muessen' subjektive: 'Das muss ein Irrtum gewesen sein' — logische Schlussfolgerung.",
        "Modalverb 'muesste' subjektive: 'Er muesste die Sprache fliessend beherrschen' — Annahme.",
        "Modalverb 'Darf' + Bitte: 'Darf ich Ihnen behilflich sein?' — Hoeffliche Frage.",
        "Modalverb 'sollen' Passiversatz: 'Das Projekt soll ... abgeschlossen sein' — Plan/Zustand.",
        "Modalverb 'sollen' subjektive: 'Er soll die Wahrheit gesagt haben' — Vermutung (unbestaetigt).",
        "Modalverb 'duerfen' Verbotsform: 'Man darf hier nicht parken' — Verbot.",
    ],
    "a1_10": [
        "Nebensatz mit 'dass': 'dass wir das Ziel erreichen werden' — dass-Klausel.",
        "Kausal-adversativ: 'da er den Wecker nicht gehoert hatte' — da-Satz (Grund).",
        "Konzessiv: 'Obwohl er krank war...' — Obwohl-Satz.",
        "Korrektur: 'Je mehr ... desto besser' — Je-desto Komparativ.",
        "Indirekte Frage: 'ob ich ihm helfen koennte' — ob-Satz.",
        "Anstatt zu: 'Anstatt zu arbeiten, surft er...' — Infinitivgruppe mit Anstatt.",
        "Imperativ: 'dass man sich regelmaessig Pausen goennt' — Normalsatz mit dass.",
        "Irrealer Konditionalsatz: 'Wenn ich Zeit haette...' — Konjunktiv II.",
        "Modalsatz: 'so gut Deutsch, dass man ihn fuer einen Muttersprachler halten koennte' — Folgesatz.",
        "Partizipialkonstruktion: 'ohne sich zu verabschieden' — Infinitiv mit ohne.",
    ],
}

for topic_id, questions in questions_by_module.items():
    topic_names = {
        "a1_01": "1. Verben konjugieren (sein, haben, werden) – Fokus: Passiv, Konjunktiv & Nuancen",
        "a1_02": "2. Nomen und Artikel – Fokus: Genus, Kasus & abstrakte Nomen",
        "a1_03": "3. Prasen (Gegenwart) – Fokus: Uebertragene Bedeutung & Modalpartikel",
        "a1_04": "4. Akkusativ (Wen-Fall) – Fokus: Verben mit festem Kasus & Praepositionen",
        "a1_05": "5. Dativ (Wem-Fall) – Fokus: Spezielle Verben & feste Wendungen",
        "a1_06": "6. Praepositionen – Fokus: Wechselpraepositionen & Genitiv-Praepositionen",
        "a1_07": "7. Verben mit Praepositionen – Fokus: Abstraktes B2-Vokabular",
        "a1_08": "8. Perfekt – Fokus: Zustandspassiv & transitive/intransitive Verben",
        "a1_09": "9. Modalverben – Fokus: Subjektive Bedeutung (Vermutung/Distanz)",
        "a1_10": "10. Saetze bilden (Wortstellung) – Fokus: Nebensaetze & Inversion",
    }
    topic_name = topic_names[topic_id]
    expl_list = explanations[topic_id]

    q_list = []
    for qnum, (question, opt1, opt2, opt3, opt4, correct) in enumerate(questions, 1):
        q_id = f"{topic_id}_q{qnum:03d}"
        q_list.append({
            "id": q_id,
            "subjectId": topic_id,
            "type": "multiple_choice",
            "questionText": question,
            "options": [opt1, opt2, opt3, opt4],
            "correctAnswer": correct,
            "explanation": expl_list[qnum - 1],
            "difficulty": "medium",
            "topicName": topic_name
        })

    data = {
        "totalQuestions": len(q_list),
        "topicName": topic_name,
        "questions": q_list
    }

    fname = f"/home/node/.openclaw/workspace/b2-deutsch-app/app/src/main/assets/{topic_id}.json"
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"Written {fname}: {len(q_list)} questions")

print("\nAll done!")