#!/usr/bin/env python3
import json, sys

# Questions 1-10: Verben konjugieren
q1 = [
    {"id": "a1_01_q001", "subjectId": "a1_01", "type": "multiple_choice", "questionText": "Welche Form ist korrekt? \"Das Kind ___ sehr müde nach dem langen Tag.\"", "options": ["haben", "ist", "wird", "sind"], "correctAnswer": "ist", "explanation": "sein-Konjugation: Das Kind (3. Person Singular) → ist", "difficulty": "easy", "topicName": "Verben konjugieren (sein, haben, werden)"},
    {"id": "a1_01_q002", "subjectId": "a1_01", "type": "multiple_choice", "questionText": "Was passt in die Lücke? \"Wir ___ nächstes Jahr Lehrer.\"", "options": ["werden", "sind", "haben", "wird"], "correctAnswer": "werden", "explanation": "werden (werden → wir werden): Zukunft/Ausbildung", "difficulty": "easy", "topicName": "Verben konjugieren (sein, haben, werden)"},
    {"id": "a1_01_q003", "subjectId": "a1_01", "type": "multiple_choice", "questionText": "Welche Aussage ist grammatisch richtig?", "options": ["Er haben keine Zeit.", "Ihr seid sehr freundlich.", "Sie ist ein gute Idee.", "Wir wird fertig."], "correctAnswer": "Ihr seid sehr freundlich.", "explanation": "ihr → seid; korrekte Konjugation von sein", "difficulty": "easy", "topicName": "Verben konjugieren (sein, haben, werden)"},
    {"id": "a1_01_q004", "subjectId": "a1_01", "type": "multiple_choice", "questionText": "\"___ du schon Erfahrung mit diesem Job?\" – Was ist korrekt?", "options": ["Bist", "Wirst", "Hast", "Sein"], "correctAnswer": "Hast", "explanation": "haben (haben → du hast): Erfahrung haben", "difficulty": "easy", "topicName": "Verben konjugieren (sein, haben, werden)"},
    {"id": "a1_01_q005", "subjectId": "a1_01", "type": "multiple_choice", "questionText": "Wählen Sie die richtige Form: \"Die Schüler ___ sehr aufgeregt vor der Prüfung.\"", "options": ["ist", "hat", "sind", "war"], "correctAnswer": "sind", "explanation": "Die Schüler (Plural) → sind; aufgeregt sein", "difficulty": "easy", "topicName": "Verben konjugieren (sein, haben, werden)"},
    {"id": "a1_01_q006", "subjectId": "a1_01", "type": "multiple_choice", "questionText": "\"Er ___ Arzt, wenn er die Prüfung besteht.\" – Welches Verb fehlt?", "options": ["hat", "ist", "war", "wird"], "correctAnswer": "wird", "explanation": "werden: Er wird Arzt (Zukunft/Bedingung)", "difficulty": "easy", "topicName": "Verben konjugieren (sein, haben, werden)"},
    {"id": "a1_01_q007", "subjectId": "a1_01", "type": "multiple_choice", "questionText": "Welcher Satz ist FALSCH?", "options": ["Ich bin Student.", "Du hast Recht.", "Sie wird glücklich.", "Wir haben hungrig."], "correctAnswer": "Wir haben hungrig.", "explanation": "Man sagt: Wir sind hungrig (nicht: haben hungrig)", "difficulty": "medium", "topicName": "Verben konjugieren (sein, haben, werden)"},
    {"id": "a1_01_q008", "subjectId": "a1_01", "type": "multiple_choice", "questionText": "\"Ich ___ keine Ahnung, wo er ist.\" – Welche Form ist richtig?", "options": ["bin", "werde", "habe", "sei"], "correctAnswer": "habe", "explanation": "haben (haben → ich habe): keine Ahnung haben", "difficulty": "easy", "topicName": "Verben konjugieren (sein, haben, werden)"},
    {"id": "a1_01_q009", "subjectId": "a1_01", "type": "multiple_choice", "questionText": "\"___ ihr morgen in der Schule?\" – Ergänzen Sie das Verb.", "options": ["Haben", "Werden", "Seid", "Seiet"], "correctAnswer": "Seid", "explanation": "sein (sein → ihr seid): ihr in der Schule seid", "difficulty": "easy", "topicName": "Verben konjugieren (sein, haben, werden)"},
    {"id": "a1_01_q010", "subjectId": "a1_01", "type": "multiple_choice", "questionText": "\"Das Wetter ___ heute sehr schön.\" – Welche Form passt?", "options": ["haben", "ist", "sind", "werden"], "correctAnswer": "ist", "explanation": "sein (Das Wetter ist): Singular Subjekt → ist", "difficulty": "easy", "topicName": "Verben konjugieren (sein, haben, werden)"},
]

# Questions 11-20: Nomen und Artikel
q2 = [
    {"id": "a1_02_q001", "subjectId": "a1_02", "type": "multiple_choice", "questionText": "Welcher Artikel ist korrekt? \"___ Hund meiner Nachbarin ist sehr groß.\"", "options": ["Das", "Die", "Der", "Den"], "correctAnswer": "Der", "explanation": "Hund ist maskulin (der), im Nominativ", "difficulty": "easy", "topicName": "Nomen und Artikel (der/die/das + Pluralformen)"},
    {"id": "a1_02_q002", "subjectId": "a1_02", "type": "multiple_choice", "questionText": "Was ist die richtige Pluralform von \"das Kind\"?", "options": ["die Kinds", "die Kindes", "die Kinder", "die Kindere"], "correctAnswer": "die Kinder", "explanation": "das Kind → die Kinder (Umlaut + kein -e)", "difficulty": "easy", "topicName": "Nomen und Artikel (der/die/das + Pluralformen)"},
    {"id": "a1_02_q003", "subjectId": "a1_02", "type": "multiple_choice", "questionText": "Welcher Artikel gehört zu \"Fenster\"?", "options": ["der", "die", "das", "den"], "correctAnswer": "das", "explanation": "Fenster ist neutral (das)", "difficulty": "easy", "topicName": "Nomen und Artikel (der/die/das + Pluralformen)"},
    {"id": "a1_02_q004", "subjectId": "a1_02", "type": "multiple_choice", "questionText": "\"___ Äpfel sind frisch.\" – Welcher Artikel fehlt hier?", "options": ["Das", "Der", "Die", "Ein"], "correctAnswer": "Die", "explanation": "Äpfel ist Plural → die Äpfel (Nominativ)", "difficulty": "easy", "topicName": "Nomen und Artikel (der/die/das + Pluralformen)"},
    {"id": "a1_02_q005", "subjectId": "a1_02", "type": "multiple_choice", "questionText": "Welche Pluralform ist FALSCH?", "options": ["das Buch → die Bücher", "die Frau → die Frauen", "der Mann → die Männe", "das Haus → die Häuser"], "correctAnswer": "der Mann → die Männe", "explanation": "Richtig: der Mann → die Männer (Umlaut a→ä)", "difficulty": "medium", "topicName": "Nomen und Artikel (der/die/das + Pluralformen)"},
    {"id": "a1_02_q006", "subjectId": "a1_02", "type": "multiple_choice", "questionText": "\"___ Lehrerin erklärt ___ Aufgabe sehr gut.\" – Was fehlt?", "options": ["Der / das", "Die / die", "Das / der", "Die / der"], "correctAnswer": "Die / die", "explanation": "Lehrerin (feminin) → die; Aufgabe (feminin) → die", "difficulty": "medium", "topicName": "Nomen und Artikel (der/die/das + Pluralformen)"},
    {"id": "a1_02_q007", "subjectId": "a1_02", "type": "multiple_choice", "questionText": "Was ist der Plural von \"die Stadt\"?", "options": ["die Städte", "die Stadts", "die Städten", "die Stadten"], "correctAnswer": "die Städte", "explanation": "die Stadt → die Städte (Umlaut a→ä)", "difficulty": "easy", "topicName": "Nomen und Artikel (der/die/das + Pluralformen)"},
    {"id": "a1_02_q008", "subjectId": "a1_02", "type": "multiple_choice", "questionText": "Welcher Satz verwendet den Artikel richtig?", "options": ["Das Mann liest ein Buch.", "Der Auto ist neu.", "Die Katze schläft.", "Ein Hund ist bellen."], "correctAnswer": "Die Katze schläft.", "explanation": "Katze ist feminin → die Katze", "difficulty": "easy", "topicName": "Nomen und Artikel (der/die/das + Pluralformen)"},
    {"id": "a1_02_q009", "subjectId": "a1_02", "type": "multiple_choice", "questionText": "\"der Tisch\" – Welche Pluralform ist korrekt?", "options": ["die Tische", "die Tischer", "die Tischt", "die Tischen"], "correctAnswer": "die Tische", "explanation": "der Tisch → die Tische (kein Umlaut)", "difficulty": "easy", "topicName": "Nomen und Artikel (der/die/das + Pluralformen)"},
    {"id": "a1_02_q010", "subjectId": "a1_02", "type": "multiple_choice", "questionText": "\"Ich kaufe ___ Brot und ___ Äpfel.\" – Was fehlt?", "options": ["eine / der", "das / die", "ein / die", "der / das"], "correctAnswer": "das / die", "explanation": "Brot (neutral) → das; Äpfel (Plural) → die", "difficulty": "medium", "topicName": "Nomen und Artikel (der/die/das + Pluralformen)"},
]

# Questions 21-30: Präsens
q3 = [
    {"id": "a1_03_q001", "subjectId": "a1_03", "type": "multiple_choice", "questionText": "Wie lautet die richtige Form? \"Er ___ jeden Morgen früh auf.\"", "options": ["stehen", "stehe", "steht", "stehst"], "correctAnswer": "steht", "explanation": "aufstehen (Konjugation: er steigt auf → steht auf)", "difficulty": "easy", "topicName": "Präsens (Gegenwart)"},
    {"id": "a1_03_q002", "subjectId": "a1_03", "type": "multiple_choice", "questionText": "Welche Form ist korrekt? \"Ihr ___ sehr gut Deutsch.\"", "options": ["spricht", "sprecht", "sprechen", "sprechst"], "correctAnswer": "sprecht", "explanation": "sprechen (Konjugation: ihr sprecht)", "difficulty": "easy", "topicName": "Präsens (Gegenwart)"},
    {"id": "a1_03_q003", "subjectId": "a1_03", "type": "multiple_choice", "questionText": "\"Das Baby ___ die ganze Nacht.\" – Welches Verb passt? (schlafen)", "options": ["schlafen", "schläft", "schläfst", "schlaft"], "correctAnswer": "schläft", "explanation": "schlafen (Ablaut: er schläft)", "difficulty": "easy", "topicName": "Präsens (Gegenwart)"},
    {"id": "a1_03_q004", "subjectId": "a1_03", "type": "multiple_choice", "questionText": "Welcher Satz steht im Präsens und ist grammatisch richtig?", "options": ["Er geht gestern ins Kino.", "Wir trinkt Kaffee.", "Sie lernt fleißig.", "Du kommen spät."], "correctAnswer": "Sie lernt fleißig.", "explanation": "sie (3. Person Singular) → lernt", "difficulty": "easy", "topicName": "Präsens (Gegenwart)"},
    {"id": "a1_03_q005", "subjectId": "a1_03", "type": "multiple_choice", "questionText": "\"Ich ___ gerne Musik.\" – Ergänzen Sie das Verb \"hören\".", "options": ["hörst", "hört", "höre", "hören"], "correctAnswer": "höre", "explanation": "hören (Konjugation: ich höre)", "difficulty": "easy", "topicName": "Präsens (Gegenwart)"},
    {"id": "a1_03_q006", "subjectId": "a1_03", "type": "multiple_choice", "questionText": "Welche Form von \"fahren\" ist korrekt? \"Du ___ zu schnell.\"", "options": ["fährst", "fahrest", "fahrenst", "fährt"], "correctAnswer": "fährst", "explanation": "fahren (Ablaut: du fährst)", "difficulty": "easy", "topicName": "Präsens (Gegenwart)"},
    {"id": "a1_03_q007", "subjectId": "a1_03", "type": "multiple_choice", "questionText": "Welcher Satz ist FALSCH?", "options": ["Wir spielen Fußball.", "Sie tanzt gern.", "Er arbeitet heute.", "Ich lesen ein Buch."], "correctAnswer": "Ich lesen ein Buch.", "explanation": "Richtig: Ich lese ein Buch (lesen → ich lese)", "difficulty": "easy", "topicName": "Präsens (Gegenwart)"},
    {"id": "a1_03_q008", "subjectId": "a1_03", "type": "multiple_choice", "questionText": "\"Die Kinder ___ auf dem Spielplatz.\" – Was passt? (spielen)", "options": ["spielst", "spielen", "spielet", "spielt"], "correctAnswer": "spielen", "explanation": "Die Kinder (Plural) → spielen", "difficulty": "easy", "topicName": "Präsens (Gegenwart)"},
    {"id": "a1_03_q009", "subjectId": "a1_03", "type": "multiple_choice", "questionText": "Wie konjugiert man \"essen\" für \"er\"?", "options": ["esst", "isst", "esset", "essen"], "correctAnswer": "isst", "explanation": "essen (Ablaut: er isst)", "difficulty": "easy", "topicName": "Präsens (Gegenwart)"},
    {"id": "a1_03_q010", "subjectId": "a1_03", "type": "multiple_choice", "questionText": "\"Wir ___ morgen ins Museum.\" – Welches Verb fehlt? (gehen)", "options": ["geht", "gehst", "gehen", "gehet"], "correctAnswer": "gehen", "explanation": "wir → gehen", "difficulty": "easy", "topicName": "Präsens (Gegenwart)"},
]

# Questions 31-40: Akkusativ
q4 = [
    {"id": "a1_04_q001", "subjectId": "a1_04", "type": "multiple_choice", "questionText": "\"Ich sehe ___ Mann auf der Straße.\" – Welcher Artikel ist korrekt?", "options": ["der", "den", "dem", "des"], "correctAnswer": "den", "explanation": "Akkusativ maskulin: den Mann (nach 'sehen')", "difficulty": "easy", "topicName": "Akkusativ (Wen-Fall)"},
    {"id": "a1_04_q002", "subjectId": "a1_04", "type": "multiple_choice", "questionText": "Welches Pronomen steht im Akkusativ? \"Er besucht ___ jeden Sonntag.\"", "options": ["sie", "ihr", "ihre", "ihnen"], "correctAnswer": "sie", "explanation": "Akkusativ 3. Person Plural: sie (Akkusativ)", "difficulty": "medium", "topicName": "Akkusativ (Wen-Fall)"},
    {"id": "a1_04_q003", "subjectId": "a1_04", "type": "multiple_choice", "questionText": "Welcher Satz verwendet den Akkusativ richtig?", "options": ["Ich kaufe dem Buch.", "Er sieht der Film.", "Sie trinkt einen Tee.", "Wir besuchen dem Freund."], "correctAnswer": "Sie trinkt einen Tee.", "explanation": "einen Tee (Akkusativ) - trinken braucht Akkusativ", "difficulty": "easy", "topicName": "Akkusativ (Wen-Fall)"},
    {"id": "a1_04_q004", "subjectId": "a1_04", "type": "multiple_choice", "questionText": "\"Er liebt ___ Katze sehr.\" – Was fehlt?", "options": ["der", "die", "das", "den"], "correctAnswer": "die", "explanation": "Akkusativ feminin: die Katze (lieben braucht Akkusativ)", "difficulty": "easy", "topicName": "Akkusativ (Wen-Fall)"},
    {"id": "a1_04_q005", "subjectId": "a1_04", "type": "multiple_choice", "questionText": "Welches Wort steht im Akkusativ? \"Das Kind wirft ___ Ball.\"", "options": ["der", "dem", "des", "den"], "correctAnswer": "den", "explanation": "Ball (maskulin) im Akkusativ → den Ball", "difficulty": "easy", "topicName": "Akkusativ (Wen-Fall)"},
    {"id": "a1_04_q006", "subjectId": "a1_04", "type": "multiple_choice", "questionText": "\"Ich rufe ___ an.\" (mein Freund) – Welche Form ist korrekt?", "options": ["meinen Freund", "meinem Freund", "mein Freund", "meiner Freund"], "correctAnswer": "meinen Freund", "explanation": "Akkusativ: meinen Freund (anrufen braucht Akkusativ)", "difficulty": "medium", "topicName": "Akkusativ (Wen-Fall)"},
    {"id": "a1_04_q007", "subjectId": "a1_04", "type": "multiple_choice", "questionText": "Was fragt man im Akkusativ?", "options": ["Wem?", "Wessen?", "Wen / Was?", "Wo?"], "correctAnswer": "Wen / Was?", "explanation": "Akkusativ fragt man mit Wen? oder Was?", "difficulty": "easy", "topicName": "Akkusativ (Wen-Fall)"},
    {"id": "a1_04_q008", "subjectId": "a1_04", "type": "multiple_choice", "questionText": "\"Sie braucht ___ neuen Computer.\" – Was ist korrekt?", "options": ["einen", "einem", "einer", "ein"], "correctAnswer": "einen", "explanation": "Akkusativ maskulin: einen neuen Computer", "difficulty": "easy", "topicName": "Akkusativ (Wen-Fall)"},
    {"id": "a1_04_q009", "subjectId": "a1_04", "type": "multiple_choice", "questionText": "Welcher Satz ist FALSCH?", "options": ["Er kauft einen Apfel.", "Wir sehen den Film.", "Du rufst dem Arzt.", "Ich trinke einen Saft."], "correctAnswer": "Du rufst dem Arzt.", "explanation": "Richtig: Du rufst den Arzt (anrufen braucht Akkusativ)", "difficulty": "medium", "topicName": "Akkusativ (Wen-Fall)"},
    {"id": "a1_04_q010", "subjectId": "a1_04", "type": "multiple_choice", "questionText": "\"Er hat ___ Schwester besucht.\" – Was fehlt?", "options": ["seiner", "seine", "seinen", "seinem"], "correctAnswer": "seine", "explanation": "Akkusativ feminin: seine Schwester", "difficulty": "medium", "topicName": "Akkusativ (Wen-Fall)"},
]

# Questions 41-50: Dativ
q5 = [
    {"id": "a1_05_q001", "subjectId": "a1_05", "type": "multiple_choice", "questionText": "\"Ich gebe ___ Kind das Buch.\" – Welcher Artikel ist korrekt?", "options": ["den", "das", "dem", "die"], "correctAnswer": "dem", "explanation": "Dativ: dem Kind (geben braucht Dativ für Empfänger)", "difficulty": "easy", "topicName": "Dativ (Wem-Fall)"},
    {"id": "a1_05_q002", "subjectId": "a1_05", "type": "multiple_choice", "questionText": "Welches Pronomen steht im Dativ? \"Er hilft ___ Nachbarin oft.\"", "options": ["sie", "ihnen", "ihr", "ihre"], "correctAnswer": "ihr", "explanation": "Dativ 3. Person feminin: ihr (helfen braucht Dativ)", "difficulty": "medium", "topicName": "Dativ (Wem-Fall)"},
    {"id": "a1_05_q003", "subjectId": "a1_05", "type": "multiple_choice", "questionText": "\"Mit ___ fährst du in den Urlaub?\" – Was fehlt?", "options": ["wer", "wen", "wem", "wessen"], "correctAnswer": "wem", "explanation": "Mit wem? → Dativ Frage (mit + Dativ)", "difficulty": "easy", "topicName": "Dativ (Wem-Fall)"},
    {"id": "a1_05_q004", "subjectId": "a1_05", "type": "multiple_choice", "questionText": "Welcher Satz ist grammatisch korrekt?", "options": ["Er dankt seinem Vater.", "Sie hilft ihren Mutter.", "Ich schreibe meinem Freundin.", "Wir folgen den Chef."], "correctAnswer": "Er dankt seinem Vater.", "explanation": "danken + Dativ: seinem Vater", "difficulty": "medium", "topicName": "Dativ (Wem-Fall)"},
    {"id": "a1_05_q005", "subjectId": "a1_05", "type": "multiple_choice", "questionText": "\"Sie schenkt ___ Bruder ein Buch.\" – Was fehlt?", "options": ["ihren", "ihrem", "ihre", "ihrer"], "correctAnswer": "ihrem", "explanation": "Dativ maskulin: ihrem Bruder (schenken + Dativ)", "difficulty": "medium", "topicName": "Dativ (Wem-Fall)"},
    {"id": "a1_05_q006", "subjectId": "a1_05", "type": "multiple_choice", "questionText": "Welche Präposition steht immer mit dem Dativ?", "options": ["für", "durch", "mit", "ohne"], "correctAnswer": "mit", "explanation": "mit verlangt immer Dativ (mit dem Auto, mit ihr)", "difficulty": "easy", "topicName": "Dativ (Wem-Fall)"},
    {"id": "a1_05_q007", "subjectId": "a1_05", "type": "multiple_choice", "questionText": "\"Er wohnt bei ___ Eltern.\" – Was ist korrekt?", "options": ["sein", "seine", "seinen", "seinem"], "correctAnswer": "seinem", "explanation": "Dativ: bei seinem Eltern (Eltern ist Plural)", "difficulty": "medium", "topicName": "Dativ (Wem-Fall)"},
    {"id": "a1_05_q008", "subjectId": "a1_05", "type": "multiple_choice", "questionText": "Welche Form steht im Dativ Plural?", "options": ["die Kinder", "den Kindern", "der Kinder", "des Kindern"], "correctAnswer": "den Kindern", "explanation": "Dativ Plural: den Kindern (immer -n Endung)", "difficulty": "easy", "topicName": "Dativ (Wem-Fall)"},
    {"id": "a1_05_q009", "subjectId": "a1_05", "type": "multiple_choice", "questionText": "\"Das Buch gehört ___ Lehrerin.\" – Was fehlt?", "options": ["den", "der", "die", "dem"], "correctAnswer": "der", "explanation": "Dativ feminin: der Lehrerin (gehören braucht Dativ)", "difficulty": "easy", "topicName": "Dativ (Wem-Fall)"},
    {"id": "a1_05_q010", "subjectId": "a1_05", "type": "multiple_choice", "questionText": "\"Er hilft ___ alten Dame.\" – Welcher Artikel fehlt?", "options": ["die", "den", "der", "das"], "correctAnswer": "der", "explanation": "Dativ feminin: der alten Dame (helfen + Dativ)", "difficulty": "easy", "topicName": "Dativ (Wem-Fall)"},
]

# Questions 51-60: Präpositionen
q6 = [
    {"id": "a1_06_q001", "subjectId": "a1_06", "type": "multiple_choice", "questionText": "\"Das Buch liegt ___ dem Tisch.\" – Welche Präposition passt?", "options": ["in", "an", "auf", "nach"], "correctAnswer": "auf", "explanation": "auf dem Tisch (Oberfläche) → Aufenthaltsort", "difficulty": "easy", "topicName": "Präpositionen (in, auf, an, mit, nach...)"},
    {"id": "a1_06_q002", "subjectId": "a1_06", "type": "multiple_choice", "questionText": "\"Wir fahren ___ Berlin.\" – Welche Präposition ist korrekt?", "options": ["nach", "in", "an", "zu"], "correctAnswer": "nach", "explanation": "nach + Stadt/Land (ohne Artikel): nach Berlin", "difficulty": "easy", "topicName": "Präpositionen (in, auf, an, mit, nach...)"},
    {"id": "a1_06_q003", "subjectId": "a1_06", "type": "multiple_choice", "questionText": "\"Er wartet ___ der Bushaltestelle.\" – Was fehlt?", "options": ["auf", "an", "in", "bei"], "correctAnswer": "an", "explanation": "an der Bushaltestelle (Ortsangabe: an + Dativ)", "difficulty": "easy", "topicName": "Präpositionen (in, auf, an, mit, nach...)"},
    {"id": "a1_06_q004", "subjectId": "a1_06", "type": "multiple_choice", "questionText": "\"Sie fährt ___ dem Auto zur Arbeit.\" – Welche Präposition?", "options": ["in", "mit", "auf", "von"], "correctAnswer": "mit", "explanation": "mit dem Auto (Verkehrsmittel + Dativ)", "difficulty": "easy", "topicName": "Präpositionen (in, auf, an, mit, nach...)"},
    {"id": "a1_06_q005", "subjectId": "a1_06", "type": "multiple_choice", "questionText": "Welche Präposition verlangt den Dativ?", "options": ["für", "durch", "gegen", "aus"], "correctAnswer": "aus", "explanation": "aus verlangt Dativ (aus dem Haus, aus der Türkei)", "difficulty": "easy", "topicName": "Präpositionen (in, auf, an, mit, nach...)"},
    {"id": "a1_06_q006", "subjectId": "a1_06", "type": "multiple_choice", "questionText": "\"Das Bild hängt ___ der Wand.\" – Was ist richtig?", "options": ["auf", "an", "in", "unter"], "correctAnswer": "an", "explanation": "an der Wand (Vertikalfläche) → an + Dativ", "difficulty": "easy", "topicName": "Präpositionen (in, auf, an, mit, nach...)"},
    {"id": "a1_06_q007", "subjectId": "a1_06", "type": "multiple_choice", "questionText": "\"Ich gehe ___ Hause.\" – Welche Präposition passt?", "options": ["zu", "nach", "in", "an"], "correctAnswer": "nach", "explanation": "nach Hause (feststehend Ausdruck, kein Artikel)", "difficulty": "easy", "topicName": "Präpositionen (in, auf, an, mit, nach...)"},
    {"id": "a1_06_q008", "subjectId": "a1_06", "type": "multiple_choice", "questionText": "Welche Präposition steht vor Ländernamen ohne Artikel?", "options": ["in die", "nach", "zu", "an"], "correctAnswer": "nach", "explanation": "nach + Land (ohne Artikel): nach Deutschland", "difficulty": "easy", "topicName": "Präpositionen (in, auf, an, mit, nach...)"},
    {"id": "a1_06_q009", "subjectId": "a1_06", "type": "multiple_choice", "questionText": "\"Er kommt ___ der Türkei.\" – Welche Präposition?", "options": ["von", "aus", "nach", "bei"], "correctAnswer": "aus", "explanation": "aus der Türkei (Herkunft) → aus + Dativ", "difficulty": "easy", "topicName": "Präpositionen (in, auf, an, mit, nach...)"},
    {"id": "a1_06_q010", "subjectId": "a1_06", "type": "multiple_choice", "questionText": "\"Das Café ist ___ der Schule.\" – Was fehlt? (Lage, Wechselpräp.)", "options": ["in", "neben", "zu", "durch"], "correctAnswer": "neben", "explanation": "neben der Schule (Lage) → neben + Dativ", "difficulty": "medium", "topicName": "Präpositionen (in, auf, an, mit, nach...)"},
]

# Questions 61-70: Verben mit Präpositionen
q7 = [
    {"id": "a1_07_q001", "subjectId": "a1_07", "type": "multiple_choice", "questionText": "\"Ich warte ___ den Bus.\" – Welche Präposition gehört zu \"warten\"?", "options": ["für", "auf", "an", "von"], "correctAnswer": "auf", "explanation": "warten auf (+Akkusativ): Ich warte auf den Bus", "difficulty": "easy", "topicName": "Verben mit Präpositionen (warten auf, denken an...)"},
    {"id": "a1_07_q002", "subjectId": "a1_07", "type": "multiple_choice", "questionText": "\"Sie denkt oft ___ ihre Heimat.\" – Was fehlt?", "options": ["von", "auf", "an", "für"], "correctAnswer": "an", "explanation": "denken an (+Akkusativ): denkt an ihre Heimat", "difficulty": "easy", "topicName": "Verben mit Präpositionen (warten auf, denken an...)"},
    {"id": "a1_07_q003", "subjectId": "a1_07", "type": "multiple_choice", "questionText": "Welches Verb geht mit \"für\"?", "options": ["träumen", "sich interessieren", "sich bedanken", "warten"], "correctAnswer": "sich bedanken", "explanation": "sich bedanken für (+Akkusativ)", "difficulty": "medium", "topicName": "Verben mit Präpositionen (warten auf, denken an...)"},
    {"id": "a1_07_q004", "subjectId": "a1_07", "type": "multiple_choice", "questionText": "\"Er freut sich ___ das Wochenende.\" – Welche Präposition?", "options": ["an", "auf", "für", "über"], "correctAnswer": "auf", "explanation": "sich freuen auf (+Akkusativ): Vorfreude", "difficulty": "easy", "topicName": "Verben mit Präpositionen (warten auf, denken an...)"},
    {"id": "a1_07_q005", "subjectId": "a1_07", "type": "multiple_choice", "questionText": "\"Ich träume ___ einer langen Reise.\" – Was ist korrekt?", "options": ["von", "an", "über", "auf"], "correctAnswer": "von", "explanation": "träumen von (+Dativ): Ich träume von einer Reise", "difficulty": "easy", "topicName": "Verben mit Präpositionen (warten auf, denken an...)"},
    {"id": "a1_07_q006", "subjectId": "a1_07", "type": "multiple_choice", "questionText": "\"Sie ärgert sich ___ den Lärm.\" – Welche Präposition fehlt?", "options": ["an", "für", "über", "gegen"], "correctAnswer": "über", "explanation": "sich ärgern über (+Akkusativ): über den Lärm", "difficulty": "easy", "topicName": "Verben mit Präpositionen (warten auf, denken an...)"},
    {"id": "a1_07_q007", "subjectId": "a1_07", "type": "multiple_choice", "questionText": "\"Er spricht ___ seinem Problem.\" – Was ist korrekt?", "options": ["über", "mit", "von", "A und C"], "correctAnswer": "A und C", "explanation": "sprechen über / von seinem Problem (beide möglich)", "difficulty": "medium", "topicName": "Verben mit Präpositionen (warten auf, denken an...)"},
    {"id": "a1_07_q008", "subjectId": "a1_07", "type": "multiple_choice", "questionText": "\"Wir freuen uns ___ deinen Besuch.\" – Was fehlt?", "options": ["an", "über", "auf", "für"], "correctAnswer": "über", "explanation": "sich freuen über (+Akkusativ): aktuelle Freude", "difficulty": "easy", "topicName": "Verben mit Präpositionen (warten auf, denken an...)"},
    {"id": "a1_07_q009", "subjectId": "a1_07", "type": "multiple_choice", "questionText": "\"Sie leidet ___ Kopfschmerzen.\" – Welche Präposition?", "options": ["von", "gegen", "unter", "für"], "correctAnswer": "unter", "explanation": "leiden unter (+Dativ): unter Kopfschmerzen", "difficulty": "easy", "topicName": "Verben mit Präpositionen (warten auf, denken an...)"},
    {"id": "a1_07_q010", "subjectId": "a1_07", "type": "multiple_choice", "questionText": "\"Ich erinnere mich gern ___ meine Schulzeit.\" – Was passt?", "options": ["an", "von", "auf", "über"], "correctAnswer": "an", "explanation": "sich erinnern an (+Akkusativ)", "difficulty": "easy", "topicName": "Verben mit Präpositionen (warten auf, denken an...)"},
]

# Questions 71-80: Perfekt
q8 = [
    {"id": "a1_08_q001", "subjectId": "a1_08", "type": "multiple_choice", "questionText": "\"Er ___ gestern ins Kino ___.\" – Welche Form ist korrekt?", "options": ["hat / gehen", "ist / gegangen", "hat / gegangen", "ist / geht"], "correctAnswer": "ist / gegangen", "explanation": "gehen → Perfekt mit sein: ist gegangen", "difficulty": "easy", "topicName": "Perfekt (haben/sein + Partizip II)"},
    {"id": "a1_08_q002", "subjectId": "a1_08", "type": "multiple_choice", "questionText": "Welches Verb bildet das Perfekt mit \"sein\"?", "options": ["kaufen", "schlafen", "fahren", "essen"], "correctAnswer": "fahren", "explanation": "fahren → ist gefahren (Bewegung/Veränderung)", "difficulty": "easy", "topicName": "Perfekt (haben/sein + Partizip II)"},
    {"id": "a1_08_q003", "subjectId": "a1_08", "type": "multiple_choice", "questionText": "\"Wir ___ das Buch ___.\" (lesen) – Was fehlt?", "options": ["sind / gelesen", "haben / gelesen", "haben / geliest", "sind / gelest"], "correctAnswer": "haben / gelesen", "explanation": "lesen → Perfekt mit haben: haben gelesen", "difficulty": "easy", "topicName": "Perfekt (haben/sein + Partizip II)"},
    {"id": "a1_08_q004", "subjectId": "a1_08", "type": "multiple_choice", "questionText": "Welches Partizip II ist korrekt?", "options": ["gespringen", "getanzt", "geschwimmt", "gegebt"], "correctAnswer": "getanzt", "explanation": "tanzen → hat getanzt (regelmäßig → ge-tanzt)", "difficulty": "easy", "topicName": "Perfekt (haben/sein + Partizip II)"},
    {"id": "a1_08_q005", "subjectId": "a1_08", "type": "multiple_choice", "questionText": "\"Das Kind ___ sehr viel ___.\" (schlafen)", "options": ["hat / geschlafen", "ist / geschlafen", "hat / schlaft", "ist / schlafen"], "correctAnswer": "hat / geschlafen", "explanation": "schlafen → Perfekt mit haben: hat geschlafen", "difficulty": "easy", "topicName": "Perfekt (haben/sein + Partizip II)"},
    {"id": "a1_08_q006", "subjectId": "a1_08", "type": "multiple_choice", "questionText": "Welcher Satz im Perfekt ist FALSCH?", "options": ["Ich habe gegessen.", "Er ist gelaufen.", "Sie hat getrunken.", "Wir sind gekauft."], "correctAnswer": "Wir sind gekauft.", "explanation": "kaufen → Perfekt mit haben: Wir haben gekauft", "difficulty": "medium", "topicName": "Perfekt (haben/sein + Partizip II)"},
    {"id": "a1_08_q007", "subjectId": "a1_08", "type": "multiple_choice", "questionText": "\"Sie ___ nach Hause ___.\" (gehen)", "options": ["hat / gegangen", "ist / gegangen", "ist / geht", "hat / geht"], "correctAnswer": "ist / gegangen", "explanation": "gehen → ist gegangen (Richtungswechsel)", "difficulty": "easy", "topicName": "Perfekt (haben/sein + Partizip II)"},
    {"id": "a1_08_q008", "subjectId": "a1_08", "type": "multiple_choice", "questionText": "Was ist das Partizip II von \"schreiben\"?", "options": ["geschreibt", "geschrieben", "schrieb", "schreibt"], "correctAnswer": "geschrieben", "explanation": "schreiben → hat geschrieben (unregelmäßig)", "difficulty": "easy", "topicName": "Perfekt (haben/sein + Partizip II)"},
    {"id": "a1_08_q009", "subjectId": "a1_08", "type": "multiple_choice", "questionText": "\"Ich ___ das schon ___.\" (sehen)", "options": ["bin / gesehen", "habe / gesehen", "habe / gesieht", "bin / sieh"], "correctAnswer": "habe / gesehen", "explanation": "sehen → hat gesehen (unregelmäßig)", "difficulty": "easy", "topicName": "Perfekt (haben/sein + Partizip II)"},
    {"id": "a1_08_q010", "subjectId": "a1_08", "type": "multiple_choice", "questionText": "\"Er ___ früh ___.\" (aufstehen) – Perfekt?", "options": ["hat / aufgestanden", "ist / aufgestanden", "hat / aufstanden", "ist / aufsteht"], "correctAnswer": "ist / aufgestanden", "explanation": "aufstehen → ist aufgestanden (trennbar + sein)", "difficulty": "medium", "topicName": "Perfekt (haben/sein + Partizip II)"},
]

# Questions 81-90: Modalverben
q9 = [
    {"id": "a1_09_q001", "subjectId": "a1_09", "type": "multiple_choice", "questionText": "\"Er ___ morgen zum Arzt gehen.\" (Verpflichtung) – Welches Modalverb?", "options": ["darf", "will", "muss", "kann"], "correctAnswer": "muss", "explanation": "müssen = Verpflichtung/Notwendigkeit", "difficulty": "easy", "topicName": "Modalverben (können, müssen, wollen, dürfen, sollen)"},
    {"id": "a1_09_q002", "subjectId": "a1_09", "type": "multiple_choice", "questionText": "\"___ ich bitte das Fenster öffnen?\" (höfliche Bitte)", "options": ["Muss", "Darf", "Soll", "Will"], "correctAnswer": "Darf", "explanation": "Darf ich...? = höfliche Bitte um Erlaubnis", "difficulty": "easy", "topicName": "Modalverben (können, müssen, wollen, dürfen, sollen)"},
    {"id": "a1_09_q003", "subjectId": "a1_09", "type": "multiple_choice", "questionText": "Welcher Satz ist grammatisch korrekt?", "options": ["Er muss arbeiten heute.", "Sie will nicht kommen.", "Wir dürfen gehen nicht.", "Ich soll das kaufen morgen."], "correctAnswer": "Sie will nicht kommen.", "explanation": "Modalverb an Position 2, Infinktiv am Ende", "difficulty": "medium", "topicName": "Modalverben (können, müssen, wollen, dürfen, sollen)"},
    {"id": "a1_09_q004", "subjectId": "a1_09", "type": "multiple_choice", "questionText": "\"Die Kinder ___ hier nicht spielen.\" – Welches Modalverb?", "options": ["müssen", "wollen", "dürfen", "sollen"], "correctAnswer": "dürfen", "explanation": "dürfen = Erlaubnis/Verbot: dürfen nicht", "difficulty": "easy", "topicName": "Modalverben (können, müssen, wollen, dürfen, sollen)"},
    {"id": "a1_09_q005", "subjectId": "a1_09", "type": "multiple_choice", "questionText": "\"Ich ___ leider nicht kommen.\" (Unfähigkeit) – Was fehlt?", "options": ["will", "muss", "kann", "soll"], "correctAnswer": "kann", "explanation": "können = Fähigkeit/Unfähigkeit", "difficulty": "easy", "topicName": "Modalverben (können, müssen, wollen, dürfen, sollen)"},
    {"id": "a1_09_q006", "subjectId": "a1_09", "type": "multiple_choice", "questionText": "Welcher Satz drückt einen Wunsch aus?", "options": ["Er muss früh aufstehen.", "Sie will eine Reise machen.", "Du darfst nicht rauchen.", "Wir sollen pünktlich sein."], "correctAnswer": "Sie will eine Reise machen.", "explanation": "wollen = Wunsch/Begehren", "difficulty": "easy", "topicName": "Modalverben (können, müssen, wollen, dürfen, sollen)"},
    {"id": "a1_09_q007", "subjectId": "a1_09", "type": "multiple_choice", "questionText": "\"Du ___ deiner Mutter helfen.\" (Anweisung) – Was passt?", "options": ["kannst", "willst", "sollst", "musst"], "correctAnswer": "sollst", "explanation": "sollen = Aufforderung/Rat von außen", "difficulty": "easy", "topicName": "Modalverben (können, müssen, wollen, dürfen, sollen)"},
    {"id": "a1_09_q008", "subjectId": "a1_09", "type": "multiple_choice", "questionText": "Welcher Satz ist FALSCH?", "options": ["Wir können Deutsch sprechen.", "Er darf keinen Alkohol trinken.", "Sie muss die Aufgabe machen.", "Ich will nicht nach Hause gehen nicht."], "correctAnswer": "Ich will nicht nach Hause gehen nicht.", "explanation": "Doppel Verneinung: nicht + nicht = falsch", "difficulty": "medium", "topicName": "Modalverben (können, müssen, wollen, dürfen, sollen)"},
    {"id": "a1_09_q009", "subjectId": "a1_09", "type": "multiple_choice", "questionText": "\"___ du Klavier spielen?\" – Was ist die passende Frage?", "options": ["Musst", "Kannst", "Sollst", "Darfst"], "correctAnswer": "Kannst", "explanation": "können = Fähigkeit: Kannst du Klavier spielen?", "difficulty": "easy", "topicName": "Modalverben (können, müssen, wollen, dürfen, sollen)"},
    {"id": "a1_09_q010", "subjectId": "a1_09", "type": "multiple_choice", "questionText": "\"Er ___ laut sprechen.\" – Welches Modalverb passt bei einem Verbot?", "options": ["soll nicht", "darf nicht", "muss nicht", "kann nicht"], "correctAnswer": "darf nicht", "explanation": "dürfen nicht = Verbot (keine Erlaubnis)", "difficulty": "medium", "topicName": "Modalverben (können, müssen, wollen, dürfen, sollen)"},
]

# Questions 91-100: Sätze bilden
q10 = [
    {"id": "a1_10_q001", "subjectId": "a1_10", "type": "multiple_choice", "questionText": "Welche Wortstellung ist korrekt für einen deutschen Hauptsatz?", "options": ["Heute ich gehe ins Kino.", "Ins Kino heute gehe ich.", "Heute gehe ich ins Kino.", "Gehe ich heute ins Kino."], "correctAnswer": "Heute gehe ich ins Kino.", "explanation": "Position 1: Temporal (heute), Position 2: Verb, Position 3: Subjekt", "difficulty": "easy", "topicName": "Sätze bilden (Wortstellung)"},
    {"id": "a1_10_q002", "subjectId": "a1_10", "type": "multiple_choice", "questionText": "\"Er trinkt jeden Morgen Kaffee.\" – Welches Element steht auf Position 1?", "options": ["Kaffee", "jeden Morgen", "Er", "trinkt"], "correctAnswer": "jeden Morgen", "explanation": "Position 1 = Temporaladverbial: jeden Morgen", "difficulty": "easy", "topicName": "Sätze bilden (Wortstellung)"},
    {"id": "a1_10_q003", "subjectId": "a1_10", "type": "multiple_choice", "questionText": "Wo steht das Verb in einem deutschen Hauptsatz?", "options": ["Am Anfang", "Am Ende", "Immer auf Position 2", "Nach dem Objekt"], "correctAnswer": "Immer auf Position 2", "explanation": "Im Hauptsatz: konjugiertes Verb auf Position 2", "difficulty": "easy", "topicName": "Sätze bilden (Wortstellung)"},
    {"id": "a1_10_q004", "subjectId": "a1_10", "type": "multiple_choice", "questionText": "Welcher Satz ist FALSCH?", "options": ["Morgen kommt er.", "Er kommt morgen.", "Kommt er morgen.", "Er morgen kommt."], "correctAnswer": "Er morgen kommt.", "explanation": "Richtige Wortstellung: Er kommt morgen (Verb muss auf Pos. 2)", "difficulty": "easy", "topicName": "Sätze bilden (Wortstellung)"},
    {"id": "a1_10_q005", "subjectId": "a1_10", "type": "multiple_choice", "questionText": "\"Ich ___ gestern zum Supermarkt ___.\" – Richtige Perfektstellung?", "options": ["bin / gegangen", "bin gegangen / zum Supermarkt", "habe / gegangen", "habe gegangen / zum"], "correctAnswer": "bin / gegangen", "explanation": "Perfekt mit sein: ist gegangen; TEKAMOLO: Zeit, Grund, Modal, Ort", "difficulty": "medium", "topicName": "Sätze bilden (Wortstellung)"},
    {"id": "a1_10_q006", "subjectId": "a1_10", "type": "multiple_choice", "questionText": "In einem Nebensatz (weil) steht das Verb...", "options": ["auf Position 2", "am Ende", "am Anfang", "vor dem Subjekt"], "correctAnswer": "am Ende", "explanation": "In Nebensätzen: Verb am Ende (weil er geht, weil er ging)", "difficulty": "easy", "topicName": "Sätze bilden (Wortstellung)"},
    {"id": "a1_10_q007", "subjectId": "a1_10", "type": "multiple_choice", "questionText": "Welcher Satz mit \"weil\" ist korrekt?", "options": ["Ich bleibe zu Hause, weil es regnet.", "Ich bleibe zu Hause, weil regnet es.", "Weil regnet es, ich bleibe zu Hause.", "Ich bleibe, weil es zu Hause regnet."], "correctAnswer": "Ich bleibe zu Hause, weil es regnet.", "explanation": "weil-Satz: Verb am Ende; Subjekt vor Verb", "difficulty": "easy", "topicName": "Sätze bilden (Wortstellung)"},
    {"id": "a1_10_q008", "subjectId": "a1_10", "type": "multiple_choice", "questionText": "Wo steht das Modalverb im Hauptsatz?", "options": ["Am Ende", "Auf Position 1", "Auf Position 2", "Nach dem Infinitiv"], "correctAnswer": "Auf Position 2", "explanation": "Modalverb ersetzt konjugierte Verb auf Position 2", "difficulty": "easy", "topicName": "Sätze bilden (Wortstellung)"},
    {"id": "a1_10_q009", "subjectId": "a1_10", "type": "multiple_choice", "questionText": "\"Manchmal ___ er ___ Musik.\" – Richtige Wortstellung?", "options": ["hört / laut", "laut / hört", "hört er / laut Musik", "er / laut hört"], "correctAnswer": "hört / laut", "explanation": "Manchmal (Pos 1) + er (Pos 3) + hört (Pos 2) + laut (Angabe) + Musik", "difficulty": "medium", "topicName": "Sätze bilden (Wortstellung)"},
    {"id": "a1_10_q010", "subjectId": "a1_10", "type": "multiple_choice", "questionText": "Welcher Satz ist grammatisch korrekt?", "options": ["Er hat gestern das Buch gelesen.", "Er gestern hat gelesen das Buch.", "Gestern er hat das Buch gelesen.", "Das Buch hat gelesen er gestern."], "correctAnswer": "Er hat gestern das Buch gelesen.", "explanation": "Richtige Stellung: Subjekt + Hilfsverb + Temporal + Objekt + Partizip", "difficulty": "easy", "topicName": "Sätze bilden (Wortstellung)"},
]

topics = [
    ("a1_01", "1. Verben konjugieren (sein, haben, werden)", q1),
    ("a1_02", "2. Nomen und Artikel (der/die/das + Pluralformen)", q2),
    ("a1_03", "3. Präsens (Gegenwart)", q3),
    ("a1_04", "4. Akkusativ (Wen-Fall)", q4),
    ("a1_05", "5. Dativ (Wem-Fall)", q5),
    ("a1_06", "6. Präpositionen (in, auf, an, mit, nach...)", q6),
    ("a1_07", "7. Verben mit Präpositionen (warten auf, denken an...)", q7),
    ("a1_08", "8. Perfekt (haben/sein + Partizip II)", q8),
    ("a1_09", "9. Modalverben (können, müssen, wollen, dürfen, sollen)", q9),
    ("a1_10", "10. Sätze bilden (Wortstellung)", q10),
]

base = "app/src/main/assets/"
for file_id, topic_name, questions in topics:
    filepath = base + file_id + ".json"
    data = {
        "version": "1.0",
        "subjectId": file_id,
        "topicName": topic_name,
        "totalQuestions": len(questions),
        "questions": questions
    }
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"Written: {filepath} ({len(questions)} questions)")

print("\nAll done!")