#!/usr/bin/env python3
"""
Generate updated b2_questions.json for merged Topic 1 (Konnektoren).
Replaces old b2_01 and b2_02 with merged content from b2_konnektoren_questions.md.
"""

import json

# Our curated 96 questions from b2_konnektoren_questions.md
curated_qs = [
    # ALS (12)
    {"id": "b2_01_q001", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ ich in Deutschland ankam, konnte ich kein Deutsch.", "options": ["Wenn", "Als", "Während", "Bevor"], "correctAnswer": "Als", "explanation": '"Als" wird für einmalige Situationen in der Vergangenheit verwendet. Beispiel: Als ich in Deutschland ankam, sprach ich kein Deutsch.', "difficulty": "easy"},
    {"id": "b2_01_q002", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ ich gestern nach Hause kam, hat es geregnet.", "options": ["Bevor", "Als", "Bis", "Während"], "correctAnswer": "Als", "explanation": '"Als" wird für einmalige vergangene Handlungen verwendet.', "difficulty": "easy"},
    {"id": "b2_01_q003", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ ich ein Kind war, habe ich in Istanbul gelebt.", "options": ["Wenn", "Während", "Als", "Seitdem"], "correctAnswer": "Als", "explanation": '"Als" beschreibt eine einmalige Situation in der Kindheit.', "difficulty": "medium"},
    {"id": "b2_01_q004", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ ich die Nachricht gelesen habe, war ich sehr überrascht.", "options": ["Während", "Als", "Bevor", "Sobald"], "correctAnswer": "Als", "explanation": '"Als" zeigt eine abgeschlossene Handlung in der Vergangenheit.', "difficulty": "medium"},
    {"id": "b2_01_q005", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ er 2019 nach Deutschland kam, sprach er nur Türkisch.", "options": ["Seitdem", "Als", "Wenn", "Während"], "correctAnswer": "Als", "explanation": '"Als" wird für einmalige vergangene Ereignisse mit Jahreszahlen verwendet.', "difficulty": "medium"},
    {"id": "b2_01_q006", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ ich mich umgedreht habe, war niemand mehr da.", "options": ["Sobald", "Als", "Bis", "Solange"], "correctAnswer": "Als", "explanation": '"Als" beschreibt eine plötzliche, einmalige Handlung in der Vergangenheit.', "difficulty": "easy"},
    {"id": "b2_01_q007", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ wir in München ankamen, hat es geschneit.", "options": ["Während", "Als", "Bevor", "Wenn"], "correctAnswer": "Als", "explanation": '"Als" wird bei der Ankunft an einem Ort verwendet.', "difficulty": "easy"},
    {"id": "b2_01_q008", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ ich jünger war, habe ich viel Fußball gespielt.", "options": ["Wenn", "Als", "Seitdem", "Während"], "correctAnswer": "Als", "explanation": '"Als" beschreibt eine Lebensphase in der Vergangenheit.', "difficulty": "easy"},
    {"id": "b2_01_q009", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ ich die Tür geöffnet habe, sah ich meinen alten Freund.", "options": ["Bevor", "Als", "Bis", "Sobald"], "correctAnswer": "Als", "explanation": '"Als" zeigt eine plötzliche Begegnung in der Vergangenheit.', "difficulty": "medium"},
    {"id": "b2_01_q010", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ sie ihren Abschluss gemacht hatte, begann sie zu arbeiten.", "options": ["Als", "Während", "Wenn", "Solange"], "correctAnswer": "Als", "explanation": '"Als" zeigt eine Abfolge von zwei vergangenen Handlungen.', "difficulty": "medium"},
    {"id": "b2_01_q011", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ ich zum ersten Mal in Berlin war, habe ich das Brandenburger Tor besucht.", "options": ["Während", "Als", "Bevor", "Wenn"], "correctAnswer": "Als", "explanation": '"Als" wird für die erste Erfahrung an einem Ort verwendet.', "difficulty": "easy"},
    {"id": "b2_01_q012", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ wir das Angebot erhalten haben, haben wir sofort geantwortet.", "options": ["Als", "Sobald", "Während", "Wenn"], "correctAnswer": "Als", "explanation": '"Als" zeigt eine schnelle Reaktion auf ein vergangenes Ereignis.', "difficulty": "hard"},
    # BEVOR (12)
    {"id": "b2_01_q013", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "Ich lerne Deutsch, ___ ich nach Deutschland gehe.", "options": ["Als", "Während", "Bevor", "Wenn"], "correctAnswer": "Bevor", "explanation": '"Bevor" bedeutet "önce" auf Türkisch. Die Handlung danach ist der Hauptpunkt.', "difficulty": "easy"},
    {"id": "b2_01_q014", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ du gehst, mache bitte die Tür zu.", "options": ["Als", "Bevor", "Während", "Bis"], "correctAnswer": "Bevor", "explanation": '"Bevor" zeigt die Handlung, die zuerst kommt.', "difficulty": "easy"},
    {"id": "b2_01_q015", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "Er ruft an, ___ er zu uns kommt.", "options": ["Während", "Bevor", "Sobald", "Als"], "correctAnswer": "Bevor", "explanation": '"Bevor" bedeutet, dass die Handlung im Nebensatz zuerst kommt.', "difficulty": "easy"},
    {"id": "b2_01_q016", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ du ins Bett gehst, solltest du die Zähne putzen.", "options": ["Während", "Bevor", "Nachdem", "Als"], "correctAnswer": "Bevor", "explanation": '"Bevor" zeigt eine Routine-Handlung vor dem Schlafen.', "difficulty": "easy"},
    {"id": "b2_01_q017", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "Sie hat alles vorbereitet, ___ die Gäste ankamen.", "options": ["Bevor", "Während", "Als", "Wenn"], "correctAnswer": "Bevor", "explanation": '"Bevor" zeigt, dass die Vorbereitung vor dem Eintreffen der Gäste geschah.', "difficulty": "medium"},
    {"id": "b2_01_q018", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ du etwas kaufst, vergleiche bitte die Preise.", "options": ["Während", "Bevor", "Nachdem", "Sobald"], "correctAnswer": "Bevor", "explanation": '"Bevor" gibt einen Rat vor dem Einkauf.', "difficulty": "easy"},
    {"id": "b2_01_q019", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "Ich möchte mit dir sprechen, ___ du gehst.", "options": ["Als", "Bevor", "Während", "Wenn"], "correctAnswer": "Bevor", "explanation": '"Bevor" zeigt die Dringlichkeit des Gesprächs vor dem Gehen.', "difficulty": "easy"},
    {"id": "b2_01_q020", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ du das Auto fährst, schnalle dich bitte an.", "options": ["Während", "Bevor", "Nachdem", "Als"], "correctAnswer": "Bevor", "explanation": '"Bevor" gibt eine Sicherheitsanweisung vor dem Fahren.', "difficulty": "easy"},
    {"id": "b2_01_q021", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "Er hat lange gearbeitet, ___ er Urlaub gemacht hat.", "options": ["Während", "Bevor", "Nachdem", "Als"], "correctAnswer": "Bevor", "explanation": '"Bevor" zeigt die Reihenfolge: Arbeit kam vor dem Urlaub.', "difficulty": "medium"},
    {"id": "b2_01_q022", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ du eine E-Mail schreibst, prüfe bitte die Rechtschreibung.", "options": ["Während", "Bevor", "Sobald", "Wenn"], "correctAnswer": "Bevor", "explanation": '"Bevor" gibt einen Tipp vor dem Schreiben.', "difficulty": "easy"},
    {"id": "b2_01_q023", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "Wir müssen das Formular ausfüllen, ___ wir einreisen dürfen.", "options": ["Während", "Bevor", "Nachdem", "Während"], "correctAnswer": "Bevor", "explanation": '"Bevor" zeigt die Voraussetzung für die Einreise.', "difficulty": "medium"},
    {"id": "b2_01_q024", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ du das Essen zubereitest, wasche dir bitte die Hände.", "options": ["Sobald", "Bevor", "Während", "Wenn"], "correctAnswer": "Bevor", "explanation": '"Bevor" gibt eine Hygieneanweisung vor dem Kochen.', "difficulty": "easy"},
    # BIS (12)
    {"id": "b2_01_q025", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "Ich warte hier, ___ du fertig bist.", "options": ["Während", "Bis", "Bevor", "Sobald"], "correctAnswer": "Bis", "explanation": '"Bis" zeigt den Endpunkt einer Handlung. Man wartet bis etwas passiert.', "difficulty": "easy"},
    {"id": "b2_01_q026", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "Er blieb im Büro, ___ sein Chef kam.", "options": ["Während", "Bis", "Bevor", "Als"], "correctAnswer": "Bis", "explanation": '"Bis" zeigt die Zeitgrenze — er blieb bis zur Ankunft des Chefs.', "difficulty": "easy"},
    {"id": "b2_01_q027", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ ich Zeit habe, kann ich dir helfen.", "options": ["Während", "Bis", "Bevor", "Sobald"], "correctAnswer": "Bis", "explanation": '"Bis" zeigt hier die Bedingung — bis ich Zeit habe.', "difficulty": "medium"},
    {"id": "b2_01_q028", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "Sie las das Buch, ___ sie eingeschlafen ist.", "options": ["Während", "Bis", "Bevor", "Wenn"], "correctAnswer": "Bis", "explanation": '"Bis" zeigt den Endpunkt — sie las bis zum Einschlafen.', "difficulty": "easy"},
    {"id": "b2_01_q029", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ der Arzt kommt, musst du im Bett bleiben.", "options": ["Während", "Bis", "Bevor", "Sobald"], "correctAnswer": "Bis", "explanation": '"Bis" zeigt die Anweisung bis zum Eintreffen des Arztes.', "difficulty": "easy"},
    {"id": "b2_01_q030", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "Wir haben gewartet, ___ der Zug angekommen ist.", "options": ["Während", "Bis", "Bevor", "Sobald"], "correctAnswer": "Bis", "explanation": '"Bis" zeigt die Zeitgrenze des Wartens.', "difficulty": "easy"},
    {"id": "b2_01_q031", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "Er sprach nicht, ___ er die Wahrheit erfahren hatte.", "options": ["Während", "Bis", "Bevor", "Nachdem"], "correctAnswer": "Bis", "explanation": '"Bis" zeigt den Zeitpunkt, ab dem er sprach — als er die Wahrheit erfuhr.', "difficulty": "medium"},
    {"id": "b2_01_q032", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ alle Gäste gegangen waren, haben wir aufgeräumt.", "options": ["Während", "Bis", "Bevor", "Sobald"], "correctAnswer": "Bis", "explanation": '"Bis" zeigt den Endpunkt — aufgeräumt wurde nach dem Gehen der Gäste.', "difficulty": "medium"},
    {"id": "b2_01_q033", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "Ich werde warten, ___ du zurückkommst.", "options": ["Während", "Bis", "Bevor", "Sobald"], "correctAnswer": "Bis", "explanation": '"Bis" zeigt den Endpunkt des Wartens.', "difficulty": "easy"},
    {"id": "b2_01_q034", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ das Spiel zu Ende war, haben wir geklatscht.", "options": ["Während", "Bis", "Bevor", "Wenn"], "correctAnswer": "Bis", "explanation": '"Bis" zeigt den Zeitpunkt des Klatschens — als das Spiel endete.', "difficulty": "medium"},
    {"id": "b2_01_q035", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "Das Kind blieb ruhig, ___ seine Mutter kam.", "options": ["Während", "Bis", "Bevor", "Sobald"], "correctAnswer": "Bis", "explanation": '"Bis" zeigt den Zeitpunkt der Veränderung — als die Mutter kam.', "difficulty": "easy"},
    {"id": "b2_01_q036", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ der Film begann, haben wir Popcorn gekauft.", "options": ["Während", "Bis", "Bevor", "Nachdem"], "correctAnswer": "Bis", "explanation": '"Bis" zeigt die Zeit vor dem Beginn — wir kauften Popcorn davor.', "difficulty": "medium"},
    # SEITDEM (12)
    {"id": "b2_01_q037", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ ich in Berlin wohne, fühle ich mich sehr wohl.", "options": ["Als", "Während", "Seitdem", "Bevor"], "correctAnswer": "Seitdem", "explanation": '"Seitdem" zeigt eine Handlung, die in der Vergangenheit begann und immer noch andauert.', "difficulty": "easy"},
    {"id": "b2_01_q038", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ er mit dem Rauchen aufgehört hat, fühlt er sich besser.", "options": ["Bevor", "Seitdem", "Wenn", "Während"], "correctAnswer": "Seitdem", "explanation": '"Seitdem" zeigt die Veränderung nach dem Aufhören einer Gewohnheit.', "difficulty": "easy"},
    {"id": "b2_01_q039", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ sie in Deutschland lebt, spricht sie fließend Deutsch.", "options": ["Während", "Seitdem", "Bevor", "Als"], "correctAnswer": "Seitdem", "explanation": '"Seitdem" zeigt die kontinuierliche Verbesserung seit einem Zeitpunkt.', "difficulty": "easy"},
    {"id": "b2_01_q040", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ ich mit dem Kurs angefangen habe, gehe ich jeden Tag zur Schule.", "options": ["Als", "Seitdem", "Während", "Bevor"], "correctAnswer": "Seitdem", "explanation": '"Seitdem" zeigt die neue Routine seit dem Start des Kurses.', "difficulty": "easy"},
    {"id": "b2_01_q041", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "Er ist nicht mehr nervös, ___ er regelmäßig meditiert.", "options": ["Während", "Seitdem", "Bevor", "Wenn"], "correctAnswer": "Seitdem", "explanation": '"Seitdem" zeigt die positive Veränderung nach einer Gewohnheit.', "difficulty": "medium"},
    {"id": "b2_01_q042", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ wir umgezogen sind, kennen wir viele neue Leute.", "options": ["Während", "Seitdem", "Bevor", "Als"], "correctAnswer": "Seitdem", "explanation": '"Seitdem" zeigt die Veränderung im sozialen Leben nach dem Umzug.', "difficulty": "easy"},
    {"id": "b2_01_q043", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ du mir geholfen hast, ist alles viel einfacher geworden.", "options": ["Während", "Seitdem", "Bevor", "Als"], "correctAnswer": "Seitdem", "explanation": '"Seitdem" zeigt die Verbesserung nach der Hilfe.', "difficulty": "easy"},
    {"id": "b2_01_q044", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ sie eine neue Stelle gefunden hat, ist sie viel glücklicher.", "options": ["Bevor", "Seitdem", "Während", "Wenn"], "correctAnswer": "Seitdem", "explanation": '"Seitdem" zeigt die emotionale Veränderung nach dem Jobwechsel.', "difficulty": "easy"},
    {"id": "b2_01_q045", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ ich 2023 umgezogen bin, wohne ich in einer größeren Wohnung.", "options": ["Während", "Seitdem", "Bevor", "Wenn"], "correctAnswer": "Seitdem", "explanation": '"Seitdem" zeigt die andauernde Situation nach dem Umzug.', "difficulty": "easy"},
    {"id": "b2_01_q046", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ er in Hamburg wohnt, arbeitet er bei einer großen Firma.", "options": ["Während", "Seitdem", "Bevor", "Als"], "correctAnswer": "Seitdem", "explanation": '"Seitdem" zeigt die Verknüpfung zweier andauernder Situationen.', "difficulty": "medium"},
    {"id": "b2_01_q047", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "Ich bin nicht mehr müde, ___ ich früher ins Bett gehe.", "options": ["Während", "Seitdem", "Bevor", "Wenn"], "correctAnswer": "Seitdem", "explanation": '"Seitdem" zeigt die positive Veränderung nach einer Gewohnheitsänderung.', "difficulty": "easy"},
    {"id": "b2_01_q048", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ wir uns kennengelernt haben, schreiben wir uns fast jeden Tag.", "options": ["Während", "Seitdem", "Bevor", "Als"], "correctAnswer": "Seitdem", "explanation": '"Seitdem" zeigt die andauernde Gewohnheit seit dem Kennenlernen.', "difficulty": "easy"},
    # WÄHREND (12)
    {"id": "b2_01_q049", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ sie kocht, hört sie Musik.", "options": ["Bevor", "Während", "Nachdem", "Bis"], "correctAnswer": "Während", "explanation": '"Während" zeigt zwei Handlungen, die gleichzeitig passieren.', "difficulty": "easy"},
    {"id": "b2_01_q050", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ er im Büro war, hat seine Frau angerufen.", "options": ["Bevor", "Während", "Nachdem", "Wenn"], "correctAnswer": "Während", "explanation": '"Während" zeigt eine Handlung, die während einer anderen passiert.', "difficulty": "easy"},
    {"id": "b2_01_q051", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "Ich habe gelernt, ___ mein Bruder ferngesehen hat.", "options": ["Bevor", "Während", "Nachdem", "Sobald"], "correctAnswer": "Während", "explanation": '"Während" zeigt parallele Handlungen zweier Personen.', "difficulty": "easy"},
    {"id": "b2_01_q052", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ sie auf den Bus gewartet hat, hat sie ein Buch gelesen.", "options": ["Bevor", "Während", "Nachdem", "Als"], "correctAnswer": "Während", "explanation": '"Während" zeigt zwei simultane Handlungen beim Warten.', "difficulty": "easy"},
    {"id": "b2_01_q053", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ ich in der Küche stand, habe ich das Fenster aufgemacht.", "options": ["Bevor", "Während", "Nachdem", "Sobald"], "correctAnswer": "Während", "explanation": '"Während" zeigt eine Handlung, die während einer anderen Situation geschah.', "difficulty": "medium"},
    {"id": "b2_01_q054", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "Er hat Kaffee getrunken, ___ er die Zeitung gelesen hat.", "options": ["Bevor", "Während", "Nachdem", "Wenn"], "correctAnswer": "Während", "explanation": '"Während" zeigt zwei entspannende Handlungen gleichzeitig.', "difficulty": "easy"},
    {"id": "b2_01_q055", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ mein Mann kocht, räume ich die Wohnung auf.", "options": ["Bevor", "Während", "Nachdem", "Als"], "correctAnswer": "Während", "explanation": '"Während" zeigt zwei verschiedene Personen bei gleichzeitigen Haushaltsaufgaben.', "difficulty": "easy"},
    {"id": "b2_01_q056", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "Das Kind hat geweint, ___ die Mutter es gewickelt hat.", "options": ["Bevor", "Während", "Nachdem", "Bis"], "correctAnswer": "Während", "explanation": '"Während" zeigt die Gleichzeitigkeit von Unruhe und Pflege.', "difficulty": "easy"},
    {"id": "b2_01_q057", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ sie im Krankenhaus lag, hat sie viele Bücher gelesen.", "options": ["Bevor", "Während", "Nachdem", "Sobald"], "correctAnswer": "Während", "explanation": '"Während" zeigt eine Handlung während eines Krankenhausaufenthalts.', "difficulty": "easy"},
    {"id": "b2_01_q058", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "Ich habe mir Notizen gemacht, ___ der Professor gesprochen hat.", "options": ["Bevor", "Während", "Nachdem", "Wenn"], "correctAnswer": "Während", "explanation": '"Während" zeigt konzentriertes Zuhören und gleichzeitiges Schreiben.', "difficulty": "medium"},
    {"id": "b2_01_q059", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ die Sonne unterging, saßen wir auf der Terrasse.", "options": ["Bevor", "Während", "Nachdem", "Als"], "correctAnswer": "Während", "explanation": '"Während" zeigt eine Handlung, die während eines Naturereignisses geschieht.', "difficulty": "easy"},
    {"id": "b2_01_q060", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ du mit dem Hund gehst, nimm bitte eine Leine mit.", "options": ["Bevor", "Während", "Nachdem", "Sobald"], "correctAnswer": "Während", "explanation": '"Während" zeigt die Begleithandlung beim Gassigehen.', "difficulty": "easy"},
    # WENN (12)
    {"id": "b2_01_q061", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ es regnet, bleibe ich zu Hause.", "options": ["Als", "Während", "Wenn", "Bevor"], "correctAnswer": "Wenn", "explanation": '"Wenn" wird für wiederholte oder zukünftige Situationen verwendet.', "difficulty": "easy"},
    {"id": "b2_01_q062", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ du Zeit hast, besuch mich bitte.", "options": ["Als", "Während", "Wenn", "Bevor"], "correctAnswer": "Wenn", "explanation": '"Wenn" drückt eine Einladung bei einer Bedingung aus.', "difficulty": "easy"},
    {"id": "b2_01_q063", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "Immer, ___ ich Stress habe, gehe ich spazieren.", "options": ["Als", "Während", "Wenn", "Bevor"], "correctAnswer": "Wenn", "explanation": '"Wenn" mit "Immer" zeigt eine wiederholte Reaktion auf eine Situation.', "difficulty": "easy"},
    {"id": "b2_01_q064", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ man in Deutschland arbeitet, muss man Steuern zahlen.", "options": ["Als", "Während", "Wenn", "Bevor"], "correctAnswer": "Wenn", "explanation": '"Wenn" drückt eine allgemeine Wahrheit oder Regel aus.', "difficulty": "medium"},
    {"id": "b2_01_q065", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "Jedes Mal, ___ ich nach Deutschland reise, besuche ich meine Freunde.", "options": ["Als", "Wenn", "Während", "Bevor"], "correctAnswer": "Wenn", "explanation": '"Wenn" mit "Jedes Mal" zeigt eine regelmäßige Gewohnheit bei Reisen.', "difficulty": "easy"},
    {"id": "b2_01_q066", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ du mich brauchst, bin ich für dich da.", "options": ["Als", "Wenn", "Während", "Bevor"], "correctAnswer": "Wenn", "explanation": '"Wenn" drückt ein Versprechen bei einer Bedingung aus.', "difficulty": "easy"},
    {"id": "b2_01_q067", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ du Fleisch kochst, achte auf die Temperatur.", "options": ["Als", "Wenn", "Während", "Bevor"], "correctAnswer": "Wenn", "explanation": '"Wenn" gibt eine Anweisung bei einer bestimmten Tätigkeit.', "difficulty": "easy"},
    {"id": "b2_01_q068", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ die Schule aus ist, gehen die Kinder nach Hause.", "options": ["Als", "Wenn", "Während", "Bevor"], "correctAnswer": "Wenn", "explanation": '"Wenn" zeigt eine regelmäßige Situation nach einem Ereignis.', "difficulty": "easy"},
    {"id": "b2_01_q069", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "Immer ___ ich diesen Song höre, denke ich an dich.", "options": ["Als", "Wenn", "Während", "Bevor"], "correctAnswer": "Wenn", "explanation": '"Wenn" zeigt eine emotionale Reaktion, die sich wiederholt.', "difficulty": "easy"},
    {"id": "b2_01_q070", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ der Frühling kommt, werden die Tage länger.", "options": ["Als", "Wenn", "Während", "Bevor"], "correctAnswer": "Wenn", "explanation": '"Wenn" zeigt eine jährlich wiederkehrende Veränderung.', "difficulty": "easy"},
    {"id": "b2_01_q071", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ man krank ist, sollte man zum Arzt gehen.", "options": ["Als", "Wenn", "Während", "Bevor"], "correctAnswer": "Wenn", "explanation": '"Wenn" drückt eine allgemeine Empfehlung bei einer Bedingung aus.', "difficulty": "easy"},
    {"id": "b2_01_q072", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ du morgen frei hast, können wir etwas unternehmen.", "options": ["Als", "Wenn", "Während", "Bevor"], "correctAnswer": "Wenn", "explanation": '"Wenn" drückt eine Möglichkeit bei einer zukünftigen Bedingung aus.', "difficulty": "easy"},
    # SOBALD (12)
    {"id": "b2_01_q073", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ ich ankomme, rufe ich dich an.", "options": ["Während", "Bevor", "Sobald", "Als"], "correctAnswer": "Sobald", "explanation": '"Sobald" bedeutet "as soon as" — unmittelbare Abfolge zweier Handlungen.', "difficulty": "easy"},
    {"id": "b2_01_q074", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ er die Wahrheit erfahren hatte, wurde er wütend.", "options": ["Während", "Bevor", "Sobald", "Wenn"], "correctAnswer": "Sobald", "explanation": '"Sobald" zeigt die unmittelbare emotionale Reaktion auf eine Information.', "difficulty": "medium"},
    {"id": "b2_01_q075", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ die Prüfung vorbei ist, machen wir eine Party.", "options": ["Während", "Bevor", "Sobald", "Als"], "correctAnswer": "Sobald", "explanation": '"Sobald" zeigt die Feier, die unmittelbar nach der Prüfung beginnt.', "difficulty": "easy"},
    {"id": "b2_01_q076", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ du fertig bist, können wir essen gehen.", "options": ["Während", "Bevor", "Sobald", "Wenn"], "correctAnswer": "Sobald", "explanation": '"Sobald" zeigt die Einladung, die vom Fertigwerden abhängt.', "difficulty": "easy"},
    {"id": "b2_01_q077", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ die Ampel grün wird, fahren wir weiter.", "options": ["Während", "Bevor", "Sobald", "Als"], "correctAnswer": "Sobald", "explanation": '"Sobald" zeigt die unmittelbare Reaktion auf ein Signal.', "difficulty": "easy"},
    {"id": "b2_01_q078", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ er die Nachricht gelesen hat, antwortete er sofort.", "options": ["Während", "Bevor", "Sobald", "Wenn"], "correctAnswer": "Sobald", "explanation": '"Sobald" zeigt die schnelle Reaktion auf eine Nachricht.', "difficulty": "easy"},
    {"id": "b2_01_q079", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ es aufhört zu regnen, gehen wir nach draußen.", "options": ["Während", "Bevor", "Sobald", "Als"], "correctAnswer": "Sobald", "explanation": '"Sobald" zeigt die Handlung, die nach dem Ende einer anderen beginnt.', "difficulty": "easy"},
    {"id": "b2_01_q080", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ ich bezahlt werde, kaufe ich mir ein neues Handy.", "options": ["Während", "Bevor", "Sobald", "Wenn"], "correctAnswer": "Sobald", "explanation": '"Sobald" zeigt die unmittelbare Handlung nach dem Erhalt des Geldes.', "difficulty": "medium"},
    {"id": "b2_01_q081", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ das Licht anging, konnte ich alles sehen.", "options": ["Während", "Bevor", "Sobald", "Als"], "correctAnswer": "Sobald", "explanation": '"Sobald" zeigt die unmittelbare Folge einer Handlung.', "difficulty": "easy"},
    {"id": "b2_01_q082", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ du das liest, wirst du verstehen.", "options": ["Während", "Bevor", "Sobald", "Wenn"], "correctAnswer": "Sobald", "explanation": '"Sobald" zeigt die unmittelbare Erkenntnis nach dem Lesen.', "difficulty": "easy"},
    {"id": "b2_01_q083", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ wir in München ankommen, suchen wir ein Hotel.", "options": ["Während", "Bevor", "Sobald", "Als"], "correctAnswer": "Sobald", "explanation": '"Sobald" zeigt die erste Handlung nach der Ankunft.', "difficulty": "easy"},
    {"id": "b2_01_q084", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ der Film zu Ende ist, gehen wir essen.", "options": ["Während", "Bevor", "Sobald", "Wenn"], "correctAnswer": "Sobald", "explanation": '"Sobald" zeigt die Planung unmittelbar nach dem Film.', "difficulty": "easy"},
    # SOLANGE (12)
    {"id": "b2_01_q085", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ du lernst, darfst du hier bleiben.", "options": ["Während", "Solange", "Bevor", "Sobald"], "correctAnswer": "Solange", "explanation": '"Solange" bedeutet "as long as" — die Erlaubnis gilt während der Lernzeit.', "difficulty": "easy"},
    {"id": "b2_01_q086", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ du hier bleibst, werde ich glücklich sein.", "options": ["Während", "Solange", "Bevor", "Als"], "correctAnswer": "Solange", "explanation": '"Solange" zeigt die Bedingung für das Glück während einer Zeitperiode.', "difficulty": "easy"},
    {"id": "b2_01_q087", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "Er hat ihr zugehört, ___ sie gesprochen hat.", "options": ["Während", "Solange", "Bevor", "Sobald"], "correctAnswer": "Solange", "explanation": '"Solange" zeigt die Dauer der Aufmerksamkeit während des Sprechens.', "difficulty": "medium"},
    {"id": "b2_01_q088", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ du die Wahrheit sagst, habe ich keine Fragen.", "options": ["Während", "Solange", "Bevor", "Wenn"], "correctAnswer": "Solange", "explanation": '"Solange" zeigt die Bedingung während einer Zeitperiode der Ehrlichkeit.', "difficulty": "medium"},
    {"id": "b2_01_q089", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "Das Auto kann hier stehen, ___ wir einkaufen.", "options": ["Während", "Solange", "Bevor", "Sobald"], "correctAnswer": "Solange", "explanation": '"Solange" zeigt die erlaubte Zeitdauer des Parkens.', "difficulty": "easy"},
    {"id": "b2_01_q090", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "Ich werde dich unterstützen, ___ du es brauchst.", "options": ["Während", "Solange", "Bevor", "Wenn"], "correctAnswer": "Solange", "explanation": '"Solange" zeigt die Dauer des Unterstützungsangebots.', "difficulty": "easy"},
    {"id": "b2_01_q091", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ du Geduld hast, wird alles gut.", "options": ["Während", "Solange", "Bevor", "Nachdem"], "correctAnswer": "Solange", "explanation": '"Solange" zeigt die Bedingung während einer Zeitperiode der Geduld.', "difficulty": "medium"},
    {"id": "b2_01_q092", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "Er ist zu Hause geblieben, ___ seine Frau krank war.", "options": ["Während", "Solange", "Bevor", "Sobald"], "correctAnswer": "Solange", "explanation": '"Solange" zeigt die Dauer des Zuhausebleibens während der Krankheit.', "difficulty": "medium"},
    {"id": "b2_01_q093", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ ich kann, helfe ich dir bei deinem Projekt.", "options": ["Während", "Solange", "Bevor", "Wenn"], "correctAnswer": "Solange", "explanation": '"Solange" zeigt die zeitlich begrenzte Hilfe während meiner Fähigkeit.', "difficulty": "medium"},
    {"id": "b2_01_q094", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "Du darfst mein Buch behalten, ___ du es brauchst.", "options": ["Während", "Solange", "Bevor", "Sobald"], "correctAnswer": "Solange", "explanation": '"Solange" zeigt die Zeitperiode der Erlaubnis.', "difficulty": "easy"},
    {"id": "b2_01_q095", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ wir hier wohnen, gehen wir jeden Sonntag in die Kirche.", "options": ["Während", "Solange", "Bevor", "Als"], "correctAnswer": "Solange", "explanation": '"Solange" zeigt die Routine während eines Wohnaufenthalts.', "difficulty": "medium"},
    {"id": "b2_01_q096", "subjectId": "b2_01", "type": "multiple_choice", "questionText": "___ es dunkel ist, sollte man das Licht anmachen.", "options": ["Während", "Solange", "Bevor", "Sobald"], "correctAnswer": "Solange", "explanation": '"Solange" zeigt die Handlung während einer Zeitperiode der Dunkelheit.', "difficulty": "easy"},
]

# Add topicName to each
for q in curated_qs:
    q['topicName'] = 'Konnektoren'

print(f"Prepared {len(curated_qs)} curated questions")

# Load existing b2_questions.json
import os
b2_path = '/home/node/.openclaw/workspace/b2-deutsch-app/app/src/main/assets/b2_questions.json'
data = json.load(open(b2_path))

# Remove old b2_01 and b2_02 questions
old_count = len(data['questionBank'])
data['questionBank'] = [q for q in data['questionBank'] if q['subjectId'] not in ('b2_01', 'b2_02')]
removed = old_count - len(data['questionBank'])
print(f"Removed {removed} old questions (b2_01 + b2_02)")

# Add our 96 new curated questions
data['questionBank'].extend(curated_qs)
data['totalQuestions'] = len(data['questionBank'])

# Update topics metadata
if 'topics' in data and 'b2_01' in data['topics']:
    data['topics']['b2_01']['name'] = 'Konnektoren'
    data['topics']['b2_01']['count'] = 96
    data['topics']['b2_01']['questionIds'] = [q['id'] for q in curated_qs]

if 'topics' in data and 'b2_02' in data['topics']:
    del data['topics']['b2_02']

# Save
with open(b2_path, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Done! Total questions now: {data['totalQuestions']}")
print(f"Topics remaining: {list(data.get('topics', {}).keys())}")
