import json

with open('app/src/main/assets/c1_02.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

print(f"Current: {len(data['questions'])} questions")

next_id = 81

questions_raw = [
    {"difficulty": "easy", "type": "multiple_choice", "questionText": "Ergaenzen Sie die Luecke fuer die indirekte Rede: Der Minister betonte, die Regierung ____ alle notwendigen Massnahmen ergreifen.", "options": ["werde", "wird", "wuerde", "werden"], "correctAnswer": "werde", "explanation": "For the third person singular (die Regierung), Konjunktiv I of 'werden' is 'werde'. It is the standard form used in indirect speech to report a statement objectively."},
    {"difficulty": "medium", "type": "multiple_choice", "questionText": "Welche Form ist korrekt, wenn Konjunktiv I und Indikativ identisch sind? Sie sagten: 'Wir reisen morgen ab.' -> Sie sagten, sie ____ morgen ab.", "options": ["verreisen", "reisten", "reisen", "wuerden abreisen"], "correctAnswer": "reisten", "explanation": "Konjunktiv I 'reisen' is identical to indicative 'sie reisen'. Therefore, Konjunktiv II ('reisten') is used to clearly mark indirect speech. The 'wuerde'-construction is also acceptable in spoken language."},
    {"difficulty": "easy", "type": "multiple_choice", "questionText": "Ergaenzen Sie das Verb im Konjunktiv I: Der Zeuge behauptete, er ____ den An geklagten noch nie zuvor gesehen.", "options": ["habe", "haette", "hat", "habe gehabt"], "correctAnswer": "habe", "explanation": "Original statement was in Perfekt or Praeteritum. In indirect speech, past tenses are rendered using Konjunktiv I of auxiliary 'haben' (3rd person singular: 'habe') + Past Participle."},
    {"difficulty": "easy", "type": "multiple_choice", "questionText": "Waehlen Sie die richtige Form von 'sein': Die Forscher gaben an, die Ergebnisse ____ eindeutig.", "options": ["seien", "sind", "waeren", "seist"], "correctAnswer": "seien", "explanation": "Subject 'die Ergebnisse' is plural (3rd person plural). Konjunktiv I of 'sein' in plural is 'seien'. Unlike many other verbs, 'seien' is visibly distinct from indicative 'sind', so no replacement form is needed."},
    {"difficulty": "medium", "type": "multiple_choice", "questionText": "Wie wird eine Aufforderung in der indirekten Rede korrekt wiedergegeben? Der Arzt riet mir: 'Trinken Sie mehr Wasser!' -> Der Arzt riet mir, ich ____ mehr Wasser trinken.", "options": ["solle", "müsse", "werde", "wolle"], "correctAnswer": "solle", "explanation": "Commands, requests, or advices are converted into indirect speech using 'sollen' in Konjunktiv I form ('solle'). This is the standard C1 transformation for imperatives."},
    {"difficulty": "medium", "type": "multiple_choice", "questionText": "Eraeutzen Sie den Satz: Der Oekonom erklaerte, durch die Krise ____ viele Unternehmen Insolvenz anmelden.", "options": ["muessten", "muessen", "muesst", "muessten"], "correctAnswer": "muessten", "explanation": "Subject 'viele Unternehmen' is plural. Konjunktiv I 'muessen' is identical to indicative present tense. Therefore it is replaced by Konjunktiv II 'muessten'."},
    {"difficulty": "easy", "type": "multiple_choice", "questionText": "Welche Form von 'wissen' passt in diese C1-Erzählung? Die An geklagte beteuerte, sie ____ nichts von den illegalen Transaktionen.", "options": ["wisse", "wusste", "wuesste", "habe gewusst"], "correctAnswer": "wisse", "explanation": "Present-tense 'Ich weiss nichts' becomes 'sie wisse' in 3rd person singular Konjunktiv I. 'Wisse' is distinct from indicative 'weiss', so Konjunktiv I is used directly."},
    {"difficulty": "easy", "type": "multiple_choice", "questionText": "Transformieren Sie eine Frage ohne Fragewort: Er fragte mich: 'Kommst du mit?' -> Er fragte mich, ____ ich mitkomme.", "options": ["ob", "dass", "wann", "wie"], "correctAnswer": "ob", "explanation": "Yes/No questions (Entscheidungsfragen) without an interrogative pronoun are introduced with the conjunction 'ob' in indirect speech."},
    {"difficulty": "medium", "type": "multiple_choice", "questionText": "Waehlen Sie das korrekte Verb fuer die indirekte Rede der Vergangenheit: Die Zeugen sagten aus, sie ____ den Unfallort sofort verlassen.", "options": ["haetten", "haben", "haetten gehabt", "seien"], "correctAnswer": "haetten", "explanation": "In plural, Konjunktiv I 'haben' is identical to indicative 'sie haben'. Thus it is replaced by Konjunktiv II 'haetten'."},
    {"difficulty": "hard", "type": "multiple_choice", "questionText": "Was signalisiert der Gebrauch von Konjunktiv II statt Konjunktiv I in: 'Der Sprecher sagte, der Chef haette keine Zeit gehabt.'?", "options": ["Der Berichtende zweifelt an der Richtigkeit der Aussage.", "Der Satz ist grammatikalisch falsch.", "Es handelt sich um ein Versprechen fuer die Zukunft.", "Der Sprecher betont, dass er absolut sicher ist."], "correctAnswer": "Der Berichtende zweifelt an der Richtigkeit der Aussage.", "explanation": "Shifting to Konjunktiv II when Konjunktiv I would have been unambiguous signals distance from the statement or doubt about its truth."},
    {"difficulty": "hard", "type": "multiple_choice", "questionText": "Eraeutzen Sie das Passiv in der indirekten Rede: Der Bericht stellte fest, dass das Gebaeude bereits im Mai ____.", "options": ["verkauft worden sei", "verkauft worden waere", "verkauft wurde", "verkauft worden sein werde"], "correctAnswer": "verkauft worden sei", "explanation": "Past passive in Konjunktiv I is formed using past participle + 'worden' + Konjunktiv I of 'sein' (3rd person singular: 'sei')."},
    {"difficulty": "easy", "type": "multiple_choice", "questionText": "Welche Konjunktiv I Form von 'geben' ist korrekt? Der Wetterdienst teilte mit, es ____ am Wochenende heftige Unwetter.", "options": ["gebe", "gae be", "gibt", "geben werde"], "correctAnswer": "gebe", "explanation": "Third person singular of 'geben' in Konjunktiv I is 'gebe'. It is distinct from indicative 'gibt', so no Konjunktiv II replacement is needed."},
    {"difficulty": "medium", "type": "multiple_choice", "questionText": "Setzen Sie in die indirekte Rede (Zukunft): Sie versicherten uns: 'Wir werden punktlich liefern.' -> Sie versicherten uns, sie ____ punktlich liefern.", "options": ["wuerden", "werden", "werdet", "wollten"], "correctAnswer": "wuerden", "explanation": "Plural Konjunktiv I 'werden' matches the indicative. Therefore it is replaced by Konjunktiv II form 'wuerden' to indicate future tense in indirect speech."},
    {"difficulty": "medium", "type": "multiple_choice", "questionText": "Wie lautet die korrekte indirekte Rede fuer ein Verbot? Der Chef wies an: 'Niemand darf das Labor ohne Maske betreten.' -> Der Chef wies an, niemand ____ das Labor ohne Maske betreten.", "options": ["duerfe", "darf", "due rfte", "solle"], "correctAnswer": "duerfe", "explanation": "Modal verb 'due rfen' in Konjunktiv I 3rd person singular is 'duerfe'. This is used directly in indirect speech for permission/prohibition statements."},
    {"difficulty": "hard", "type": "multiple_choice", "questionText": "Welcher Satz ist stilistisch auf bestem C1-Niveau fuer journalistische Berichterstattung?", "options": ["Laut Regierungsangaben wolle man die Steuern im naechsten Jahr senken.", "Die Regierung sagte, dass sie die Steuern naechstes Jahr senken wollen.", "Regierungsangaben zufolge wuerden die Steuern naechstes Jahr gesenkt werden.", "Der Kanzler sagte, er wird die Steuern senken."], "correctAnswer": "Laut Regierungsangaben wolle man die Steuern im naechsten Jahr senken.", "explanation": "The combination of prepositional source reference 'Laut...' with modal verb 'wollen' in Konjunktiv I ('wolle') represents excellent academic/journalistic style."},
    {"difficulty": "medium", "type": "multiple_choice", "questionText": "Vervollstaendigen Sie die indirekte Rede: Die Aktivisten meinten, sie ____ seit Jahren fuer den Klimaschutz.", "options": ["kaempften", "kaempfen", "haben gekuaempft", "wuerden kaempfen"], "correctAnswer": "kaempften", "explanation": "For plural 'sie', Konjunktiv I 'kaempfen' is identical to indicative. The correct substitution is Konjunktiv II 'kaempften'."},
    {"difficulty": "hard", "type": "multiple_choice", "questionText": "Welche Konjunktiv-Form von 'moegen' druckt einen Wunsch in der indirekten Rede aus? Der Kunde aeusserte, er ____ mit dem Geschaeftsfuehrer sprechen.", "options": ["moechte", "mache", "mag", "moege"], "correctAnswer": "moechte", "explanation": "'Moechte' (Konjunktiv II of 'moegen') is the standard way to express a polite wish in indirect speech, matching the direct speech choice 'Ich moechte...'."},
    {"difficulty": "easy", "type": "multiple_choice", "questionText": "Eraeutzen Sie das fehlende Verb: Die Nachbarn behaupteten, sie ____ die laute Musik gar nicht gehoert.", "options": ["haetten", "haben", "habe", "seien"], "correctAnswer": "haetten", "explanation": "Since 'die Nachbarn' is plural, the past auxiliary 'haben' is replaced by Konjunktiv II 'haetten' because Konjunktiv I ('haben') equals the indicative."},
    {"difficulty": "hard", "type": "multiple_choice", "questionText": "In welchem Fall wird der Konjunktiv I in der Alltagssprache am haeufigsten durch den Indikativ ersetzt, ohne dass es falsch wirkt?", "options": ["Wenn der Nebensatz mit der Konjunktion 'dass' eingeleitet wird.", "Wenn der Hauptsatz im Praeteritum steht.", "Wenn es sich um wissenschaftliche Berichte handelt.", "Wenn der Sprecher seine eigene Aussage wiederholt."], "correctAnswer": "Wenn der Nebensatz mit der Konjunktion 'dass' eingeleitet wird.", "explanation": "In modern German, introducing the indirect speech clause with 'dass' often tolerates the indicative mood in colloquial registers, as the subordination itself already marks the indirect nature."},
    {"difficulty": "easy", "type": "multiple_choice", "questionText": "Eraeutzen Sie die Luecke: Das Gericht stellte klar, der An geklagte ____ voll schuldfaehig.", "options": ["sei", "waere", "ist", "seien"], "correctAnswer": "sei", "explanation": "Subject 'der An geklagte' is singular. Konjunktiv I of 'sein' is 'sei', making it ideal for formal court reporting."}
]

for q in questions_raw:
    q["id"] = f"c1_02_q{str(next_id).zfill(3)}"
    next_id += 1

data['questions'].extend(questions_raw)
data['totalQuestions'] = len(data['questions'])

with open('app/src/main/assets/c1_02.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Added {len(questions_raw)} questions. New total: {data['totalQuestions']}")
print(f"IDs: {questions_raw[0]['id']} — {questions_raw[-1]['id']}")
