import json

with open('app/src/main/assets/c1_03.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

print(f"Current: {len(data['questions'])} questions")

next_id = 81

questions_raw = [
    {"difficulty": "easy", "type": "multiple_choice", "questionText": "Welche Konstruktion ist eine typische Passiversatzform?", "options": ["Er wird das Paket schicken.", "Das Paket laesst sich leicht schicken.", "Das Paket wurde geschickt.", "Er schickt das Paket."], "correctAnswer": "lässt sich leicht schicken", "explanation": "'sich lassen + Infinitiv' is one of the most common passive substitutes in German. It expresses possibility or ability, similar to 'koennen + Passiv'. The other options are either active, future, or genuine passive constructions."},
    {"difficulty": "easy", "type": "multiple_choice", "questionText": "Ersetzen Sie das Passiv durch eine Passiversatzform: 'Das Formular kann ausgefuellt werden.'", "options": ["Das Formular ist ausgefuellt.", "Das Formular fuellt sich aus.", "Das Formular laesst sich ausfuellen.", "Das Formular wird ausgefuellt."], "correctAnswer": "Das Formular laesst sich ausfuellen", "explanation": "'laesst sich ausfuellen' replaces 'kann ausgefuellt werden'. Both express that filling out the form is possible. 'sich lassen + Infinitiv' always implies possibility or feasibility."},
    {"difficulty": "easy", "type": "multiple_choice", "questionText": "Was bedeutet die Konstruktion 'sein + zu + Infinitiv'?", "options": ["Eine abgeschlossene Handlung in der Vergangenheit", "Eine Moeglichkeit oder Notwendigkeit (Passiversatzform)", "Eine Bitte oder ein Wunsch", "Eine zukuenftige Handlung"], "correctAnswer": "Eine Moeglichkeit oder Notwendigkeit (Passiversatzform)", "explanation": "'Sein + zu + Infinitiv' is a passive substitute expressing either possibility ('can be done') or necessity ('must be done'), depending on context."},
    {"difficulty": "easy", "type": "multiple_choice", "questionText": "Wandeln Sie um: 'Die Aufgabe muss erledigt werden.' -> Passiversatzform mit 'sein'", "options": ["Die Aufgabe ist erledigt worden.", "Die Aufgabe ist zu erledigen.", "Die Aufgabe soll erledigt sein.", "Die Aufgabe waere zu erledigen."], "correctAnswer": "Die Aufgabe ist zu erledigen", "explanation": "'ist zu erledigen' replaces 'muss erledigt werden'. The construction 'Sein + zu + Infinitiv' expresses obligation or necessity and is a classic Passiversatzform."},
    {"difficulty": "easy", "type": "multiple_choice", "questionText": "Welche Passiversatzform druckt aus, dass etwas moeglich ist?", "options": ["Sein + zu + Infinitiv (im Sinne von Pflicht)", "sich lassen + Infinitiv", "haben + zu + Infinitiv", "brauchen + nicht + zu + Infinitiv"], "correctAnswer": "sich lassen + Infinitiv", "explanation": "'sich lassen + Infinitiv' expresses possibility. 'haben + zu' and 'Sein + zu' (obligation sense) express necessity. 'brauchen + nicht + zu' expresses something is not necessary."},
    {"difficulty": "easy", "type": "multiple_choice", "questionText": "Ersetzen Sie das Passiv: 'Der Text kann leicht verstanden werden.'", "options": ["Der Text versteht sich leicht.", "Der Text laesst sich leicht verstehen.", "Der Text ist leicht zu verstehen.", "Sowohl B als auch C sind korrekte Passiversatzformen."], "correctAnswer": "Sowohl B als auch C sind korrekte Passiversatzformen", "explanation": "Both 'laesst sich leicht verstehen' and 'ist leicht zu verstehen' are valid passive substitutes for 'kann leicht verstanden werden'. Option A carries a different idiomatic meaning."},
    {"difficulty": "medium", "type": "multiple_choice", "questionText": "Wandeln Sie um: 'Die Rechnung muss bis Freitag bezahlt werden.' -> Passiversatzform mit 'haben'", "options": ["Die Rechnung hat bis Freitag bezahlt.", "Die Rechnung ist bis Freitag zu bezahlen.", "Die Rechnung hat bis Freitag zu bezahlen.", "Man hat die Rechnung bis Freitag bezahlt."], "correctAnswer": "Die Rechnung hat bis Freitag zu bezahlen", "explanation": "'haben + zu + Infinitiv' expresses obligation equivalent to 'muessen + Passiv'. The subject of 'haben' here is the thing that must be done ('die Rechnung'), not a person."},
    {"difficulty": "medium", "type": "multiple_choice", "questionText": "Welcher Satz enthaelt eine korrekte Verwendung von 'sich lassen'?", "options": ["Das Problem laesst sich nicht ignorieren.", "Das Problem laesst sich nicht ignoriert.", "Das Problem laesst nicht sich ignorieren.", "Das Problem hat sich nicht ignorieren lassen."], "correctAnswer": "Das Problem laesst sich nicht ignorieren", "explanation": "'sich lassen + Infinitiv' requires the infinitive (not Partizip II). The reflexive 'sich' must directly follow 'laesst'. Option D uses 'hat ... lassen' which changes the tense."},
    {"difficulty": "medium", "type": "multiple_choice", "questionText": "Ersetzen Sie: 'Die neuen Vorschriften muessen beachtet werden.' Welche Passiversatzform mit Adjektiv auf '-bar' ist moeglich?", "options": ["Die neuen Vorschriften sind beachtenswert.", "Die neuen Vorschriften sind beachtbar.", "Die neuen Vorschriften sind unbeachtlich.", "Die neuen Vorschriften sind verbindlich."], "correctAnswer": "Die neuen Vorschriften sind beachtbar", "explanation": "Adjectives ending in '-bar' from verb stems function as passive substitutes: 'beachtbar' = 'can/must be observed'. Note: in practice 'verbindlich' is more natural, but '-bar' adjectives are a recognized Passiversatzform category."},
    {"difficulty": "medium", "type": "multiple_choice", "questionText": "Was ist der Unterschied zwischen 'Sein + zu + Infinitiv' und 'haben + zu + Infinitiv'?", "options": ["Es gibt keinen Unterschied; beide sind austauschbar.", "'Sein + zu + Infinitiv' betont die Pflicht des Subjekts; 'haben + zu + Infinitiv' bescreibt einen Zustand.", "'haben + zu + Infinitiv' hat ein persoenliches Subjekt (Person als Handlungstraeger); 'Sein + zu + Infinitiv' hat oft ein sachliches Subjekt.", "'haben + zu + Infinitiv' wird nur im Perfekt verwendet."], "correctAnswer": "'haben + zu + Infinitiv' hat ein persoenliches Subjekt (Person als Handlungstraeger); 'Sein + zu + Infinitiv' hat oft ein sachliches Subjekt", "explanation": "With 'haben + zu + Infinitiv', the subject is typically the agent (a person who has an obligation): 'Er hat den Bericht zu schreiben'. With 'Sein + zu + Infinitiv', the subject is the object being acted upon: 'Der Bericht ist zu schreiben'."},
    {"difficulty": "medium", "type": "multiple_choice", "questionText": "'Der Schaden ____ nicht mehr ____.' - Ergaenzen Sie die Passiversatzform mit 'lassen'.", "options": ["laesst / reparieren", "laesst sich / reparieren", "hat sich / repariert", "laesst / sich reparieren"], "correctAnswer": "laesst sich / reparieren", "explanation": "The correct structure is: 'Der Schaden laesst sich nicht mehr reparieren.' The reflexive 'sich' belongs to 'lassen', not to 'reparieren', and the infinitive comes at the end."},
    {"difficulty": "medium", "type": "multiple_choice", "questionText": "Welche Passiversatzform druckt KEINE Notwendigkeit aus?", "options": ["Sein + zu + Infinitiv", "haben + zu + Infinitiv", "sich lassen + Infinitiv", "brauchen + nicht + zu + Infinitiv"], "correctAnswer": "sich lassen + Infinitiv", "explanation": "'sich lassen + Infinitiv' expresses possibility, not necessity. 'Sein + zu + Infinitiv' and 'haben + zu + Infinitiv' express obligation. 'brauchen + nicht + zu + Infinitiv' expresses that something is not necessary."},
    {"difficulty": "medium", "type": "multiple_choice", "questionText": "Ersetzen Sie das Passiv: 'Die Ergebnisse koennen nicht angezweifelt werden.'", "options": ["Die Ergebnisse lassen sich nicht anzweifeln.", "Die Ergebnisse sind nicht anzuzweifeln.", "Die Ergebnisse haben sich nicht anzuzwe。随后eln.", "Die Ergebnisse koennen nicht angezweifelt sein."], "correctAnswer": "Die Ergebnisse sind nicht anzuzweifeln", "explanation": "'sind + zu + Infinitiv' with negation expresses that something cannot or should not be done. Note the separable verb: 'anzuzweifeln' (an-zu-zweifeln). Option A is incorrect because 'lassen' requires the plain infinitive (anzweifeln), not a zu-infinitive."},
    {"difficulty": "medium", "type": "multiple_choice", "questionText": "Welches Adjektivsuffix bildet haeufig eine Passiversatzform?", "options": ["-lich", "-bar", "-ig", "-sam"], "correctAnswer": "-bar", "explanation": "Adjectives with the suffix '-bar' (e.g. 'loesbar', 'machbar', 'erkennbar') are formed from verb stems and function as passive substitutes meaning 'can be done'."},
    {"difficulty": "hard", "type": "multiple_choice", "questionText": "Wandeln Sie vollstaendig um: 'Die Unterlagen muessen bis Montag eingereicht werden.' -> Passiversatzform mit 'haben'", "options": ["Die Unterlagen haben bis Montag einzureichen.", "Man hat die Unterlagen bis Montag einzureichen.", "Die Unterlagen haben bis Montag eingereicht.", "Die Unterlagen sind bis Montag einzureichen."], "correctAnswer": "Die Unterlagen sind bis Montag einzureichen", "explanation": "When the subject is the object being acted upon (docs, not a person), 'Sein + zu + Infinitiv' is the correct substitution for 'muessen + Passiv'. 'haben + zu + Infinitiv' requires a personal agent as subject."},
    {"difficulty": "hard", "type": "multiple_choice", "questionText": "Welche Aussage ueber '-bar'-Adjektive als Passiversatzformen ist FALSCH?", "options": ["Sie drucken aus, dass etwas moeglich ist.", "Sie werden aus Verbstämmen gebildet (z.B. loesen -> loesbar).", "Sie koennen immer durch 'sich lassen + Infinitiv' ersetzt werden.", "Nicht alle Verben bilden gebrauchliche '-bar'-Adjektive."], "correctAnswer": "Sie koennen immer durch 'sich lassen + Infinitiv' ersetzt werden", "explanation": "While '-bar' adjectives and 'sich lassen + Infinitiv' both express possibility, they are not always interchangeable. Some '-bar' adjectives have lexicalized meanings that differ from a literal 'sich lassen' construction."},
    {"difficulty": "hard", "type": "multiple_choice", "questionText": "Formen Sie um: 'Der Konflikt kann durch Dialog geloest werden.' Welche zwei Passiversatzformen sind korrekt?", "options": ["Der Konflikt laesst sich durch Dialog loesen. / Der Konflikt ist durch Dialog zu loesen.", "Der Konflikt hat sich durch Dialog zu loesen. / Der Konflikt loest sich durch Dialog.", "Der Konflikt ist durch Dialog geloest. / Der Konflikt laesst sich durch Dialog geloest.", "Der Konflikt laesst durch Dialog loesen. / Der Konflikt ist loesbar durch Dialog."], "correctAnswer": "Der Konflikt laesst sich durch Dialog loesen. / Der Konflikt ist durch Dialog zu loesen", "explanation": "Both 'laesst sich loesen' and 'ist zu loesen' correctly replace 'kann geloest werden'. The agent phrase 'durch Dialog' is retained in both."},
    {"difficulty": "hard", "type": "multiple_choice", "questionText": "Welcher Satz verwendet 'haben + zu + Infinitiv' KORREKT?", "options": ["Das Gebaude hat abgerissen zu werden.", "Der Mieter hat die Wohnung bis Ende des Monats zu raumen.", "Die Wohnung hat sich zu raumen.", "Der Vertrag hat zu unterschreiben bis Freitag."], "correctAnswer": "Der Mieter hat die Wohnung bis Ende des Monats zu raumen", "explanation": "'haben + zu + Infinitiv' requires a personal subject (here: 'der Mieter') who has an obligation. Option A is incorrect because 'haben' is not used with passive infinitives; Options C and D have incorrect word order."},
    {"difficulty": "hard", "type": "multiple_choice", "questionText": "Bestimmen Sie die Bedeutung: 'Die Klausel ist so nicht hinzunehmen.'", "options": ["Die Klausel wurde nicht hinzugefuegt.", "Die Klausel kann so nicht akzeptiert werden.", "Die Klausel hat nichts hinzuzufuegen.", "Die Klausel ist nicht vorhanden."], "correctAnswer": "Die Klausel kann so nicht akzeptiert werden", "explanation": "'ist + zu + Infinitiv' with negation expresses impossibility or unacceptability: the clause cannot/should not be accepted as it is. 'hinzunehmen' means 'to accept/tolerate'."},
    {"difficulty": "hard", "type": "multiple_choice", "questionText": "Welche Passiversatzform ist im Satz enthalten und was bedeutet sie? 'Saemtliche Einwaende des Ausschusses sind in der Analyse zu beruecksichtigen.'", "options": ["'sich lassen + Infinitiv' - die Einwaende koennen beruecksichtigt werden", "'Sein + zu zu + Infinitiv' - die Einwaende muessen beruecksichtigt werden", "'haben + zu + Infinitiv' - der Ausschuss muss die Einwaende beruecksichtigen", "'-bar'-Adjektiv - die Einwaende sind beruecksichtigbar"], "correctAnswer": "'Sein + zu + Infinitiv' - die Einwaende muessen beruecksichtigt werden", "explanation": "'sind zu beruecksichtigen' is the 'Sein + zu + Infinitiv' construction. In formal/official contexts, it expresses obligation: the objections must be taken into account."}
]

for q in questions_raw:
    q["id"] = f"c1_03_q{str(next_id).zfill(3)}"
    next_id += 1

data['questions'].extend(questions_raw)
data['totalQuestions'] = len(data['questions'])

with open('app/src/main/assets/c1_03.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Added {len(questions_raw)} questions. New total: {data['totalQuestions']}")
print(f"IDs: {questions_raw[0]['id']} — {questions_raw[-1]['id']}")
bad = [(q['id'], len(q['options'])) for q in data['questions'] if len(q['options']) != 4]
print(f"Questions with !=4 options: {bad if bad else 'None — all OK'}")
