import json

questions = [
    {"difficulty": "easy", "type": "multiple_choice", "questionText": "Passiversatzformen werden verwendet, um den ____ zu vermeiden oder stilistisch abwechslungsreicher zu gestalten.", "options": ["Konjunktiv", "Vorgangspassiv", "Zustandspassiv", "Imperativ"], "correctAnswer": "Vorgangspassiv", "explanation": "Passive alternatives (Passiversatzformen) help avoid the standard Vorgangspassiv (werden + past participle) for stylistic variety or to sound more natural."},
    {"difficulty": "medium", "type": "multiple_choice", "questionText": "Welches Verb ist eine typische Passiversatzform mit der Bedeutung 'koennen'?", "options": ["sein + zu + Infinitiv", "lassen sich", "gehoeren + past participle", "bleiben + past participle"], "correctAnswer": "lassen sich", "explanation": "'lassen sich' + Infinitive expresses passive meaning with modal nuance of possibility, e.g., 'Das Problem laesst sich loesen' = 'The problem can be solved'."},
    {"difficulty": "easy", "type": "multiple_choice", "questionText": "Ersetzen Sie das Passiv durch eine Passiversatzform: 'Das Formular muss ausgefüllt werden.'", "options": ["Das Formular ist auszufuellen.", "Das Formular laesst sich ausfuellen.", "Das Formular gehoert ausgfuellt.", "Das Formular bleibt auszufuellen."], "correctAnswer": "Das Formular ist auszufuellen.", "explanation": "'sein + zu + Infinitiv' expresses necessity/duty, equivalent to 'muessen + Passiv'. 'Das Formular ist auszufuellen' = 'The form must be filled out'."},
    {"difficulty": "medium", "type": "multiple_choice", "questionText": "____ druckt eine passive Bedeutung mit einer modalen Nuance der Moeglichkeit aus.", "options": ["sich lassen + Infinitiv", "sein + zu + Infinitiv", "gehoeren + past participle", "bleiben + past participle"], "correctAnswer": "sich lassen + Infinitiv", "explanation": "'sich lassen + Infinitiv' means 'can be done' (possibility), e.g., 'Das Buch laesst sich leicht lesen' = 'The book can be read easily'."},
    {"difficulty": "easy", "type": "multiple_choice", "questionText": "Welcher Satz ist eine Passiversatzform mit 'sich lassen'?", "options": ["Die Aufgabe ist zu schaffen.", "Die Aufgabe laesst sich schaffen.", "Die Aufgabe wird geschafft.", "Die Aufgabe gehoert geschafft."], "correctAnswer": "Die Aufgabe laesst sich schaffen.", "explanation": "'laesst sich schaffen' is the passive replacement form. The others are either 'sein + zu' or standard passive."},
    {"difficulty": "easy", "type": "multiple_choice", "questionText": "Die Konstruktion 'sein + zu + Infinitiv' druckt meist ____ aus.", "options": ["Moeglichkeit", "Notwendigkeit oder Aufforderung", "Vergangenheit", "Wunsch"], "correctAnswer": "Notwendigkeit oder Aufforderung", "explanation": "'sein + zu + Infinitiv' typically expresses necessity or obligation, similar to 'muessen' or 'sollen' in passive voice."},
    {"difficulty": "medium", "type": "multiple_choice", "questionText": "Vervollstaendigen Sie: 'Diese Rechnung ____ nicht mehr bezahlt werden.'", "options": ["laesst sich", "ist zu", "hat sich", "bleibt"], "correctAnswer": "ist zu", "explanation": "'ist zu bezahlen' = must be paid. 'ist zu + Infinitiv' is correct. 'laesst sich bezahlen' would mean 'can be paid' (possibility, not necessity)."},
    {"difficulty": "medium", "type": "multiple_choice", "questionText": "Welche Bedeutung hat 'sich lassen + Infinitiv' im Vergleich zum normalen Passiv?", "options": ["Es betont die Handlung selbst.", "Es betont die Moeglichkeit oder Machbarkeit.", "Es betont den Zustand.", "Es betont den Zeitpunkt."], "correctAnswer": "Es betont die Moeglichkeit oder Machbarkeit.", "explanation": "'sich lassen' adds a modal flavor of possibility/feasibility, whereas standard passive simply states the action without modal nuance."},
    {"difficulty": "hard", "type": "multiple_choice", "questionText": "Ersetzen Sie: 'Dieser Text kann nicht uebersetzt werden.' (Passiversatzform mit 'lassen')", "options": ["Dieser Text laesst sich nicht uebersetzen.", "Dieser Text ist nicht zu uebersetzen.", "Dieser Text bleibt unuebersetzt.", "Dieser Text gehoert nicht uebersetzt."], "correctAnswer": "Dieser Text laesst sich nicht uebersetzen.", "explanation": "Modal verb 'kann' + passive → 'laesst sich nicht uebersetzen' expresses impossibility. 'ist nicht zu uebersetzen' would mean 'must not be translated' (different nuance)."},
    {"difficulty": "easy", "type": "multiple_choice", "questionText": "____ wird oft als Ersatz fuer das Passiv mit Modalverb verwendet, besonders bei Handlungsverben.", "options": ["Die Konstruktion 'bleiben + past participle'", "Die Konstruktion 'gehoeren + past participle'", "Die Konstruktion 'sich lassen + Infinitiv'", "Die Konstruktion 'sein + am + Infinitiv'"], "correctAnswer": "Die Konstruktion 'sich lassen + Infinitiv'", "explanation": "'sich lassen' is a common alternative when a modal verb (koennen) + passive would be used, especially for actions."},
    {"difficulty": "medium", "type": "multiple_choice", "questionText": "'Die Tuer bleibt geschlossen.' – Welche Funktion hat dieser Satz?", "options": ["Vorgangspassiv", "Zustandspassiv", "Passiversatzform mit 'bleiben'", "Aktivsatz"], "correctAnswer": "Passiversatzform mit 'bleiben'", "explanation": "'bleiben + past participle' is a passive replacement form that emphasizes the resulting state or that the state continues."},
    {"difficulty": "medium", "type": "multiple_choice", "questionText": "Welche Passiversatzform druckt aus, dass eine Handlung nicht abgeschlossen ist oder ein Zustand anhaelt?", "options": ["sich lassen + Infinitiv", "sein + zu + Infinitiv", "bleiben + past participle", "gehoeren + past participle"], "correctAnswer": "bleiben + past participle", "explanation": "'bleiben + past participle' indicates that something remains in a certain state, often as a result of a previous action (e.g., 'Das Problem bleibt ungeloest')."},
    {"difficulty": "hard", "type": "multiple_choice", "questionText": "Vervollstaendigen Sie: (bleiben) 'Das Essen ____ auf dem Tisch stehen gelassen.'", "options": ["laesst sich", "ist zu", "bleibt", "gehoert"], "correctAnswer": "bleibt", "explanation": "'bleibt stehen gelassen' = remains left standing. 'bleiben + past participle' shows a continuing state."},
    {"difficulty": "hard", "type": "multiple_choice", "questionText": "Die Konstruktion 'gehoeren + past participle' wird im Deutschen ____ verwendet.", "options": ["als Ersatz fuer das Passiv mit Modalverb 'muessen'", "regional (besonders suenddeutsch/ oesterreichisch)", "nur in der gesprochenen Sprache", "als Ersatz fuer 'sich lassen'"], "correctAnswer": "regional (besonders suenddeutsch/ oesterreichisch)", "explanation": "'gehoeren + past participle' (e.g., 'Das gehoert repariert') is regionally used, especially in southern Germany, Austria, and Switzerland, meaning 'needs to be done'."},
    {"difficulty": "medium", "type": "multiple_choice", "questionText": "Was bedeutet 'Das Auto gehoert gewaschen'?", "options": ["Das Auto kann gewaschen werden.", "Das Auto wird gewaschen.", "Das Auto muss gewaschen werden.", "Das Auto bleibt gewaschen."], "correctAnswer": "Das Auto muss gewaschen werden.", "explanation": "In regional usage (S Germany/Austria), 'gehoert gewaschen' means 'needs to be washed' (necessity), similar to 'muss gewaschen werden'."},
    {"difficulty": "hard", "type": "multiple_choice", "questionText": "Welche Passiversatzform kann auch mit einem Dativobjekt verwendet werden?", "options": ["sein + zu + Infinitiv", "sich lassen + Infinitiv", "bleiben + past participle", "gehoeren + past participle"], "correctAnswer": "sich lassen + Infinitiv", "explanation": "'sich lassen' can be used with dative: 'Dem Patienten laesst sich helfen' = 'The patient can be helped'."},
    {"difficulty": "medium", "type": "multiple_choice", "questionText": "Ersetzen Sie das Passiv: 'Dieses Problem kann leicht geloest werden.' (mit 'lassen')", "options": ["Dieses Problem laesst sich leicht geloest.", "Dieses Problem laesst sich leicht loesen.", "Dieses Problem ist leicht zu loesen.", "Dieses Problem bleibt leicht geloest."], "correctAnswer": "Dieses Problem laesst sich leicht loesen.", "explanation": "'laesst sich leicht loesen' uses the infinitive 'loesen', not the past participle. The structure is 'sich lassen + Infinitiv'."},
    {"difficulty": "easy", "type": "multiple_choice", "questionText": "Welcher Satz ist KEINE Passiversatzform?", "options": ["Das Paket ist zu oeffnen.", "Das Paket laesst sich oeffnen.", "Das Paket wird geoeffnet.", "Das Paket bleibt geoeffnet."], "correctAnswer": "Das Paket wird geoeffnet.", "explanation": "'wird geoeffnet' is standard Vorgangspassiv, not an Ersatzform. The others are passive replacements (sein+zu, sich lassen, bleiben)."},
    {"difficulty": "medium", "type": "multiple_choice", "questionText": "Formen Sie um in eine Passiversatzform mit 'sich lassen': 'Diese Datei kann nicht wiederhergestellt werden.'", "options": ["Diese Datei ist nicht wiederherzustellen.", "Diese Datei laesst sich nicht wiederhergestellt.", "Diese Datei laesst sich nicht wiederherstellen.", "Diese Datei bleibt nicht wiederhergestellt."], "correctAnswer": "Diese Datei laesst sich nicht wiederherstellen.", "explanation": "'kann nicht wiederhergestellt werden' (possibility) → 'laesst sich nicht wiederherstellen' is the correct passive replacement using infinitive."},
    {"difficulty": "hard", "type": "multiple_choice", "questionText": "Was ist der Unterschied zwischen 'Das Geschaeft ist zu schliessen' und 'Das Geschaeft laesst sich schliessen'?", "options": ["Kein Unterschied.", "Ersteres druckt Notwendigkeit aus, letzteres Moeglichkeit.", "Ersteres ist Aktiv, letzteres Passiv.", "Ersteres ist Vergangenheit, letzteres Zukunft."], "correctAnswer": "Ersteres druckt Notwendigkeit aus, letzteres Moeglichkeit.", "explanation": "'ist zu schliessen' = must be closed (necessity). 'laesst sich schliessen' = can be closed (possibility). This is a key distinction."}
]

for i, q in enumerate(questions, start=1):
    q["id"] = f"c1_03_q{str(i).zfill(3)}"

data = {
    "version": "1.0",
    "subjectId": "c1_03",
    "topicName": "Passiversatzformen",
    "level": "C1",
    "totalQuestions": len(questions),
    "description": "Passiversatzformen — Passive replacement forms in German allow you to avoid standard Vorgangspassiv (werden + Partizip II) for stylistic variety. Key forms: (1) 'sein + zu + Infinitiv' = necessity/obligation (must be done); (2) 'sich lassen + Infinitiv' = possibility (can be done); (3) 'bleiben + Partizip II' = continuing state (remains done); (4) 'gehören + Partizip II' = regional necessity (southern Germany/Austria/Switzerland, e.g., 'Das gehört repariert' = needs to be repaired). These forms are essential for C1-level academic and journalistic writing.",
    "tips": [
        "Core distinction: 'sein + zu + Infinitiv' = necessity (müssen + Passiv). 'sich lassen + Infinitiv' = possibility (können + Passiv). 'Das ist zu tun' = must be done. 'Das lässt sich tun' = can be done.",
        "'sich lassen + Infinitiv' uses the INFINITIVE (not Partizip II): 'Die Tür lässt sich öffnen' (NOT 'die Tür lässt sich geöffnet').",
        "'bleiben + Partizip II' describes a RESULTING STATE: 'Das Problem bleibt ungelöst' (the problem remains unsolved). Unlike 'sein + Partizip II' (Zustandspassiv), 'bleiben' implies the state persists.",
        "'gehören + Partizip II' is REGIONAL (southern Germany, Austria, Switzerland). It means 'needs to be done' and sounds informal/native. Use it knowing it marks the speaker as southern.",
        "'sein + zu + Infinitiv' can be used with passive meaning AND dative objects: 'Dem Patienten ist nicht zu helfen' (the patient cannot be helped / one cannot help the patient).",
        "All passive replacements can be used in all tenses via Konjunktiv I/II: 'Das wäre zu überprüfen', 'Das war zu tun', 'Das wird zu erledigen sein'.",
        "Academic C1 writing tip: rotate between 'werden + Partizip II', 'sein + zu + Infinitiv', and adverbial/passive nominal phrases to create variety."
    ],
    "questions": questions
}

with open('app/src/main/assets/c1_03.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Created c1_03.json with {len(questions)} questions")
print(f"Topic: {data['topicName']}")
print(f"IDs: {data['questions'][0]['id']} — {data['questions'][-1]['id']}")
