#!/usr/bin/env python3
import json

with open('app/src/main/assets/c2_06.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

existing_count = len(data['questions'])
next_id = existing_count + 1

new_questions = []

def q(id_num, difficulty, questionText, options, correctAnswer, explanation):
    return {
        "id": f"c2_06_q{str(id_num).zfill(3)}",
        "subjectId": "c2_06",
        "topicName": "Funktionsverbgefuge",
        "questionText": questionText,
        "options": options,
        "correctAnswer": correctAnswer,
        "explanation": explanation,
        "difficulty": difficulty,
        "type": "multiple_choice"
    }

new_questions.extend([
    q(81, "easy",
      "Was ist ein Funktionsverbgefüge (FVG)?",
      ["Ein Verb, das allein als Vollverb eine vollständige Aussage macht",
       "Eine Verbindung aus einem bedeutungsarmen Verb und einem Nomen, die gemeinsam die Funktion eines Vollverbs übernehmen",
       "Ein zusammengesetztes Nomen aus zwei Substantiven",
       "Ein Modalverb in Kombination mit einem Infinitiv"],
      "Eine Verbindung aus einem bedeutungsarmen Verb und einem Nomen, die gemeinsam die Funktion eines Vollverbs übernehmen",
      "A Funktionsverbgefüge (support verb construction) consists of a semantically light verb (Funktionsverb) combined with a noun (often a nominalization), together expressing what a single full verb would otherwise convey. E.g. 'zur Anwendung bringen' = 'anwenden'. They are characteristic of formal, legal, and administrative German."),
    q(82, "easy",
      "Welches der folgenden Paare ist ein typisches Funktionsverbgefüge und sein Vollverb-Äquivalent?",
      ['„in Kraft treten" – „kraftvoll werden"',
       '„zur Kenntnis nehmen" – „kenntnisreich sein"',
       '„in Frage stellen" – „bezweifeln"',
       '„unter Druck setzen" – „drücken lernen"'],
      "„in Frage stellen" – „bezweifeln"",
      "'In Frage stellen' (to call into question / to challenge) is the Funktionsverbgefüge equivalent of 'bezweifeln'. 'Zur Kenntnis nehmen' ≠ 'kenntnisreich sein', and 'in Kraft treten' ≠ 'kraftvoll werden'. Only the third pair is correctly matched."),
    q(83, "easy",
      "Welches Verb ist ein typisches Funktionsverb in deutschen FVG?",
      ["schlafen", "bringen", "essen", "wachsen"],
      "bringen",
      "'Bringen' is one of the core Funktionsverben in German, forming constructions such as 'zur Anwendung bringen', 'zum Ausdruck bringen', 'in Einklang bringen', 'zur Geltung bringen'. Other typical Funktionsverben include 'kommen', 'stehen', 'stellen', 'nehmen', 'setzen', 'treten', 'gelangen', and 'finden'."),
    q(84, "easy",
      "Was bedeutet das Funktionsverbgefüge „zur Anwendung kommen"?",
      ["anwenden", "angewendet werden", "anwenden wollen", "zur Anwendung fehlen"],
      "angewendet werden",
      "'Zur Anwendung kommen' is the passive-equivalent FVG of 'anwenden'. FVG with 'kommen' typically express a passive or inchoative meaning: the subject undergoes the action rather than performing it. 'Zur Anwendung bringen' = active 'anwenden'; 'zur Anwendung kommen' = passive 'angewendet werden'."),
    q(85, "easy",
      "In welchem Texttyp sind Funktionsverbgefüge besonders häufig anzutreffen?",
      ["In Kinderbüchern und Märchen",
       "In informellen WhatsApp-Nachrichten",
       "In Gesetzestexten, Verträgen und behördlichen Schreiben",
       "In lyrischen Gedichten"],
      "In Gesetzestexten, Verträgen und behördlichen Schreiben",
      "FVG are a hallmark of formal, legal, and administrative language. Legal texts ('Zur Anzeige bringen', 'in Kraft setzen', 'Klage erheben') and official correspondence rely heavily on FVG as standardized formulations."),
    q(86, "easy",
      "Ergänzen Sie das Funktionsverbgefüge: „Das Gericht brachte das Urteil zur ____.",
      ["Kenntnis", "Verkündung", "Anwendung", "Sprache"],
      "Verkündung",
      "'Zur Verkündung bringen' (to pronounce / to announce officially) is the correct legal FVG here. 'Zur Kenntnis bringen' = to inform; 'zur Anwendung bringen' = to apply; 'zur Sprache bringen' = to bring up a topic."),
    q(87, "medium",
      "Welches Vollverb entspricht dem FVG „eine Entscheidung treffen"?",
      ["entschlagen", "entscheiden", "beschließen oder entscheiden", "treffen"],
      "beschließen oder entscheiden",
      "'Eine Entscheidung treffen' is the FVG equivalent of 'entscheiden' or 'beschließen'. The Funktionsverb 'treffen' here is semantically light (it does not mean 'to hit' or 'to meet'). Both are accepted full-verb equivalents."),
    q(88, "medium",
      "Was ist der Unterschied zwischen „einen Antrag stellen" und „einen Antrag einreichen"?",
      ["„Einen Antrag stellen" ist ein FVG; „einen Antrag einreichen" ist ein Vollverb mit Objekt — beide bedeuten dasselbe im formellen Kontext.",
       "„Einen Antrag stellen" bedeutet, einen Antrag abzulehnen.",
       "„Einen Antrag einreichen" ist umgangssprachlich; „stellen" ist korrekt.",
       "Nur „stellen" ist juristisch korrekt; „einreichen" ist ein Grammatikfehler."],
      "„Einen Antrag stellen" ist ein FVG; „einen Antrag einreichen" ist ein Vollverb mit Objekt — beide bedeuten dasselbe im formellen Kontext.",
      "'Einen Antrag stellen' is the classic FVG (stellen = Funktionsverb). 'Einen Antrag einreichen' uses 'einreichen' as a full verb. Both are correct in formal/legal contexts."),
    q(89, "medium",
      "Welches Funktionsverbgefüge kann „informieren" ersetzen?",
      ["in Kenntnis setzen", "unter Kenntnis bringen", "zur Kenntnis kommen", "mit Kenntnis stehen"],
      "in Kenntnis setzen",
      "'In Kenntnis setzen' (to inform / to notify) is the established FVG for 'informieren'. 'Zur Kenntnis nehmen' means 'to take note of', not 'to inform'. The other options are not established FVG."),
    q(90, "medium",
      "Ergänzen Sie den formellen Satz: „Die Behörde hat gegen den Bescheid Einspruch ____.",
      ["gestellt", "erhoben", "genommen", "gebracht"],
      "erhoben",
      "'Einspruch erheben' (to lodge an objection / to appeal) is the fixed legal FVG. Other legal FVG with 'erheben': 'Klage erheben', 'Anklage erheben', 'Beschwerde erheben'. 'Stellen', 'nehmen', and 'bringen' do not collocate with 'Einspruch'."),
    q(91, "medium",
      "Welches FVG drückt aktive Handlung aus, welches eine passiv-ähnliche Bedeutung? „zur Geltung bringen" / „zur Geltung kommen"",
      ["Beide drücken passive Bedeutung aus.",
       "„zur Geltung bringen" = aktiv (etwas durchsetzen); „zur Geltung kommen" = passiv-ähnlich (zur Wirkung gelangen)",
       "„zur Geltung kommen" = aktiv; „zur Geltung bringen" = passiv",
       "Beide drücken aktive Bedeutung aus."],
      "„zur Geltung bringen" = aktiv (etwas durchsetzen); „zur Geltung kommen" = passiv-ähnlich (zur Wirkung gelangen)",
      "FVG with 'bringen' are active/causative; FVG with 'kommen' are inchoative/passive-like. This parallel structure is a systematic feature of formal German FVG."),
    q(92, "medium",
      "Welcher Satz enthält ein korrekt verwendetes juristisches Funktionsverbgefüge?",
      ["Der Anwalt hat die Klage erhoben.",
       "Der Anwalt hat die Klage gemacht.",
       "Der Anwalt hat die Klage gesagt.",
       "Der Anwalt hat die Klage gehabt."],
      "Der Anwalt hat die Klage erhoben.",
      "'Klage erheben' is a fixed legal FVG meaning 'to file a lawsuit'. 'Erheben' is the established Funktionsverb. 'Machen', 'sagen', and 'haben' are not Funktionsverben for 'Klage' and produce non-standard results."),
    q(93, "medium",
      "Ergänzen Sie den juristischen Satz: „Das Gesetz tritt am 1. Januar in ____.",
      ["Geltung", "Kraft", "Wirkung", "Anwendung"],
      "Kraft",
      "'In Kraft treten' (to come into force) is the standard legal FVG for legislation entering into force. It is among the most frequently used FVG in German legal language."),
    q(94, "hard",
      "Welches ist das korrekte Funktionsverbgefüge für „berücksichtigen" im juristisch-formellen Register?",
      ["in Berücksichtigung nehmen", "Berücksichtigung finden", "zur Berücksichtigung kommen", "mit Berücksichtigung bringen"],
      "Berücksichtigung finden",
      "'Berücksichtigung finden' is the correct formal/legal FVG for 'berücksichtigt werden' (to be taken into consideration). 'Finden' is a productive Funktionsverb: 'Anwendung finden', 'Erwähnung finden', 'Berücksichtigung finden'."),
    q(95, "hard",
      "Ergänzen Sie den Vertragssatz: „Die Vertragsparteien kommen überein, dass strittige Punkte einer gütlichen Einigung ____ sollen.",
      ["zugeführt werden", "zugeführt bekommen", "zugeführt nehmen", "in Zuführung kommen"],
      "zugeführt werden",
      "'Einer gütlichen Einigung zugeführt werden' (to be brought to an amicable resolution) is a formal legal passive construction. 'Zuführen' (to lead/bring to) functions as the support verb."),
    q(96, "hard",
      "Welche stilistische Kritik wird an einem übermäßigen Gebrauch von Funktionsverbgefügen in Rechtstexten geäußert?",
      ["FVG sind grammatikalisch inkorrekt und sollten vermieden werden.",
       "FVG sind zu kurz und liefern zu wenig Information.",
       "FVG können Texte aufblähen, Handelnde verschleiern und die Verständlichkeit für Laien erheblich reduzieren.",
       "FVG sind ausschließlich in der Umgangssprache verbreitet und wirken in Rechtstexten deplatziert."],
      "FVG können Texte aufblähen, Handelnde verschleiern und die Verständlichkeit für Laien erheblich reduzieren.",
      "Excessive FVG use creates 'Bürokratendeutsch' (bureaucratic German): they inflate sentence length, obscure agency, and reduce accessibility for non-specialists."),
    q(97, "hard",
      "Welches FVG ist das korrekte formelle Äquivalent zu „etwas beschleunigen"?",
      ["in Beschleunigung bringen", "Beschleunigung erfahren", "einer Beschleunigung zuführen", "unter Beschleunigung stellen"],
      "einer Beschleunigung zuführen",
      "'Einer Beschleunigung zuführen' follows the formal FVG pattern: dative article + nominalization + 'zuführen'. This is a productive pattern in official language: 'einer Lösung zuführen', 'einer Klärung zuführen', 'einer Prüfung zuführen'."),
    q(98, "hard",
      "Analysieren Sie den folgenden Satz: „Der Vorstand hat Beschluss gefasst, das Verfahren zum Abschluss zu bringen und alle Beteiligten in Kenntnis zu setzen." + " Welche Ausdrücke sind FVG?",
      ["Nur „Beschluss fassen" ist ein FVG; die anderen Ausdrücke sind Vollverben.",
       "„Beschluss fassen", „zum Abschluss bringen" und „in Kenntnis setzen" sind alle drei Funktionsverbgefüge.",
       "„Zum Abschluss bringen" und „in Kenntnis setzen" sind FVG; „Beschluss fassen" ist ein idiomatischer Ausdruck.",
       "Keiner der Ausdrücke ist ein Funktionsverbgefüge."],
      "„Beschluss fassen", „zum Abschluss bringen" und „in Kenntnis setzen" sind alle drei Funktionsverbgefüge.",
      "All three are FVG: (1) 'Beschluss fassen' = 'beschließen'; (2) 'zum Abschluss bringen' = 'abschließen/beenden'; (3) 'in Kenntnis setzen' = 'informieren'. This sentence is a typical example of FVG-dense formal administrative German."),
    q(99, "hard",
      "Welcher Satz verwendet das Funktionsverbgefüge „in Anspruch nehmen" korrekt im rechtlichen Sinne?",
      ["Der Kläger nahm das Gericht in Anspruch, weil er keine Zeit hatte.",
       "Der Beklagte nahm sein Recht auf rechtliches Gehör in Anspruch.",
       "Das Gericht nahm die Zeugen in Anspruch, damit sie schwiegen.",
       "Der Richter nahm das Urteil in Anspruch."],
      "Der Beklagte nahm sein Recht auf rechtliches Gehör in Anspruch.",
      "'In Anspruch nehmen' in legal language means 'to exercise / to invoke a right or service'. Correct usage is with rights, entitlements, or services as the object: 'ein Recht in Anspruch nehmen', 'Hilfe in Anspruch nehmen'."),
    q(100, "hard",
      "Welche der folgenden Aussagen über Funktionsverbgefüge ist FALSCH?",
      ["FVG bestehen aus einem semantisch abgeschwächten Verb und einem nominalen Element, das den eigentlichen Handlungsinhalt trägt.",
       "FVG mit „kommen" drücken oft eine passiv-ähnliche oder inchoative Bedeutung aus, FVG mit „bringen" eher eine aktiv-kausative.",
       "Alle Funktionsverbgefüge sind vollständig durch ein einziges Vollverb ersetzbar, ohne dass ein Bedeutungsunterschied entsteht.",
       "FVG erlauben durch das nominale Element eine attributive Erweiterung, die bei einem einfachen Vollverb nicht möglich wäre."],
      "Alle Funktionsverbgefüge sind vollständig durch ein einziges Vollverb ersetzbar, ohne dass ein Bedeutungsunterschied entsteht.",
      "This is FALSE. FVG are not always perfectly interchangeable with full verbs. They carry additional nuances: aspectual distinctions, register formality, agent visibility, and attributive expandability (e.g., 'eine endgültige Entscheidung treffen' vs. *'endgültig entscheiden')."),
])

data['questions'].extend(new_questions)
data['totalQuestions'] = len(data['questions'])

print(f"Added {len(new_questions)} questions. New total: {data['totalQuestions']}")
print(f"Last ID: {data['questions'][-1]['id']}")

with open('app/src/main/assets/c2_06.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("c2_06.json updated successfully")